In [2]:
import pandas as pd
import numpy as np

# Creating a dataframe from an array

## Option 1

In [3]:
# creating an array
data = np.array([[1,4], [2,5], [3,6]])

In [4]:
# creating a dataframe
df = pd.DataFrame(data,
             index = ["row1","row2", "row3"],
             columns=["col1", "col2"])

In [5]:
# showing the data frame
df

      col1  col2
row1     1     4
row2     2     5
row3     3     6

## Option 2

In [6]:
# creating an array with list shape
data2 = [[1,4], [2,5], [3,6]]

In [7]:
# creating a dataframe
df2 = pd.DataFrame(data2,
                  index = ["row1","row2", "row3"],
                  columns=["col1", "col2"])

In [8]:
# showing the dataframe
df2

      col1  col2
row1     1     4
row2     2     5
row3     3     6

# Creating a DataFrame from a dictionary

In [9]:
# list used for this example
states = ["Texas", "Georgia", "Michigan","Florida"]

population = [12345678, 59874635, 8749587, 94536125]

In [10]:
# sorting lists within a dictionary
dict_states = {'States':states, 'Population':population}

In [11]:
# Creating the dataframe
df_states = pd.DataFrame(dict_states)

In [12]:
# Showing the dataframe
df_states

     States  Population
0     Texas    12345678
1   Georgia    59874635
2  Michigan     8749587
3   Florida    94536125

# Creating a DataFrame from a csv file

In [13]:
# Reading the csv file
df_exams = pd.read_csv('StudentsPerformance.csv')

In [14]:
# showing the 5 rows of dataframe 
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [15]:
# show dataframe
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [16]:
# show last 5 rows of dataframe
df_exams.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [17]:
# show first n rows in dataframe
df_exams.head(7)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92

In [18]:
# show last n rows in dataframe
df_exams.tail(8)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
992,female,group D,associate's degree,free/reduced,none,55,76,76
993,female,group D,bachelor's degree,free/reduced,none,62,72,74
994,male,group A,high school,standard,none,63,63,62
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [19]:
# shape of dataframe
df_exams.shape

(1000, 8)

In [20]:
# size of dataframe
df_exams.size

8000

In [21]:
# changing pandas behavior
pd.set_option('display.max_rows', 1000)
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50
10,male,group C,associate's degree,standard,none,58,54,52
11,male,group D,associate's degree,standard,none,40,52,43
12,female,group B,high school,standard,none,65,81,73
13,male,group A,some college,standard,completed,78,72,70
14,female,group A,master's degree,standard,none,50,53,58
15,female,group C,some high school,standard,none,69,75,78
16,male,group C,high school,standard,none,88,89,86
17,female,group B,some high school,free/reduced,none,18,32,28
18,male,group C,master's degree,free/reduced,completed,46,42,46
19,female,group C,associate's degree,free/reduced,none,54,58,61
20,male,group D,high school,standard,none,66,69,63
21,female,group B,some college,free/reduced,completed,65,75,70
22,male,group D,some college,standard,none,44,54,53
23,female,group C,some high school,standard,none,69,73,73
24,male,group D,bachelor's degree,free/reduced,completed,74,71,80
25,male,group A,master's degree,free/reduced,none,73,74,72
26,male,group B,some college,standard,none,69,54,55
27,female,group C,bachelor's degree,standard,none,67,69,75
28,male,group C,high school,standard,none,70,70,65
29,female,group D,master's degree,standard,none,62,70,75
30,female,group D,some college,standard,none,69,74,74
31,female,group B,some college,standard,none,63,65,61
32,female,group E,master's degree,free/reduced,none,56,72,65
33,male,group D,some college,standard,none,40,42,38
34,male,group E,some college,standard,none,97,87,82
35,male,group E,associate's degree,standard,completed,81,81,79
36,female,group D,associate's degree,standard,none,74,81,83
37,female,group D,some high school,free/reduced,none,50,64,59
38,female,group D,associate's degree,free/reduced,completed,75,90,88
39,male,group B,associate's degree,free/reduced,none,57,56,57
40,male,group C,associate's degree,free/reduced,none,55,61,54
41,female,group C,associate's degree,standard,none,58,73,68
42,female,group B,associate's degree,standard,none,53,58,65
43,male,group B,some college,free/reduced,completed,59,65,66
44,female,group E,associate's degree,free/reduced,none,50,56,54
45,male,group B,associate's degree,standard,none,65,54,57
46,female,group A,associate's degree,standard,completed,55,65,62
47,female,group C,high school,standard,none,66,71,76
48,female,group D,associate's degree,free/reduced,completed,57,74,76
49,male,group C,high school,standard,completed,82,84,82
50,male,group E,some college,standard,none,53,55,48
51,male,group E,associate's degree,free/reduced,completed,77,69,68
52,male,group C,some college,standard,none,53,44,42
53,male,group D,high school,standard,none,88,78,75
54,female,group C,some high school,free/reduced,completed,71,84,87
55,female,group C,high school,free/reduced,none,33,41,43
56,female,group E,associate's degree,standard,completed,82,85,86
57,male,group D,associate's degree,standard,none,52,55,49
58,male,group D,some college,standard,completed,58,59,58
59,female,group C,some high school,free/reduced,none,0,17,10
60,male,group E,bachelor's degree,free/reduced,completed,79,74,72
61,male,group A,some high school,free/reduced,none,39,39,34
62,male,group A,associate's degree,free/reduced,none,62,61,55
63,female,group C,associate's degree,standard,none,69,80,71
64,female,group D,some high school,standard,none,59,58,59
65,male,group B,some high school,standard,none,67,64,61
66,male,group D,some high school,free/reduced,none,45,37,37
67,female,group C,some college,standard,none,60,72,74
68,male,group B,associate's degree,free/reduced,none,61,58,56
69,female,group C,associate's degree,standard,none,39,64,57
70,female,group D,some college,free/reduced,completed,58,63,73
71,male,group D,some college,standard,completed,63,55,63
72,female,group A,associate's degree,free/reduced,none,41,51,48
73,male,group C,some high school,free/reduced,none,61,57,56
74,male,group C,some high school,standard,none,49,49,41
75,male,group B,associate's degree,free/reduced,none,44,41,38
76,male,group E,some high school,standard,none,30,26,22
77,male,group A,bachelor's degree,standard,completed,80,78,81
78,female,group D,some high school,standard,completed,61,74,72
79,female,group E,master's degree,standard,none,62,68,68
80,female,group B,associate's degree,standard,none,47,49,50
81,male,group B,high school,free/reduced,none,49,45,45
82,male,group A,some college,free/reduced,completed,50,47,54
83,male,group E,associate's degree,standard,none,72,64,63
84,male,group D,high school,free/reduced,none,42,39,34
85,female,group C,some college,standard,none,73,80,82
86,female,group C,some college,free/reduced,none,76,83,88
87,female,group D,associate's degree,standard,none,71,71,74
88,female,group A,some college,standard,none,58,70,67
89,female,group D,some high school,standard,none,73,86,82
90,female,group C,bachelor's degree,standard,none,65,72,74
91,male,group C,high school,free/reduced,none,27,34,36
92,male,group C,high school,standard,none,71,79,71
93,male,group C,associate's degree,free/reduced,completed,43,45,50
94,female,group B,some college,standard,none,79,86,92
95,male,group C,associate's degree,free/reduced,completed,78,81,82
96,male,group B,some high school,standard,completed,65,66,62
97,female,group E,some college,standard,completed,63,72,70
98,female,group D,some college,free/reduced,none,58,67,62
99,female,group D,bachelor's degree,standard,none,65,67,62
100,male,group B,some college,standard,none,79,67,67
101,male,group D,bachelor's degree,standard,completed,68,74,74
102,female,group D,associate's degree,standard,none,85,91,89
103,male,group B,high school,standard,completed,60,44,47
104,male,group C,some college,standard,completed,98,86,90
105,female,group C,some college,standard,none,58,67,72
106,female,group D,master's degree,standard,none,87,100,100
107,male,group E,associate's degree,standard,completed,66,63,64
108,female,group B,associate's degree,free/reduced,none,52,76,70
109,female,group B,some high school,standard,none,70,64,72
110,female,group D,associate's degree,free/reduced,completed,77,89,98
111,male,group C,high school,standard,none,62,55,49
112,male,group A,associate's degree,standard,none,54,53,47
113,female,group D,some college,standard,none,51,58,54
114,female,group E,bachelor's degree,standard,completed,99,100,100
115,male,group C,high school,standard,none,84,77,74
116,female,group B,bachelor's degree,free/reduced,none,75,85,82
117,female,group D,bachelor's degree,standard,none,78,82,79
118,female,group D,some high school,standard,none,51,63,61
119,female,group C,some college,standard,none,55,69,65
120,female,group C,bachelor's degree,standard,completed,79,92,89
121,male,group B,associate's degree,standard,completed,91,89,92
122,female,group C,some college,standard,completed,88,93,93
123,male,group D,high school,free/reduced,none,63,57,56
124,male,group E,some college,standard,none,83,80,73
125,female,group B,high school,standard,none,87,95,86
126,male,group B,some high school,standard,none,72,68,67
127,male,group D,some college,standard,completed,65,77,74
128,male,group D,master's degree,standard,none,82,82,74
129,female,group A,bachelor's degree,standard,none,51,49,51
130,male,group D,master's degree,standard,none,89,84,82
131,male,group C,some high school,free/reduced,completed,53,37,40
132,male,group E,some college,free/reduced,completed,87,74,70
133,female,group C,some college,standard,completed,75,81,84
134,male,group D,bachelor's degree,free/reduced,completed,74,79,75
135,male,group C,bachelor's degree,standard,none,58,55,48
136,male,group B,some high school,standard,completed,51,54,41
137,male,group E,high school,standard,none,70,55,56
138,female,group C,associate's degree,standard,none,59,66,67
139,male,group D,some college,standard,completed,71,61,69
140,female,group D,some high school,standard,none,76,72,71
141,female,group C,some college,free/reduced,none,59,62,64
142,female,group E,some college,free/reduced,completed,42,55,54
143,male,group A,high school,standard,none,57,43,47
144,male,group D,some college,standard,none,88,73,78
145,female,group C,some college,free/reduced,none,22,39,33
146,male,group B,some high school,standard,none,88,84,75
147,male,group C,associate's degree,free/reduced,none,73,68,66
148,female,group D,bachelor's degree,standard,completed,68,75,81
149,male,group E,associate's degree,free/reduced,completed,100,100,93
150,male,group A,some high school,standard,completed,62,67,69
151,male,group A,bachelor's degree,standard,none,77,67,68
152,female,group B,associate's degree,standard,completed,59,70,66
153,male,group D,bachelor's degree,standard,none,54,49,47
154,male,group D,some high school,standard,none,62,67,61
155,female,group C,some college,standard,completed,70,89,88
156,female,group E,high school,free/reduced,completed,66,74,78
157,male,group B,some college,free/reduced,none,60,60,60
158,female,group B,associate's degree,standard,completed,61,86,87
159,male,group D,associate's degree,free/reduced,none,66,62,64
160,male,group B,associate's degree,free/reduced,completed,82,78,74
161,female,group E,some college,free/reduced,completed,75,88,85
162,male,group B,master's degree,free/reduced,none,49,53,52
163,male,group C,high school,standard,none,52,53,49
164,female,group E,master's degree,standard,none,81,92,91
165,female,group C,bachelor's degree,standard,completed,96,100,100
166,male,group C,high school,free/reduced,completed,53,51,51
167,female,group B,master's degree,free/reduced,completed,58,76,78
168,female,group B,high school,standard,completed,68,83,78
169,female,group C,some college,free/reduced,completed,67,75,70
170,male,group A,high school,standard,completed,72,73,74
171,male,group E,some high school,standard,none,94,88,78
172,female,group D,some college,standard,none,79,86,81
173,female,group C,associate's degree,standard,none,63,67,70
174,female,group C,bachelor's degree,free/reduced,completed,43,51,54
175,female,group C,master's degree,standard,completed,81,91,87
176,female,group B,high school,free/reduced,completed,46,54,58
177,female,group C,associate's degree,standard,completed,71,77,77
178,female,group B,master's degree,free/reduced,completed,52,70,62
179,female,group D,some high school,standard,completed,97,100,100
180,male,group C,master's degree,free/reduced,completed,62,68,75
181,female,group C,some college,free/reduced,none,46,64,66
182,female,group E,high school,standard,none,50,50,47
183,female,group D,associate's degree,standard,none,65,69,70
184,male,group C,some high school,free/reduced,completed,45,52,49
185,male,group C,associate's degree,free/reduced,completed,65,67,65
186,male,group E,high school,standard,none,80,76,65
187,male,group D,some high school,standard,completed,62,66,68
188,male,group B,some high school,free/reduced,none,48,52,45
189,female,group C,bachelor's degree,standard,none,77,88,87
190,female,group E,associate's degree,standard,none,66,65,69
191,male,group D,some college,standard,completed,76,83,79
192,female,group B,some high school,standard,none,62,64,66
193,male,group D,some college,standard,completed,77,62,62
194,female,group C,master's degree,standard,completed,69,84,85
195,male,group D,associate's degree,standard,none,61,55,52
196,male,group C,some high school,free/reduced,completed,59,69,65
197,male,group E,high school,free/reduced,none,55,56,51
198,female,group B,some college,free/reduced,none,45,53,55
199,female,group B,bachelor's degree,free/reduced,none,78,79,76
200,female,group C,associate's degree,standard,completed,67,84,86
201,female,group D,some college,free/reduced,none,65,81,77
202,male,group C,associate's degree,standard,none,69,77,69
203,female,group B,associate's degree,standard,none,57,69,68
204,male,group C,some college,standard,none,59,41,42
205,male,group D,some high school,standard,completed,74,71,78
206,male,group E,bachelor's degree,standard,none,82,62,62
207,male,group E,high school,standard,completed,81,80,76
208,female,group B,some college,free/reduced,none,74,81,76
209,female,group B,some college,free/reduced,none,58,61,66
210,male,group D,some high school,free/reduced,completed,80,79,79
211,male,group C,some college,free/reduced,none,35,28,27
212,female,group C,high school,free/reduced,none,42,62,60
213,male,group C,associate's degree,free/reduced,completed,60,51,56
214,male,group E,high school,standard,completed,87,91,81
215,male,group B,some high school,standard,completed,84,83,75
216,female,group E,associate's degree,free/reduced,completed,83,86,88
217,female,group C,high school,free/reduced,none,34,42,39
218,male,group B,high school,free/reduced,none,66,77,70
219,male,group B,some high school,standard,completed,61,56,56
220,female,group D,high school,standard,completed,56,68,74
221,male,group B,associate's degree,standard,none,87,85,73
222,female,group C,some high school,free/reduced,none,55,65,62
223,male,group D,some high school,standard,none,86,80,75
224,female,group B,associate's degree,standard,completed,52,66,73
225,female,group E,master's degree,free/reduced,none,45,56,54
226,female,group C,some college,standard,none,72,72,71
227,male,group D,high school,standard,none,57,50,54
228,male,group A,some high school,free/reduced,none,68,72,64
229,female,group C,some college,standard,completed,88,95,94
230,male,group D,some college,standard,none,76,64,66
231,male,group C,associate's degree,standard,none,46,43,42
232,female,group B,bachelor's degree,standard,none,67,86,83
233,male,group E,some high school,standard,none,92,87,78
234,male,group C,bachelor's degree,standard,completed,83,82,84
235,male,group D,associate's degree,standard,none,80,75,77
236,male,group D,bachelor's degree,free/reduced,none,63,66,67
237,female,group D,some high school,standard,completed,64,60,74
238,male,group B,some college,standard,none,54,52,51
239,male,group C,associate's degree,standard,none,84,80,80
240,male,group D,high school,free/reduced,completed,73,68,66
241,female,group E,bachelor's degree,standard,none,80,83,83
242,female,group D,high school,standard,none,56,52,55
243,male,group E,some college,standard,none,59,51,43
244,male,group D,some high school,standard,none,75,74,69
245,male,group C,associate's degree,standard,none,85,76,71
246,male,group E,associate's degree,standard,none,89,76,74
247,female,group B,high school,standard,completed,58,70,68
248,female,group B,high school,standard,none,65,64,62
249,male,group C,high school,standard,none,68,60,53
250,male,group A,some high school,standard,completed,47,49,49
251,female,group D,some college,free/reduced,none,71,83,83
252,female,group B,some high school,standard,completed,60,70,70
253,male,group D,master's degree,standard,none,80,80,72
254,male,group D,high school,standard,none,54,52,52
255,female,group E,some college,standard,none,62,73,70
256,female,group C,associate's degree,free/reduced,none,64,73,68
257,male,group C,associate's degree,standard,completed,78,77,77
258,female,group B,some college,standard,none,70,75,78
259,female,group C,master's degree,free/reduced,completed,65,81,81
260,female,group C,some high school,free/reduced,completed,64,79,77
261,male,group C,some college,standard,completed,79,79,78
262,female,group C,some high school,free/reduced,none,44,50,51
263,female,group E,high school,standard,none,99,93,90
264,male,group D,high school,standard,none,76,73,68
265,male,group D,some high school,free/reduced,none,59,42,41
266,female,group C,bachelor's degree,standard,none,63,75,81
267,female,group D,high school,standard,none,69,72,77
268,female,group D,associate's degree,standard,completed,88,92,95
269,female,group E,some college,free/reduced,none,71,76,70
270,male,group C,bachelor's degree,standard,none,69,63,61
271,male,group C,some college,standard,none,58,49,42
272,female,group D,associate's degree,free/reduced,none,47,53,58
273,female,group D,some college,standard,none,65,70,71
274,male,group B,some college,standard,completed,88,85,76
275,male,group C,bachelor's degree,standard,none,83,78,73
276,female,group C,some high school,standard,completed,85,92,93
277,female,group E,high school,standard,completed,59,63,75
278,female,group C,some high school,free/reduced,none,65,86,80
279,male,group B,bachelor's degree,free/reduced,none,73,56,57
280,male,group D,high school,standard,none,53,52,42
281,male,group D,high school,standard,none,45,48,46
282,female,group D,bachelor's degree,free/reduced,none,73,79,84
283,female,group D,some college,free/reduced,completed,70,78,78
284,female,group B,some high school,standard,none,37,46,46
285,male,group B,associate's degree,standard,completed,81,82,82
286,male,group E,associate's degree,standard,completed,97,82,88
287,female,group B,some high school,standard,none,67,89,82
288,male,group B,bachelor's degree,free/reduced,none,88,75,76
289,male,group E,some high school,standard,completed,77,76,77
290,male,group C,associate's degree,standard,none,76,70,68
291,male,group D,some high school,standard,none,86,73,70
292,male,group C,some high school,standard,completed,63,60,57
293,female,group E,bachelor's degree,standard,none,65,73,75
294,male,group D,high school,free/reduced,completed,78,77,80
295,male,group B,associate's degree,free/reduced,none,67,62,60
296,male,group A,some high school,standard,completed,46,41,43
297,male,group E,associate's degree,standard,completed,71,74,68
298,male,group C,high school,free/reduced,completed,40,46,50
299,male,group D,associate's degree,free/reduced,none,90,87,75
300,male,group A,some college,free/reduced,completed,81,78,81
301,male,group D,some high school,free/reduced,none,56,54,52
302,female,group C,associate's degree,standard,completed,67,84,81
303,male,group B,associate's degree,standard,none,80,76,64
304,female,group C,associate's degree,standard,completed,74,75,83
305,male,group A,some college,standard,none,69,67,69
306,male,group E,some college,standard,completed,99,87,81
307,male,group C,some high school,standard,none,51,52,44
308,female,group B,associate's degree,free/reduced,none,53,71,67
309,female,group D,high school,free/reduced,none,49,57,52
310,female,group B,associate's degree,standard,none,73,76,80
311,male,group B,bachelor's degree,standard,none,66,60,57
312,male,group D,bachelor's degree,standard,completed,67,61,68
313,female,group C,associate's degree,free/reduced,completed,68,67,69
314,female,group C,bachelor's degree,standard,completed,59,64,75
315,male,group C,high school,standard,none,71,66,65
316,female,group D,master's degree,standard,completed,77,82,91
317,male,group C,associate's degree,standard,none,83,72,78
318,male,group B,bachelor's degree,standard,none,63,71,69
319,female,group D,associate's degree,free/reduced,none,56,65,63
320,female,group C,high school,free/reduced,completed,67,79,84
321,female,group E,high school,standard,none,75,86,79
322,female,group C,some college,standard,none,71,81,80
323,female,group C,some high school,free/reduced,none,43,53,53
324,female,group C,high school,free/reduced,none,41,46,43
325,female,group C,some college,standard,none,82,90,94
326,male,group C,some college,standard,none,61,61,62
327,male,group A,some college,free/reduced,none,28,23,19
328,male,group C,associate's degree,standard,completed,82,75,77
329,female,group B,some high school,standard,none,41,55,51
330,male,group C,high school,standard,none,71,60,61
331,male,group C,associate's degree,standard,none,47,37,35
332,male,group E,associate's degree,standard,completed,62,56,53

# Attributes

In [22]:
# get shape of a dataframe
df_exams.shape

(1000, 8)

In [23]:
#get index of dataframe
df_exams.index
# index range adds 1 for the header

RangeIndex(start=0, stop=1000, step=1)

In [24]:
df_exams.head(0)

Empty DataFrame
Columns: [gender, race/ethnicity, parental level of education, lunch, test preparation course, math score, reading score, writing score]
Index: []

In [25]:
# get column names
df_exams.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [26]:
df_exams.dtypes

gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object

# Methods

In [27]:
# first 5 columns
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [28]:
#show info of dataframe
df_exams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [29]:
# describing basic stats of dataframe
df_exams.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

# Functions

In [30]:
# length of dataframe
len(df_exams)

1000

In [31]:
# highest index of dataframe
max(df_exams.index)

999

In [32]:
# lowest index of dataframe
min(df_exams.index)

0

In [33]:
# type of dataframe
type(df_exams)

pandas.core.frame.DataFrame

In [34]:
# rounding the values of the dataset
round(df_exams,2)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50
10,male,group C,associate's degree,standard,none,58,54,52
11,male,group D,associate's degree,standard,none,40,52,43
12,female,group B,high school,standard,none,65,81,73
13,male,group A,some college,standard,completed,78,72,70
14,female,group A,master's degree,standard,none,50,53,58
15,female,group C,some high school,standard,none,69,75,78
16,male,group C,high school,standard,none,88,89,86
17,female,group B,some high school,free/reduced,none,18,32,28
18,male,group C,master's degree,free/reduced,completed,46,42,46
19,female,group C,associate's degree,free/reduced,none,54,58,61
20,male,group D,high school,standard,none,66,69,63
21,female,group B,some college,free/reduced,completed,65,75,70
22,male,group D,some college,standard,none,44,54,53
23,female,group C,some high school,standard,none,69,73,73
24,male,group D,bachelor's degree,free/reduced,completed,74,71,80
25,male,group A,master's degree,free/reduced,none,73,74,72
26,male,group B,some college,standard,none,69,54,55
27,female,group C,bachelor's degree,standard,none,67,69,75
28,male,group C,high school,standard,none,70,70,65
29,female,group D,master's degree,standard,none,62,70,75
30,female,group D,some college,standard,none,69,74,74
31,female,group B,some college,standard,none,63,65,61
32,female,group E,master's degree,free/reduced,none,56,72,65
33,male,group D,some college,standard,none,40,42,38
34,male,group E,some college,standard,none,97,87,82
35,male,group E,associate's degree,standard,completed,81,81,79
36,female,group D,associate's degree,standard,none,74,81,83
37,female,group D,some high school,free/reduced,none,50,64,59
38,female,group D,associate's degree,free/reduced,completed,75,90,88
39,male,group B,associate's degree,free/reduced,none,57,56,57
40,male,group C,associate's degree,free/reduced,none,55,61,54
41,female,group C,associate's degree,standard,none,58,73,68
42,female,group B,associate's degree,standard,none,53,58,65
43,male,group B,some college,free/reduced,completed,59,65,66
44,female,group E,associate's degree,free/reduced,none,50,56,54
45,male,group B,associate's degree,standard,none,65,54,57
46,female,group A,associate's degree,standard,completed,55,65,62
47,female,group C,high school,standard,none,66,71,76
48,female,group D,associate's degree,free/reduced,completed,57,74,76
49,male,group C,high school,standard,completed,82,84,82
50,male,group E,some college,standard,none,53,55,48
51,male,group E,associate's degree,free/reduced,completed,77,69,68
52,male,group C,some college,standard,none,53,44,42
53,male,group D,high school,standard,none,88,78,75
54,female,group C,some high school,free/reduced,completed,71,84,87
55,female,group C,high school,free/reduced,none,33,41,43
56,female,group E,associate's degree,standard,completed,82,85,86
57,male,group D,associate's degree,standard,none,52,55,49
58,male,group D,some college,standard,completed,58,59,58
59,female,group C,some high school,free/reduced,none,0,17,10
60,male,group E,bachelor's degree,free/reduced,completed,79,74,72
61,male,group A,some high school,free/reduced,none,39,39,34
62,male,group A,associate's degree,free/reduced,none,62,61,55
63,female,group C,associate's degree,standard,none,69,80,71
64,female,group D,some high school,standard,none,59,58,59
65,male,group B,some high school,standard,none,67,64,61
66,male,group D,some high school,free/reduced,none,45,37,37
67,female,group C,some college,standard,none,60,72,74
68,male,group B,associate's degree,free/reduced,none,61,58,56
69,female,group C,associate's degree,standard,none,39,64,57
70,female,group D,some college,free/reduced,completed,58,63,73
71,male,group D,some college,standard,completed,63,55,63
72,female,group A,associate's degree,free/reduced,none,41,51,48
73,male,group C,some high school,free/reduced,none,61,57,56
74,male,group C,some high school,standard,none,49,49,41
75,male,group B,associate's degree,free/reduced,none,44,41,38
76,male,group E,some high school,standard,none,30,26,22
77,male,group A,bachelor's degree,standard,completed,80,78,81
78,female,group D,some high school,standard,completed,61,74,72
79,female,group E,master's degree,standard,none,62,68,68
80,female,group B,associate's degree,standard,none,47,49,50
81,male,group B,high school,free/reduced,none,49,45,45
82,male,group A,some college,free/reduced,completed,50,47,54
83,male,group E,associate's degree,standard,none,72,64,63
84,male,group D,high school,free/reduced,none,42,39,34
85,female,group C,some college,standard,none,73,80,82
86,female,group C,some college,free/reduced,none,76,83,88
87,female,group D,associate's degree,standard,none,71,71,74
88,female,group A,some college,standard,none,58,70,67
89,female,group D,some high school,standard,none,73,86,82
90,female,group C,bachelor's degree,standard,none,65,72,74
91,male,group C,high school,free/reduced,none,27,34,36
92,male,group C,high school,standard,none,71,79,71
93,male,group C,associate's degree,free/reduced,completed,43,45,50
94,female,group B,some college,standard,none,79,86,92
95,male,group C,associate's degree,free/reduced,completed,78,81,82
96,male,group B,some high school,standard,completed,65,66,62
97,female,group E,some college,standard,completed,63,72,70
98,female,group D,some college,free/reduced,none,58,67,62
99,female,group D,bachelor's degree,standard,none,65,67,62
100,male,group B,some college,standard,none,79,67,67
101,male,group D,bachelor's degree,standard,completed,68,74,74
102,female,group D,associate's degree,standard,none,85,91,89
103,male,group B,high school,standard,completed,60,44,47
104,male,group C,some college,standard,completed,98,86,90
105,female,group C,some college,standard,none,58,67,72
106,female,group D,master's degree,standard,none,87,100,100
107,male,group E,associate's degree,standard,completed,66,63,64
108,female,group B,associate's degree,free/reduced,none,52,76,70
109,female,group B,some high school,standard,none,70,64,72
110,female,group D,associate's degree,free/reduced,completed,77,89,98
111,male,group C,high school,standard,none,62,55,49
112,male,group A,associate's degree,standard,none,54,53,47
113,female,group D,some college,standard,none,51,58,54
114,female,group E,bachelor's degree,standard,completed,99,100,100
115,male,group C,high school,standard,none,84,77,74
116,female,group B,bachelor's degree,free/reduced,none,75,85,82
117,female,group D,bachelor's degree,standard,none,78,82,79
118,female,group D,some high school,standard,none,51,63,61
119,female,group C,some college,standard,none,55,69,65
120,female,group C,bachelor's degree,standard,completed,79,92,89
121,male,group B,associate's degree,standard,completed,91,89,92
122,female,group C,some college,standard,completed,88,93,93
123,male,group D,high school,free/reduced,none,63,57,56
124,male,group E,some college,standard,none,83,80,73
125,female,group B,high school,standard,none,87,95,86
126,male,group B,some high school,standard,none,72,68,67
127,male,group D,some college,standard,completed,65,77,74
128,male,group D,master's degree,standard,none,82,82,74
129,female,group A,bachelor's degree,standard,none,51,49,51
130,male,group D,master's degree,standard,none,89,84,82
131,male,group C,some high school,free/reduced,completed,53,37,40
132,male,group E,some college,free/reduced,completed,87,74,70
133,female,group C,some college,standard,completed,75,81,84
134,male,group D,bachelor's degree,free/reduced,completed,74,79,75
135,male,group C,bachelor's degree,standard,none,58,55,48
136,male,group B,some high school,standard,completed,51,54,41
137,male,group E,high school,standard,none,70,55,56
138,female,group C,associate's degree,standard,none,59,66,67
139,male,group D,some college,standard,completed,71,61,69
140,female,group D,some high school,standard,none,76,72,71
141,female,group C,some college,free/reduced,none,59,62,64
142,female,group E,some college,free/reduced,completed,42,55,54
143,male,group A,high school,standard,none,57,43,47
144,male,group D,some college,standard,none,88,73,78
145,female,group C,some college,free/reduced,none,22,39,33
146,male,group B,some high school,standard,none,88,84,75
147,male,group C,associate's degree,free/reduced,none,73,68,66
148,female,group D,bachelor's degree,standard,completed,68,75,81
149,male,group E,associate's degree,free/reduced,completed,100,100,93
150,male,group A,some high school,standard,completed,62,67,69
151,male,group A,bachelor's degree,standard,none,77,67,68
152,female,group B,associate's degree,standard,completed,59,70,66
153,male,group D,bachelor's degree,standard,none,54,49,47
154,male,group D,some high school,standard,none,62,67,61
155,female,group C,some college,standard,completed,70,89,88
156,female,group E,high school,free/reduced,completed,66,74,78
157,male,group B,some college,free/reduced,none,60,60,60
158,female,group B,associate's degree,standard,completed,61,86,87
159,male,group D,associate's degree,free/reduced,none,66,62,64
160,male,group B,associate's degree,free/reduced,completed,82,78,74
161,female,group E,some college,free/reduced,completed,75,88,85
162,male,group B,master's degree,free/reduced,none,49,53,52
163,male,group C,high school,standard,none,52,53,49
164,female,group E,master's degree,standard,none,81,92,91
165,female,group C,bachelor's degree,standard,completed,96,100,100
166,male,group C,high school,free/reduced,completed,53,51,51
167,female,group B,master's degree,free/reduced,completed,58,76,78
168,female,group B,high school,standard,completed,68,83,78
169,female,group C,some college,free/reduced,completed,67,75,70
170,male,group A,high school,standard,completed,72,73,74
171,male,group E,some high school,standard,none,94,88,78
172,female,group D,some college,standard,none,79,86,81
173,female,group C,associate's degree,standard,none,63,67,70
174,female,group C,bachelor's degree,free/reduced,completed,43,51,54
175,female,group C,master's degree,standard,completed,81,91,87
176,female,group B,high school,free/reduced,completed,46,54,58
177,female,group C,associate's degree,standard,completed,71,77,77
178,female,group B,master's degree,free/reduced,completed,52,70,62
179,female,group D,some high school,standard,completed,97,100,100
180,male,group C,master's degree,free/reduced,completed,62,68,75
181,female,group C,some college,free/reduced,none,46,64,66
182,female,group E,high school,standard,none,50,50,47
183,female,group D,associate's degree,standard,none,65,69,70
184,male,group C,some high school,free/reduced,completed,45,52,49
185,male,group C,associate's degree,free/reduced,completed,65,67,65
186,male,group E,high school,standard,none,80,76,65
187,male,group D,some high school,standard,completed,62,66,68
188,male,group B,some high school,free/reduced,none,48,52,45
189,female,group C,bachelor's degree,standard,none,77,88,87
190,female,group E,associate's degree,standard,none,66,65,69
191,male,group D,some college,standard,completed,76,83,79
192,female,group B,some high school,standard,none,62,64,66
193,male,group D,some college,standard,completed,77,62,62
194,female,group C,master's degree,standard,completed,69,84,85
195,male,group D,associate's degree,standard,none,61,55,52
196,male,group C,some high school,free/reduced,completed,59,69,65
197,male,group E,high school,free/reduced,none,55,56,51
198,female,group B,some college,free/reduced,none,45,53,55
199,female,group B,bachelor's degree,free/reduced,none,78,79,76
200,female,group C,associate's degree,standard,completed,67,84,86
201,female,group D,some college,free/reduced,none,65,81,77
202,male,group C,associate's degree,standard,none,69,77,69
203,female,group B,associate's degree,standard,none,57,69,68
204,male,group C,some college,standard,none,59,41,42
205,male,group D,some high school,standard,completed,74,71,78
206,male,group E,bachelor's degree,standard,none,82,62,62
207,male,group E,high school,standard,completed,81,80,76
208,female,group B,some college,free/reduced,none,74,81,76
209,female,group B,some college,free/reduced,none,58,61,66
210,male,group D,some high school,free/reduced,completed,80,79,79
211,male,group C,some college,free/reduced,none,35,28,27
212,female,group C,high school,free/reduced,none,42,62,60
213,male,group C,associate's degree,free/reduced,completed,60,51,56
214,male,group E,high school,standard,completed,87,91,81
215,male,group B,some high school,standard,completed,84,83,75
216,female,group E,associate's degree,free/reduced,completed,83,86,88
217,female,group C,high school,free/reduced,none,34,42,39
218,male,group B,high school,free/reduced,none,66,77,70
219,male,group B,some high school,standard,completed,61,56,56
220,female,group D,high school,standard,completed,56,68,74
221,male,group B,associate's degree,standard,none,87,85,73
222,female,group C,some high school,free/reduced,none,55,65,62
223,male,group D,some high school,standard,none,86,80,75
224,female,group B,associate's degree,standard,completed,52,66,73
225,female,group E,master's degree,free/reduced,none,45,56,54
226,female,group C,some college,standard,none,72,72,71
227,male,group D,high school,standard,none,57,50,54
228,male,group A,some high school,free/reduced,none,68,72,64
229,female,group C,some college,standard,completed,88,95,94
230,male,group D,some college,standard,none,76,64,66
231,male,group C,associate's degree,standard,none,46,43,42
232,female,group B,bachelor's degree,standard,none,67,86,83
233,male,group E,some high school,standard,none,92,87,78
234,male,group C,bachelor's degree,standard,completed,83,82,84
235,male,group D,associate's degree,standard,none,80,75,77
236,male,group D,bachelor's degree,free/reduced,none,63,66,67
237,female,group D,some high school,standard,completed,64,60,74
238,male,group B,some college,standard,none,54,52,51
239,male,group C,associate's degree,standard,none,84,80,80
240,male,group D,high school,free/reduced,completed,73,68,66
241,female,group E,bachelor's degree,standard,none,80,83,83
242,female,group D,high school,standard,none,56,52,55
243,male,group E,some college,standard,none,59,51,43
244,male,group D,some high school,standard,none,75,74,69
245,male,group C,associate's degree,standard,none,85,76,71
246,male,group E,associate's degree,standard,none,89,76,74
247,female,group B,high school,standard,completed,58,70,68
248,female,group B,high school,standard,none,65,64,62
249,male,group C,high school,standard,none,68,60,53
250,male,group A,some high school,standard,completed,47,49,49
251,female,group D,some college,free/reduced,none,71,83,83
252,female,group B,some high school,standard,completed,60,70,70
253,male,group D,master's degree,standard,none,80,80,72
254,male,group D,high school,standard,none,54,52,52
255,female,group E,some college,standard,none,62,73,70
256,female,group C,associate's degree,free/reduced,none,64,73,68
257,male,group C,associate's degree,standard,completed,78,77,77
258,female,group B,some college,standard,none,70,75,78
259,female,group C,master's degree,free/reduced,completed,65,81,81
260,female,group C,some high school,free/reduced,completed,64,79,77
261,male,group C,some college,standard,completed,79,79,78
262,female,group C,some high school,free/reduced,none,44,50,51
263,female,group E,high school,standard,none,99,93,90
264,male,group D,high school,standard,none,76,73,68
265,male,group D,some high school,free/reduced,none,59,42,41
266,female,group C,bachelor's degree,standard,none,63,75,81
267,female,group D,high school,standard,none,69,72,77
268,female,group D,associate's degree,standard,completed,88,92,95
269,female,group E,some college,free/reduced,none,71,76,70
270,male,group C,bachelor's degree,standard,none,69,63,61
271,male,group C,some college,standard,none,58,49,42
272,female,group D,associate's degree,free/reduced,none,47,53,58
273,female,group D,some college,standard,none,65,70,71
274,male,group B,some college,standard,completed,88,85,76
275,male,group C,bachelor's degree,standard,none,83,78,73
276,female,group C,some high school,standard,completed,85,92,93
277,female,group E,high school,standard,completed,59,63,75
278,female,group C,some high school,free/reduced,none,65,86,80
279,male,group B,bachelor's degree,free/reduced,none,73,56,57
280,male,group D,high school,standard,none,53,52,42
281,male,group D,high school,standard,none,45,48,46
282,female,group D,bachelor's degree,free/reduced,none,73,79,84
283,female,group D,some college,free/reduced,completed,70,78,78
284,female,group B,some high school,standard,none,37,46,46
285,male,group B,associate's degree,standard,completed,81,82,82
286,male,group E,associate's degree,standard,completed,97,82,88
287,female,group B,some high school,standard,none,67,89,82
288,male,group B,bachelor's degree,free/reduced,none,88,75,76
289,male,group E,some high school,standard,completed,77,76,77
290,male,group C,associate's degree,standard,none,76,70,68
291,male,group D,some high school,standard,none,86,73,70
292,male,group C,some high school,standard,completed,63,60,57
293,female,group E,bachelor's degree,standard,none,65,73,75
294,male,group D,high school,free/reduced,completed,78,77,80
295,male,group B,associate's degree,free/reduced,none,67,62,60
296,male,group A,some high school,standard,completed,46,41,43
297,male,group E,associate's degree,standard,completed,71,74,68
298,male,group C,high school,free/reduced,completed,40,46,50
299,male,group D,associate's degree,free/reduced,none,90,87,75
300,male,group A,some college,free/reduced,completed,81,78,81
301,male,group D,some high school,free/reduced,none,56,54,52
302,female,group C,associate's degree,standard,completed,67,84,81
303,male,group B,associate's degree,standard,none,80,76,64
304,female,group C,associate's degree,standard,completed,74,75,83
305,male,group A,some college,standard,none,69,67,69
306,male,group E,some college,standard,completed,99,87,81
307,male,group C,some high school,standard,none,51,52,44
308,female,group B,associate's degree,free/reduced,none,53,71,67
309,female,group D,high school,free/reduced,none,49,57,52
310,female,group B,associate's degree,standard,none,73,76,80
311,male,group B,bachelor's degree,standard,none,66,60,57
312,male,group D,bachelor's degree,standard,completed,67,61,68
313,female,group C,associate's degree,free/reduced,completed,68,67,69
314,female,group C,bachelor's degree,standard,completed,59,64,75
315,male,group C,high school,standard,none,71,66,65
316,female,group D,master's degree,standard,completed,77,82,91
317,male,group C,associate's degree,standard,none,83,72,78
318,male,group B,bachelor's degree,standard,none,63,71,69
319,female,group D,associate's degree,free/reduced,none,56,65,63
320,female,group C,high school,free/reduced,completed,67,79,84
321,female,group E,high school,standard,none,75,86,79
322,female,group C,some college,standard,none,71,81,80
323,female,group C,some high school,free/reduced,none,43,53,53
324,female,group C,high school,free/reduced,none,41,46,43
325,female,group C,some college,standard,none,82,90,94
326,male,group C,some college,standard,none,61,61,62
327,male,group A,some college,free/reduced,none,28,23,19
328,male,group C,associate's degree,standard,completed,82,75,77
329,female,group B,some high school,standard,none,41,55,51
330,male,group C,high school,standard,none,71,60,61
331,male,group C,associate's degree,standard,none,47,37,35
332,male,group E,associate's degree,standard,completed,62,56,53

# Selecting one column

## Syntax 1

In [35]:
# select a column with []
df_exams['gender']

0      female
1      female
2      female
3        male
4        male
5      female
6      female
7        male
8        male
9      female
10       male
11       male
12     female
13       male
14     female
15     female
16       male
17     female
18       male
19     female
20       male
21     female
22       male
23     female
24       male
25       male
26       male
27     female
28       male
29     female
30     female
31     female
32     female
33       male
34       male
35       male
36     female
37     female
38     female
39       male
40       male
41     female
42     female
43       male
44     female
45       male
46     female
47     female
48     female
49       male
50       male
51       male
52       male
53       male
54     female
55     female
56     female
57       male
58       male
59     female
60       male
61       male
62       male
63     female
64     female
65       male
66       male
67     female
68       male
69     female
70     female
71       male
72     female
73       male
74       male
75       male
76       male
77       male
78     female
79     female
80     female
81       male
82       male
83       male
84       male
85     female
86     female
87     female
88     female
89     female
90     female
91       male
92       male
93       male
94     female
95       male
96       male
97     female
98     female
99     female
100      male
101      male
102    female
103      male
104      male
105    female
106    female
107      male
108    female
109    female
110    female
111      male
112      male
113    female
114    female
115      male
116    female
117    female
118    female
119    female
120    female
121      male
122    female
123      male
124      male
125    female
126      male
127      male
128      male
129    female
130      male
131      male
132      male
133    female
134      male
135      male
136      male
137      male
138    female
139      male
140    female
141    female
142    female
143      male
144      male
145    female
146      male
147      male
148    female
149      male
150      male
151      male
152    female
153      male
154      male
155    female
156    female
157      male
158    female
159      male
160      male
161    female
162      male
163      male
164    female
165    female
166      male
167    female
168    female
169    female
170      male
171      male
172    female
173    female
174    female
175    female
176    female
177    female
178    female
179    female
180      male
181    female
182    female
183    female
184      male
185      male
186      male
187      male
188      male
189    female
190    female
191      male
192    female
193      male
194    female
195      male
196      male
197      male
198    female
199    female
200    female
201    female
202      male
203    female
204      male
205      male
206      male
207      male
208    female
209    female
210      male
211      male
212    female
213      male
214      male
215      male
216    female
217    female
218      male
219      male
220    female
221      male
222    female
223      male
224    female
225    female
226    female
227      male
228      male
229    female
230      male
231      male
232    female
233      male
234      male
235      male
236      male
237    female
238      male
239      male
240      male
241    female
242    female
243      male
244      male
245      male
246      male
247    female
248    female
249      male
250      male
251    female
252    female
253      male
254      male
255    female
256    female
257      male
258    female
259    female
260    female
261      male
262    female
263    female
264      male
265      male
266    female
267    female
268    female
269    female
270      male
271      male
272    female
273    female
274      male
275      male
276    female
277    female
278    female
279      male
280      male
281      male
282    female
283    female
284    female
285      male
286      male
287    female
288      male
289      male
290      male
291      male
292      male
293    female
294      male
295      male
296      male
297      male
298      male
299      male
300      male
301      male
302    female
303      male
304    female
305      male
306      male
307      male
308    female
309    female
310    female
311      male
312      male
313    female
314    female
315      male
316    female
317      male
318      male
319    female
320    female
321    female
322    female
323    female
324    female
325    female
326      male
327      male
328      male
329    female
330      male
331      male
332      male
333      male
334    female
335    female
336      male
337      male
338    female
339    female
340      male
341    female
342    female
343      male
344      male
345    female
346      male
347    female
348      male
349      male
350    female
351      male
352    female
353    female
354    female
355    female
356      male
357    female
358      male
359    female
360    female
361      male
362    female
363    female
364      male
365      male
366      male
367      male
368    female
369    female
370      male
371    female
372      male
373    female
374    female
375      male
376    female
377    female
378    female
379      male
380    female
381      male
382      male
383    female
384    female
385    female
386    female
387    female
388    female
389      male
390      male
391    female
392      male
393      male
394    female
395      male
396    female
397    female
398      male
399      male
400    female
401      male
402    female
403    female
404    female
405    female
406      male
407    female
408    female
409      male
410    female
411      male
412      male
413      male
414    female
415      male
416      male
417      male
418      male
419      male
420    female
421    female
422    female
423    female
424      male
425    female
426      male
427      male
428      male
429      male
430      male
431    female
432      male
433    female
434      male
435      male
436      male
437      male
438      male
439      male
440    female
441    female
442    female
443    female
444      male
445    female
446      male
447      male
448      male
449      male
450    female
451    female
452    female
453      male
454    female
455      male
456    female
457      male
458    female
459      male
460      male
461      male
462    female
463    female
464      male
465    female
466    female
467      male
468    female
469      male
470    female
471    female
472    female
473    female
474    female
475    female
476      male
477      male
478    female
479      male
480      male
481    female
482      male
483      male
484    female
485      male
486      male
487    female
488      male
489      male
490    female
491    female
492    female
493    female
494    female
495      male
496    female
497    female
498    female
499      male
500    female
501    female
502      male
503    female
504    female
505    female
506      male
507      male
508      male
509    female
510      male
511      male
512      male
513    female
514    female
515    female
516    female
517    female
518    female
519    female
520      male
521    female
522      male
523      male
524      male
525      male
526      male
527    female
528    female
529    female
530    female
531    female
532      male
533    female
534      male
535    female
536      male
537    female
538      male
539      male
540      male
541      male
542    female
543    female
544    female
545      male
546    female
547      male
548    female
549      male
550      male
551      male
552    female
553      male
554      male
555    female
556    female
557      male
558    female
559      male
560    female
561    female
562      male
563    female
564      male
565      male
566    female
567    female
568      male
569      male
570      male
571      male
572    female
573    female
574    female
575      male
576      male
577    female
578    female
579    female
580    female
581    female
582    female
583    female
584    female
585    female
586    female
587    female
588    female
589    female
590      male
591      male
592      male
593    female
594    female
595    female
596      male
597      male
598    female
599    female
600    female
601    female
602    female
603      male
604      male
605      male
606    female
607    female
608    female
609    female
610      male
611    female
612      male
613    female
614    female
615    female
616    female
617      male
618      male
619      male
620    female
621      male
622      male
623      male
624    female
625      male
626      male
627      male
628      male
629    female
630      male
631      male
632    female
633    female
634      male
635      male
636    female
637    female
638      male
639    female
640      male
641    female
642    female
643    female
644      male
645    female
646    female
647    female
648    female
649    female
650      male
651    female
652    female
653    female
654    female
655    female
656      male
657      male
658    female
659      male
660      male
661      male
662    female
663    female
664      male
665    female
666    female
667    female
668      male
669      male
670    female
671      male
672    female
673    female
674    female
675    female
676    female
677    female
678      male
679      male
680    female
681      male
682      male
683    female
684      male
685    female
686      male
687      male
688      male
689      male
690    female
691    female
692    female
693    female
694    female
695    female
696    female
697    female
698    female
699      male
700    female
701    female
702      male
703    female
704    female
705      male
706      male
707      male
708      male
709    female
710      male
711    female
712    female
713      male
714    female
715    female
716      male
717    female
718    female
719      male
720    female
721      male
722    female
723      male
724      male
725      male
726    female
727      male
728    female
729      male
730    female
731      male
732    female
733      male
734    female
735      male
736      male
737    female
738      male
739      male
740      male
741    female
742    female
743    female
744      male
745      male
746      male
747      male
748    female
749      male
750      male
751      male
752      male
753    female
754      male
755    female
756      male
757      male
758    female
759      male
760    female
761    female
762      male
763    female
764      male
765    female
766    female
767      male
768    female
769      male
770      male
771      male
772    female
773    female
774      male
775    female
776    female
777    female
778    female
779      male
780    female
781    female
782    female
783    female
784      male
785    female
786    female
787    female
788      male
789    female
790    female
791    female
792      male
793      male
794    female
795    female
796      male
797    female
798      male
799    female
800      male
801      male
802    female
803    female
804    female
805      male
806    female
807    female
808      male
809      male
810      male
811      male
812    female
813      male
814    female
815      male
816    female
817      male
818    female
819    female
820    female
821    female
822      male
823    female
824    female
825      male
826    female
827    female
828    female
829      male
830    female
831    female
832      male
833    female
834      male
835    female
836      male
837    female
838      male
839    female
840    female
841      male
842    female
843      male
844    female
845      male
846      male
847      male
848    female
849      male
850      male
851    female
852    female
853      male
854      male
855    female
856      male
857    female
858      male
859      male
860    female
861    female
862      male
863    female
864      male
865      male
866      male
867      male
868      male
869      male
870      male
871    female
872      male
873      male
874    female
875      male
876      male
877      male
878    female
879    female
880      male
881    female
882    female
883      male
884    female
885    female
886    female
887      male
888    female
889      male
890    female
891    female
892    female
893      male
894    female
895    female
896      male
897    female
898      male
899    female
900      male
901    female
902    female
903    female
904    female
905      male
906      male
907    female
908    female
909      male
910      male
911    female
912    female
913    female
914    female
915    female
916      male
917    female
918    female
919      male
920      male
921    female
922      male
923    female
924      male
925      male
926      male
927    female
928      male
929    female
930      male
931      male
932      male
933      male
934      male
935      male
936      male
937    female
938      male
939      male
940      male
941    female
942      male
943      male
944    female
945    female
946      male
947    female
948      male
949    female
950      male
951    female
952    female
953      male
954    female
955      male
956      male
957    female
958    female
959      male
960    female
961    female
962    female
963    female
964      male
965    female
966      male
967      male
968    female
969    female
970    female
971      male
972    female
973    female
974    female
975    female
976      male
977      male
978      male
979    female
980    female
981      male
982      male
983    female
984    female
985      male
986    female
987      male
988    female
989    female
990      male
991    female
992    female
993    female
994      male
995    female
996      male
997    female
998    female
999    female
Name: gender, dtype: object

In [36]:
# type of series
type(df_exams['gender'])

pandas.core.series.Series

In [37]:
# series attributes and methods
df_exams['gender'].describe()

count       1000
unique         2
top       female
freq         518
Name: gender, dtype: object

In [38]:
df_exams['gender'].index

RangeIndex(start=0, stop=1000, step=1)

In [39]:
df_exams['gender'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 1000 entries, 0 to 999
Series name: gender
Non-Null Count  Dtype
--------------  -----
1000 non-null   object
dtypes: object(1)
memory usage: 7.9+ KB

## Syntax 2

In [40]:
# select a column with .
df_exams.gender

0      female
1      female
2      female
3        male
4        male
5      female
6      female
7        male
8        male
9      female
10       male
11       male
12     female
13       male
14     female
15     female
16       male
17     female
18       male
19     female
20       male
21     female
22       male
23     female
24       male
25       male
26       male
27     female
28       male
29     female
30     female
31     female
32     female
33       male
34       male
35       male
36     female
37     female
38     female
39       male
40       male
41     female
42     female
43       male
44     female
45       male
46     female
47     female
48     female
49       male
50       male
51       male
52       male
53       male
54     female
55     female
56     female
57       male
58       male
59     female
60       male
61       male
62       male
63     female
64     female
65       male
66       male
67     female
68       male
69     female
70     female
71       male
72     female
73       male
74       male
75       male
76       male
77       male
78     female
79     female
80     female
81       male
82       male
83       male
84       male
85     female
86     female
87     female
88     female
89     female
90     female
91       male
92       male
93       male
94     female
95       male
96       male
97     female
98     female
99     female
100      male
101      male
102    female
103      male
104      male
105    female
106    female
107      male
108    female
109    female
110    female
111      male
112      male
113    female
114    female
115      male
116    female
117    female
118    female
119    female
120    female
121      male
122    female
123      male
124      male
125    female
126      male
127      male
128      male
129    female
130      male
131      male
132      male
133    female
134      male
135      male
136      male
137      male
138    female
139      male
140    female
141    female
142    female
143      male
144      male
145    female
146      male
147      male
148    female
149      male
150      male
151      male
152    female
153      male
154      male
155    female
156    female
157      male
158    female
159      male
160      male
161    female
162      male
163      male
164    female
165    female
166      male
167    female
168    female
169    female
170      male
171      male
172    female
173    female
174    female
175    female
176    female
177    female
178    female
179    female
180      male
181    female
182    female
183    female
184      male
185      male
186      male
187      male
188      male
189    female
190    female
191      male
192    female
193      male
194    female
195      male
196      male
197      male
198    female
199    female
200    female
201    female
202      male
203    female
204      male
205      male
206      male
207      male
208    female
209    female
210      male
211      male
212    female
213      male
214      male
215      male
216    female
217    female
218      male
219      male
220    female
221      male
222    female
223      male
224    female
225    female
226    female
227      male
228      male
229    female
230      male
231      male
232    female
233      male
234      male
235      male
236      male
237    female
238      male
239      male
240      male
241    female
242    female
243      male
244      male
245      male
246      male
247    female
248    female
249      male
250      male
251    female
252    female
253      male
254      male
255    female
256    female
257      male
258    female
259    female
260    female
261      male
262    female
263    female
264      male
265      male
266    female
267    female
268    female
269    female
270      male
271      male
272    female
273    female
274      male
275      male
276    female
277    female
278    female
279      male
280      male
281      male
282    female
283    female
284    female
285      male
286      male
287    female
288      male
289      male
290      male
291      male
292      male
293    female
294      male
295      male
296      male
297      male
298      male
299      male
300      male
301      male
302    female
303      male
304    female
305      male
306      male
307      male
308    female
309    female
310    female
311      male
312      male
313    female
314    female
315      male
316    female
317      male
318      male
319    female
320    female
321    female
322    female
323    female
324    female
325    female
326      male
327      male
328      male
329    female
330      male
331      male
332      male
333      male
334    female
335    female
336      male
337      male
338    female
339    female
340      male
341    female
342    female
343      male
344      male
345    female
346      male
347    female
348      male
349      male
350    female
351      male
352    female
353    female
354    female
355    female
356      male
357    female
358      male
359    female
360    female
361      male
362    female
363    female
364      male
365      male
366      male
367      male
368    female
369    female
370      male
371    female
372      male
373    female
374    female
375      male
376    female
377    female
378    female
379      male
380    female
381      male
382      male
383    female
384    female
385    female
386    female
387    female
388    female
389      male
390      male
391    female
392      male
393      male
394    female
395      male
396    female
397    female
398      male
399      male
400    female
401      male
402    female
403    female
404    female
405    female
406      male
407    female
408    female
409      male
410    female
411      male
412      male
413      male
414    female
415      male
416      male
417      male
418      male
419      male
420    female
421    female
422    female
423    female
424      male
425    female
426      male
427      male
428      male
429      male
430      male
431    female
432      male
433    female
434      male
435      male
436      male
437      male
438      male
439      male
440    female
441    female
442    female
443    female
444      male
445    female
446      male
447      male
448      male
449      male
450    female
451    female
452    female
453      male
454    female
455      male
456    female
457      male
458    female
459      male
460      male
461      male
462    female
463    female
464      male
465    female
466    female
467      male
468    female
469      male
470    female
471    female
472    female
473    female
474    female
475    female
476      male
477      male
478    female
479      male
480      male
481    female
482      male
483      male
484    female
485      male
486      male
487    female
488      male
489      male
490    female
491    female
492    female
493    female
494    female
495      male
496    female
497    female
498    female
499      male
500    female
501    female
502      male
503    female
504    female
505    female
506      male
507      male
508      male
509    female
510      male
511      male
512      male
513    female
514    female
515    female
516    female
517    female
518    female
519    female
520      male
521    female
522      male
523      male
524      male
525      male
526      male
527    female
528    female
529    female
530    female
531    female
532      male
533    female
534      male
535    female
536      male
537    female
538      male
539      male
540      male
541      male
542    female
543    female
544    female
545      male
546    female
547      male
548    female
549      male
550      male
551      male
552    female
553      male
554      male
555    female
556    female
557      male
558    female
559      male
560    female
561    female
562      male
563    female
564      male
565      male
566    female
567    female
568      male
569      male
570      male
571      male
572    female
573    female
574    female
575      male
576      male
577    female
578    female
579    female
580    female
581    female
582    female
583    female
584    female
585    female
586    female
587    female
588    female
589    female
590      male
591      male
592      male
593    female
594    female
595    female
596      male
597      male
598    female
599    female
600    female
601    female
602    female
603      male
604      male
605      male
606    female
607    female
608    female
609    female
610      male
611    female
612      male
613    female
614    female
615    female
616    female
617      male
618      male
619      male
620    female
621      male
622      male
623      male
624    female
625      male
626      male
627      male
628      male
629    female
630      male
631      male
632    female
633    female
634      male
635      male
636    female
637    female
638      male
639    female
640      male
641    female
642    female
643    female
644      male
645    female
646    female
647    female
648    female
649    female
650      male
651    female
652    female
653    female
654    female
655    female
656      male
657      male
658    female
659      male
660      male
661      male
662    female
663    female
664      male
665    female
666    female
667    female
668      male
669      male
670    female
671      male
672    female
673    female
674    female
675    female
676    female
677    female
678      male
679      male
680    female
681      male
682      male
683    female
684      male
685    female
686      male
687      male
688      male
689      male
690    female
691    female
692    female
693    female
694    female
695    female
696    female
697    female
698    female
699      male
700    female
701    female
702      male
703    female
704    female
705      male
706      male
707      male
708      male
709    female
710      male
711    female
712    female
713      male
714    female
715    female
716      male
717    female
718    female
719      male
720    female
721      male
722    female
723      male
724      male
725      male
726    female
727      male
728    female
729      male
730    female
731      male
732    female
733      male
734    female
735      male
736      male
737    female
738      male
739      male
740      male
741    female
742    female
743    female
744      male
745      male
746      male
747      male
748    female
749      male
750      male
751      male
752      male
753    female
754      male
755    female
756      male
757      male
758    female
759      male
760    female
761    female
762      male
763    female
764      male
765    female
766    female
767      male
768    female
769      male
770      male
771      male
772    female
773    female
774      male
775    female
776    female
777    female
778    female
779      male
780    female
781    female
782    female
783    female
784      male
785    female
786    female
787    female
788      male
789    female
790    female
791    female
792      male
793      male
794    female
795    female
796      male
797    female
798      male
799    female
800      male
801      male
802    female
803    female
804    female
805      male
806    female
807    female
808      male
809      male
810      male
811      male
812    female
813      male
814    female
815      male
816    female
817      male
818    female
819    female
820    female
821    female
822      male
823    female
824    female
825      male
826    female
827    female
828    female
829      male
830    female
831    female
832      male
833    female
834      male
835    female
836      male
837    female
838      male
839    female
840    female
841      male
842    female
843      male
844    female
845      male
846      male
847      male
848    female
849      male
850      male
851    female
852    female
853      male
854      male
855    female
856      male
857    female
858      male
859      male
860    female
861    female
862      male
863    female
864      male
865      male
866      male
867      male
868      male
869      male
870      male
871    female
872      male
873      male
874    female
875      male
876      male
877      male
878    female
879    female
880      male
881    female
882    female
883      male
884    female
885    female
886    female
887      male
888    female
889      male
890    female
891    female
892    female
893      male
894    female
895    female
896      male
897    female
898      male
899    female
900      male
901    female
902    female
903    female
904    female
905      male
906      male
907    female
908    female
909      male
910      male
911    female
912    female
913    female
914    female
915    female
916      male
917    female
918    female
919      male
920      male
921    female
922      male
923    female
924      male
925      male
926      male
927    female
928      male
929    female
930      male
931      male
932      male
933      male
934      male
935      male
936      male
937    female
938      male
939      male
940      male
941    female
942      male
943      male
944    female
945    female
946      male
947    female
948      male
949    female
950      male
951    female
952    female
953      male
954    female
955      male
956      male
957    female
958    female
959      male
960    female
961    female
962    female
963    female
964      male
965    female
966      male
967      male
968    female
969    female
970    female
971      male
972    female
973    female
974    female
975    female
976      male
977      male
978      male
979    female
980    female
981      male
982      male
983    female
984    female
985      male
986    female
987      male
988    female
989    female
990      male
991    female
992    female
993    female
994      male
995    female
996      male
997    female
998    female
999    female
Name: gender, dtype: object

In [41]:
df_exams['math score'].mean()

np.float64(66.089)

# Selecting two or more columns

In [42]:
# select two columns
df_exams[['gender', 'math score', 'reading score']]

     gender  math score  reading score
0    female          72             72
1    female          69             90
2    female          90             95
3      male          47             57
4      male          76             78
5    female          71             83
6    female          88             95
7      male          40             43
8      male          64             64
9    female          38             60
10     male          58             54
11     male          40             52
12   female          65             81
13     male          78             72
14   female          50             53
15   female          69             75
16     male          88             89
17   female          18             32
18     male          46             42
19   female          54             58
20     male          66             69
21   female          65             75
22     male          44             54
23   female          69             73
24     male          74             71
25     male          73             74
26     male          69             54
27   female          67             69
28     male          70             70
29   female          62             70
30   female          69             74
31   female          63             65
32   female          56             72
33     male          40             42
34     male          97             87
35     male          81             81
36   female          74             81
37   female          50             64
38   female          75             90
39     male          57             56
40     male          55             61
41   female          58             73
42   female          53             58
43     male          59             65
44   female          50             56
45     male          65             54
46   female          55             65
47   female          66             71
48   female          57             74
49     male          82             84
50     male          53             55
51     male          77             69
52     male          53             44
53     male          88             78
54   female          71             84
55   female          33             41
56   female          82             85
57     male          52             55
58     male          58             59
59   female           0             17
60     male          79             74
61     male          39             39
62     male          62             61
63   female          69             80
64   female          59             58
65     male          67             64
66     male          45             37
67   female          60             72
68     male          61             58
69   female          39             64
70   female          58             63
71     male          63             55
72   female          41             51
73     male          61             57
74     male          49             49
75     male          44             41
76     male          30             26
77     male          80             78
78   female          61             74
79   female          62             68
80   female          47             49
81     male          49             45
82     male          50             47
83     male          72             64
84     male          42             39
85   female          73             80
86   female          76             83
87   female          71             71
88   female          58             70
89   female          73             86
90   female          65             72
91     male          27             34
92     male          71             79
93     male          43             45
94   female          79             86
95     male          78             81
96     male          65             66
97   female          63             72
98   female          58             67
99   female          65             67
100    male          79             67
101    male          68             74
102  female          85             91
103    male          60             44
104    male          98             86
105  female          58             67
106  female          87            100
107    male          66             63
108  female          52             76
109  female          70             64
110  female          77             89
111    male          62             55
112    male          54             53
113  female          51             58
114  female          99            100
115    male          84             77
116  female          75             85
117  female          78             82
118  female          51             63
119  female          55             69
120  female          79             92
121    male          91             89
122  female          88             93
123    male          63             57
124    male          83             80
125  female          87             95
126    male          72             68
127    male          65             77
128    male          82             82
129  female          51             49
130    male          89             84
131    male          53             37
132    male          87             74
133  female          75             81
134    male          74             79
135    male          58             55
136    male          51             54
137    male          70             55
138  female          59             66
139    male          71             61
140  female          76             72
141  female          59             62
142  female          42             55
143    male          57             43
144    male          88             73
145  female          22             39
146    male          88             84
147    male          73             68
148  female          68             75
149    male         100            100
150    male          62             67
151    male          77             67
152  female          59             70
153    male          54             49
154    male          62             67
155  female          70             89
156  female          66             74
157    male          60             60
158  female          61             86
159    male          66             62
160    male          82             78
161  female          75             88
162    male          49             53
163    male          52             53
164  female          81             92
165  female          96            100
166    male          53             51
167  female          58             76
168  female          68             83
169  female          67             75
170    male          72             73
171    male          94             88
172  female          79             86
173  female          63             67
174  female          43             51
175  female          81             91
176  female          46             54
177  female          71             77
178  female          52             70
179  female          97            100
180    male          62             68
181  female          46             64
182  female          50             50
183  female          65             69
184    male          45             52
185    male          65             67
186    male          80             76
187    male          62             66
188    male          48             52
189  female          77             88
190  female          66             65
191    male          76             83
192  female          62             64
193    male          77             62
194  female          69             84
195    male          61             55
196    male          59             69
197    male          55             56
198  female          45             53
199  female          78             79
200  female          67             84
201  female          65             81
202    male          69             77
203  female          57             69
204    male          59             41
205    male          74             71
206    male          82             62
207    male          81             80
208  female          74             81
209  female          58             61
210    male          80             79
211    male          35             28
212  female          42             62
213    male          60             51
214    male          87             91
215    male          84             83
216  female          83             86
217  female          34             42
218    male          66             77
219    male          61             56
220  female          56             68
221    male          87             85
222  female          55             65
223    male          86             80
224  female          52             66
225  female          45             56
226  female          72             72
227    male          57             50
228    male          68             72
229  female          88             95
230    male          76             64
231    male          46             43
232  female          67             86
233    male          92             87
234    male          83             82
235    male          80             75
236    male          63             66
237  female          64             60
238    male          54             52
239    male          84             80
240    male          73             68
241  female          80             83
242  female          56             52
243    male          59             51
244    male          75             74
245    male          85             76
246    male          89             76
247  female          58             70
248  female          65             64
249    male          68             60
250    male          47             49
251  female          71             83
252  female          60             70
253    male          80             80
254    male          54             52
255  female          62             73
256  female          64             73
257    male          78             77
258  female          70             75
259  female          65             81
260  female          64             79
261    male          79             79
262  female          44             50
263  female          99             93
264    male          76             73
265    male          59             42
266  female          63             75
267  female          69             72
268  female          88             92
269  female          71             76
270    male          69             63
271    male          58             49
272  female          47             53
273  female          65             70
274    male          88             85
275    male          83             78
276  female          85             92
277  female          59             63
278  female          65             86
279    male          73             56
280    male          53             52
281    male          45             48
282  female          73             79
283  female          70             78
284  female          37             46
285    male          81             82
286    male          97             82
287  female          67             89
288    male          88             75
289    male          77             76
290    male          76             70
291    male          86             73
292    male          63             60
293  female          65             73
294    male          78             77
295    male          67             62
296    male          46             41
297    male          71             74
298    male          40             46
299    male          90             87
300    male          81             78
301    male          56             54
302  female          67             84
303    male          80             76
304  female          74             75
305    male          69             67
306    male          99             87
307    male          51             52
308  female          53             71
309  female          49             57
310  female          73             76
311    male          66             60
312    male          67             61
313  female          68             67
314  female          59             64
315    male          71             66
316  female          77             82
317    male          83             72
318    male          63             71
319  female          56             65
320  female          67             79
321  female          75             86
322  female          71             81
323  female          43             53
324  female          41             46
325  female          82             90
326    male          61             61
327    male          28             23
328    male          82             75
329  female          41             55
330    male          71             60
331    male          47             37
332    male          62             56
333    male          90             78
334  female          83             93
335  female          61             68
336    male          76             70
337    male          49             51
338  female          24             38
339  female          35             55
340    male          58             61
341  female          61             73
342  female          69             76
343    male          67             72
344    male          79             73
345  female          72             80
346    male          62             61
347  female          77             94
348    male          75             74
349    male          87             74
350  female          52             65
351    male          66             57
352  female          63             78
353  female          46             58
354  female          59             71
355  female          61             72
356    male          63             61
357  female          42             66
358    male          59             62
359  female          80             90
360  female          58             62
361    male          85             84
362  female          52             58
363  female          27             34
364    male          59             60
365    male          49             58
366    male          69             58
367    male          61             66
368  female          44             64
369  female          73             84
370    male          84             77
371  female          45             73
372    male          74             74
373  female          82             97
374  female          59             70
375    male          46             43
376  female          80             90
377  female          85             95
378  female          71             83
379    male          66             64
380  female          80             86
381    male          87            100
382    male          79             81
383  female          38             49
384  female          38             43
385  female          67             76
386  female          64             73
387  female          57             78
388  female          62             64
389    male          73             70
390    male          73             67
391  female          77             68
392    male          76             67
393    male          57             54
394  female          65             74
395    male          48             45
396  female          50             67
397  female          85             89
398    male          74             63
399    male          60             59
400  female          59             54
401    male          53             43
402  female          49             65
403  female          88             99
404  female          54             59
405  female          63             73
406    male          65             65
407  female          82             80
408  female          52             57
409    male          87             84
410  female          70             71
411    male          84             83
412    male          71             66
413    male          63             67
414  female          51             72
415    male          84             73
416    male          71             74
417    male          74             73
418    male          68             59
419    male          57             56
420  female          82             93
421  female          57             58
422  female          47             58
423  female          59             85
424    male          41             39
425  female          62             67
426    male          86             83
427    male          69             71
428    male          65             59
429    male          68             63
430    male          64             66
431  female          61             72
432    male          61             56
433  female          47             59
434    male          73             66
435    male          50             48
436    male          75             68
437    male          75             66
438    male          70             56
439    male          89             88
440  female          67             81
441  female          78             81
442  female          59             73
443  female          73             83
444    male          79             82
445  female          67             74
446    male          69             66
447    male          86             81
448    male          47             46
449    male          81             73
450  female          64             85
451  female         100             92
452  female          65             77
453    male          65             58
454  female          53             61
455    male          37             56
456  female          79             89
457    male          53             54
458  female         100            100
459    male          72             65
460    male          53             58
461    male          54             54
462  female          71             70
463  female          77             90
464    male          75             58
465  female          84             87
466  female          26             31
467    male          72             67
468  female          77             88
469    male          91             74
470  female          83             85
471  female          63             69
472  female          68             86
473  female          59             67
474  female          90             90
475  female          71             76
476    male          76             62
477    male          80             68
478  female          55             64
479    male          76             71
480    male          73             71
481  female          52             59
482    male          68             68
483    male          59             52
484  female          49             52
485    male          70             74
486    male          61             47
487  female          60             75
488    male          64             53
489    male          79             82
490  female          65             85
491  female          64             64
492  female          83             83
493  female          81             88
494  female          54             64
495    male          68             64
496  female          54             48
497  female          59             78
498  female          66             69
499    male          76             71
500  female          74             79
501  female          94             87
502    male          63             61
503  female          95             89
504  female          40             59
505  female          82             82
506    male          68             70
507    male          55             59
508    male          79             78
509  female          86             92
510    male          76             71

In [43]:
# check datatype
type(df_exams[['gender', 'math score']])

pandas.core.frame.DataFrame

In [44]:
# select more than 2 columns
df_exams[[ 'math score', 'reading score', 'writing score']]

     math score  reading score  writing score
0            72             72             74
1            69             90             88
2            90             95             93
3            47             57             44
4            76             78             75
5            71             83             78
6            88             95             92
7            40             43             39
8            64             64             67
9            38             60             50
10           58             54             52
11           40             52             43
12           65             81             73
13           78             72             70
14           50             53             58
15           69             75             78
16           88             89             86
17           18             32             28
18           46             42             46
19           54             58             61
20           66             69             63
21           65             75             70
22           44             54             53
23           69             73             73
24           74             71             80
25           73             74             72
26           69             54             55
27           67             69             75
28           70             70             65
29           62             70             75
30           69             74             74
31           63             65             61
32           56             72             65
33           40             42             38
34           97             87             82
35           81             81             79
36           74             81             83
37           50             64             59
38           75             90             88
39           57             56             57
40           55             61             54
41           58             73             68
42           53             58             65
43           59             65             66
44           50             56             54
45           65             54             57
46           55             65             62
47           66             71             76
48           57             74             76
49           82             84             82
50           53             55             48
51           77             69             68
52           53             44             42
53           88             78             75
54           71             84             87
55           33             41             43
56           82             85             86
57           52             55             49
58           58             59             58
59            0             17             10
60           79             74             72
61           39             39             34
62           62             61             55
63           69             80             71
64           59             58             59
65           67             64             61
66           45             37             37
67           60             72             74
68           61             58             56
69           39             64             57
70           58             63             73
71           63             55             63
72           41             51             48
73           61             57             56
74           49             49             41
75           44             41             38
76           30             26             22
77           80             78             81
78           61             74             72
79           62             68             68
80           47             49             50
81           49             45             45
82           50             47             54
83           72             64             63
84           42             39             34
85           73             80             82
86           76             83             88
87           71             71             74
88           58             70             67
89           73             86             82
90           65             72             74
91           27             34             36
92           71             79             71
93           43             45             50
94           79             86             92
95           78             81             82
96           65             66             62
97           63             72             70
98           58             67             62
99           65             67             62
100          79             67             67
101          68             74             74
102          85             91             89
103          60             44             47
104          98             86             90
105          58             67             72
106          87            100            100
107          66             63             64
108          52             76             70
109          70             64             72
110          77             89             98
111          62             55             49
112          54             53             47
113          51             58             54
114          99            100            100
115          84             77             74
116          75             85             82
117          78             82             79
118          51             63             61
119          55             69             65
120          79             92             89
121          91             89             92
122          88             93             93
123          63             57             56
124          83             80             73
125          87             95             86
126          72             68             67
127          65             77             74
128          82             82             74
129          51             49             51
130          89             84             82
131          53             37             40
132          87             74             70
133          75             81             84
134          74             79             75
135          58             55             48
136          51             54             41
137          70             55             56
138          59             66             67
139          71             61             69
140          76             72             71
141          59             62             64
142          42             55             54
143          57             43             47
144          88             73             78
145          22             39             33
146          88             84             75
147          73             68             66
148          68             75             81
149         100            100             93
150          62             67             69
151          77             67             68
152          59             70             66
153          54             49             47
154          62             67             61
155          70             89             88
156          66             74             78
157          60             60             60
158          61             86             87
159          66             62             64
160          82             78             74
161          75             88             85
162          49             53             52
163          52             53             49
164          81             92             91
165          96            100            100
166          53             51             51
167          58             76             78
168          68             83             78
169          67             75             70
170          72             73             74
171          94             88             78
172          79             86             81
173          63             67             70
174          43             51             54
175          81             91             87
176          46             54             58
177          71             77             77
178          52             70             62
179          97            100            100
180          62             68             75
181          46             64             66
182          50             50             47
183          65             69             70
184          45             52             49
185          65             67             65
186          80             76             65
187          62             66             68
188          48             52             45
189          77             88             87
190          66             65             69
191          76             83             79
192          62             64             66
193          77             62             62
194          69             84             85
195          61             55             52
196          59             69             65
197          55             56             51
198          45             53             55
199          78             79             76
200          67             84             86
201          65             81             77
202          69             77             69
203          57             69             68
204          59             41             42
205          74             71             78
206          82             62             62
207          81             80             76
208          74             81             76
209          58             61             66
210          80             79             79
211          35             28             27
212          42             62             60
213          60             51             56
214          87             91             81
215          84             83             75
216          83             86             88
217          34             42             39
218          66             77             70
219          61             56             56
220          56             68             74
221          87             85             73
222          55             65             62
223          86             80             75
224          52             66             73
225          45             56             54
226          72             72             71
227          57             50             54
228          68             72             64
229          88             95             94
230          76             64             66
231          46             43             42
232          67             86             83
233          92             87             78
234          83             82             84
235          80             75             77
236          63             66             67
237          64             60             74
238          54             52             51
239          84             80             80
240          73             68             66
241          80             83             83
242          56             52             55
243          59             51             43
244          75             74             69
245          85             76             71
246          89             76             74
247          58             70             68
248          65             64             62
249          68             60             53
250          47             49             49
251          71             83             83
252          60             70             70
253          80             80             72
254          54             52             52
255          62             73             70
256          64             73             68
257          78             77             77
258          70             75             78
259          65             81             81
260          64             79             77
261          79             79             78
262          44             50             51
263          99             93             90
264          76             73             68
265          59             42             41
266          63             75             81
267          69             72             77
268          88             92             95
269          71             76             70
270          69             63             61
271          58             49             42
272          47             53             58
273          65             70             71
274          88             85             76
275          83             78             73
276          85             92             93
277          59             63             75
278          65             86             80
279          73             56             57
280          53             52             42
281          45             48             46
282          73             79             84
283          70             78             78
284          37             46             46
285          81             82             82
286          97             82             88
287          67             89             82
288          88             75             76
289          77             76             77
290          76             70             68
291          86             73             70
292          63             60             57
293          65             73             75
294          78             77             80
295          67             62             60
296          46             41             43
297          71             74             68
298          40             46             50
299          90             87             75
300          81             78             81
301          56             54             52
302          67             84             81
303          80             76             64
304          74             75             83
305          69             67             69
306          99             87             81
307          51             52             44
308          53             71             67
309          49             57             52
310          73             76             80
311          66             60             57
312          67             61             68
313          68             67             69
314          59             64             75
315          71             66             65
316          77             82             91
317          83             72             78
318          63             71             69
319          56             65             63
320          67             79             84
321          75             86             79
322          71             81             80
323          43             53             53
324          41             46             43
325          82             90             94
326          61             61             62
327          28             23             19
328          82             75             77
329          41             55             51
330          71             60             61
331          47             37             35
332          62             56             53
333          90             78             81
334          83             93             95
335          61             68             66
336          76             70             69
337          49             51             43
338          24             38             27
339          35             55             60
340          58             61             52
341          61             73             63
342          69             76             74
343          67             72             67
344          79             73             67
345          72             80             75
346          62             61             57
347          77             94             95
348          75             74             66
349          87             74             76
350          52             65             69
351          66             57             52
352          63             78             80
353          46             58             57
354          59             71             70
355          61             72             70
356          63             61             61
357          42             66             69
358          59             62             61
359          80             90             89
360          58             62             59
361          85             84             78
362          52             58             58
363          27             34             32
364          59             60             58
365          49             58             60
366          69             58             53
367          61             66             61
368          44             64             58
369          73             84             85
370          84             77             71
371          45             73             70
372          74             74             72
373          82             97             96
374          59             70             73
375          46             43             41
376          80             90             82
377          85             95            100
378          71             83             77
379          66             64             62
380          80             86             83
381          87            100             95
382          79             81             71
383          38             49             45
384          38             43             43
385          67             76             75
386          64             73             70
387          57             78             67
388          62             64             64
389          73             70             75
390          73             67             59
391          77             68             77
392          76             67             67
393          57             54             56
394          65             74             77
395          48             45             41
396          50             67             63
397          85             89             95
398          74             63             57
399          60             59             54
400          59             54             67
401          53             43             43
402          49             65             55
403          88             99            100
404          54             59             62
405          63             73             68
406          65             65             63
407          82             80             77
408          52             57             56
409          87             84             85
410          70             71             74
411          84             83             78
412          71             66             60
413          63             67             67
414          51             72             79
415          84             73             69
416          71             74             68
417          74             73             67
418          68             59             62
419          57             56             54
420          82             93             93
421          57             58             64
422          47             58             67
423          59             85             80
424          41             39             34
425          62             67             62
426          86             83             86
427          69             71             65
428          65             59             53
429          68             63             54
430          64             66             59
431          61             72             70
432          61             56             55

# Adding a new column

## Adding a new column with a scalar value

In [45]:
# adding new column
df_exams['Language Score']=70

In [46]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Language Score
0,female,group B,bachelor's degree,standard,none,72,72,74,70
1,female,group C,some college,standard,completed,69,90,88,70
2,female,group B,master's degree,standard,none,90,95,93,70
3,male,group A,associate's degree,free/reduced,none,47,57,44,70
4,male,group C,some college,standard,none,76,78,75,70
5,female,group B,associate's degree,standard,none,71,83,78,70
6,female,group B,some college,standard,completed,88,95,92,70
7,male,group B,some college,free/reduced,none,40,43,39,70
8,male,group D,high school,free/reduced,completed,64,64,67,70
9,female,group B,high school,free/reduced,none,38,60,50,70
10,male,group C,associate's degree,standard,none,58,54,52,70
11,male,group D,associate's degree,standard,none,40,52,43,70
12,female,group B,high school,standard,none,65,81,73,70
13,male,group A,some college,standard,completed,78,72,70,70
14,female,group A,master's degree,standard,none,50,53,58,70
15,female,group C,some high school,standard,none,69,75,78,70
16,male,group C,high school,standard,none,88,89,86,70
17,female,group B,some high school,free/reduced,none,18,32,28,70
18,male,group C,master's degree,free/reduced,completed,46,42,46,70
19,female,group C,associate's degree,free/reduced,none,54,58,61,70
20,male,group D,high school,standard,none,66,69,63,70
21,female,group B,some college,free/reduced,completed,65,75,70,70
22,male,group D,some college,standard,none,44,54,53,70
23,female,group C,some high school,standard,none,69,73,73,70
24,male,group D,bachelor's degree,free/reduced,completed,74,71,80,70
25,male,group A,master's degree,free/reduced,none,73,74,72,70
26,male,group B,some college,standard,none,69,54,55,70
27,female,group C,bachelor's degree,standard,none,67,69,75,70
28,male,group C,high school,standard,none,70,70,65,70
29,female,group D,master's degree,standard,none,62,70,75,70
30,female,group D,some college,standard,none,69,74,74,70
31,female,group B,some college,standard,none,63,65,61,70
32,female,group E,master's degree,free/reduced,none,56,72,65,70
33,male,group D,some college,standard,none,40,42,38,70
34,male,group E,some college,standard,none,97,87,82,70
35,male,group E,associate's degree,standard,completed,81,81,79,70
36,female,group D,associate's degree,standard,none,74,81,83,70
37,female,group D,some high school,free/reduced,none,50,64,59,70
38,female,group D,associate's degree,free/reduced,completed,75,90,88,70
39,male,group B,associate's degree,free/reduced,none,57,56,57,70
40,male,group C,associate's degree,free/reduced,none,55,61,54,70
41,female,group C,associate's degree,standard,none,58,73,68,70
42,female,group B,associate's degree,standard,none,53,58,65,70
43,male,group B,some college,free/reduced,completed,59,65,66,70
44,female,group E,associate's degree,free/reduced,none,50,56,54,70
45,male,group B,associate's degree,standard,none,65,54,57,70
46,female,group A,associate's degree,standard,completed,55,65,62,70
47,female,group C,high school,standard,none,66,71,76,70
48,female,group D,associate's degree,free/reduced,completed,57,74,76,70
49,male,group C,high school,standard,completed,82,84,82,70
50,male,group E,some college,standard,none,53,55,48,70
51,male,group E,associate's degree,free/reduced,completed,77,69,68,70
52,male,group C,some college,standard,none,53,44,42,70
53,male,group D,high school,standard,none,88,78,75,70
54,female,group C,some high school,free/reduced,completed,71,84,87,70
55,female,group C,high school,free/reduced,none,33,41,43,70
56,female,group E,associate's degree,standard,completed,82,85,86,70
57,male,group D,associate's degree,standard,none,52,55,49,70
58,male,group D,some college,standard,completed,58,59,58,70
59,female,group C,some high school,free/reduced,none,0,17,10,70
60,male,group E,bachelor's degree,free/reduced,completed,79,74,72,70
61,male,group A,some high school,free/reduced,none,39,39,34,70
62,male,group A,associate's degree,free/reduced,none,62,61,55,70
63,female,group C,associate's degree,standard,none,69,80,71,70
64,female,group D,some high school,standard,none,59,58,59,70
65,male,group B,some high school,standard,none,67,64,61,70
66,male,group D,some high school,free/reduced,none,45,37,37,70
67,female,group C,some college,standard,none,60,72,74,70
68,male,group B,associate's degree,free/reduced,none,61,58,56,70
69,female,group C,associate's degree,standard,none,39,64,57,70
70,female,group D,some college,free/reduced,completed,58,63,73,70
71,male,group D,some college,standard,completed,63,55,63,70
72,female,group A,associate's degree,free/reduced,none,41,51,48,70
73,male,group C,some high school,free/reduced,none,61,57,56,70
74,male,group C,some high school,standard,none,49,49,41,70
75,male,group B,associate's degree,free/reduced,none,44,41,38,70
76,male,group E,some high school,standard,none,30,26,22,70
77,male,group A,bachelor's degree,standard,completed,80,78,81,70
78,female,group D,some high school,standard,completed,61,74,72,70
79,female,group E,master's degree,standard,none,62,68,68,70
80,female,group B,associate's degree,standard,none,47,49,50,70
81,male,group B,high school,free/reduced,none,49,45,45,70
82,male,group A,some college,free/reduced,completed,50,47,54,70
83,male,group E,associate's degree,standard,none,72,64,63,70
84,male,group D,high school,free/reduced,none,42,39,34,70
85,female,group C,some college,standard,none,73,80,82,70
86,female,group C,some college,free/reduced,none,76,83,88,70
87,female,group D,associate's degree,standard,none,71,71,74,70
88,female,group A,some college,standard,none,58,70,67,70
89,female,group D,some high school,standard,none,73,86,82,70
90,female,group C,bachelor's degree,standard,none,65,72,74,70
91,male,group C,high school,free/reduced,none,27,34,36,70
92,male,group C,high school,standard,none,71,79,71,70
93,male,group C,associate's degree,free/reduced,completed,43,45,50,70
94,female,group B,some college,standard,none,79,86,92,70
95,male,group C,associate's degree,free/reduced,completed,78,81,82,70
96,male,group B,some high school,standard,completed,65,66,62,70
97,female,group E,some college,standard,completed,63,72,70,70
98,female,group D,some college,free/reduced,none,58,67,62,70
99,female,group D,bachelor's degree,standard,none,65,67,62,70
100,male,group B,some college,standard,none,79,67,67,70
101,male,group D,bachelor's degree,standard,completed,68,74,74,70
102,female,group D,associate's degree,standard,none,85,91,89,70
103,male,group B,high school,standard,completed,60,44,47,70
104,male,group C,some college,standard,completed,98,86,90,70
105,female,group C,some college,standard,none,58,67,72,70
106,female,group D,master's degree,standard,none,87,100,100,70
107,male,group E,associate's degree,standard,completed,66,63,64,70
108,female,group B,associate's degree,free/reduced,none,52,76,70,70
109,female,group B,some high school,standard,none,70,64,72,70
110,female,group D,associate's degree,free/reduced,completed,77,89,98,70
111,male,group C,high school,standard,none,62,55,49,70
112,male,group A,associate's degree,standard,none,54,53,47,70
113,female,group D,some college,standard,none,51,58,54,70
114,female,group E,bachelor's degree,standard,completed,99,100,100,70
115,male,group C,high school,standard,none,84,77,74,70
116,female,group B,bachelor's degree,free/reduced,none,75,85,82,70
117,female,group D,bachelor's degree,standard,none,78,82,79,70
118,female,group D,some high school,standard,none,51,63,61,70
119,female,group C,some college,standard,none,55,69,65,70
120,female,group C,bachelor's degree,standard,completed,79,92,89,70
121,male,group B,associate's degree,standard,completed,91,89,92,70
122,female,group C,some college,standard,completed,88,93,93,70
123,male,group D,high school,free/reduced,none,63,57,56,70
124,male,group E,some college,standard,none,83,80,73,70
125,female,group B,high school,standard,none,87,95,86,70
126,male,group B,some high school,standard,none,72,68,67,70
127,male,group D,some college,standard,completed,65,77,74,70
128,male,group D,master's degree,standard,none,82,82,74,70
129,female,group A,bachelor's degree,standard,none,51,49,51,70
130,male,group D,master's degree,standard,none,89,84,82,70
131,male,group C,some high school,free/reduced,completed,53,37,40,70
132,male,group E,some college,free/reduced,completed,87,74,70,70
133,female,group C,some college,standard,completed,75,81,84,70
134,male,group D,bachelor's degree,free/reduced,completed,74,79,75,70
135,male,group C,bachelor's degree,standard,none,58,55,48,70
136,male,group B,some high school,standard,completed,51,54,41,70
137,male,group E,high school,standard,none,70,55,56,70
138,female,group C,associate's degree,standard,none,59,66,67,70
139,male,group D,some college,standard,completed,71,61,69,70
140,female,group D,some high school,standard,none,76,72,71,70
141,female,group C,some college,free/reduced,none,59,62,64,70
142,female,group E,some college,free/reduced,completed,42,55,54,70
143,male,group A,high school,standard,none,57,43,47,70
144,male,group D,some college,standard,none,88,73,78,70
145,female,group C,some college,free/reduced,none,22,39,33,70
146,male,group B,some high school,standard,none,88,84,75,70
147,male,group C,associate's degree,free/reduced,none,73,68,66,70
148,female,group D,bachelor's degree,standard,completed,68,75,81,70
149,male,group E,associate's degree,free/reduced,completed,100,100,93,70
150,male,group A,some high school,standard,completed,62,67,69,70
151,male,group A,bachelor's degree,standard,none,77,67,68,70
152,female,group B,associate's degree,standard,completed,59,70,66,70
153,male,group D,bachelor's degree,standard,none,54,49,47,70
154,male,group D,some high school,standard,none,62,67,61,70
155,female,group C,some college,standard,completed,70,89,88,70
156,female,group E,high school,free/reduced,completed,66,74,78,70
157,male,group B,some college,free/reduced,none,60,60,60,70
158,female,group B,associate's degree,standard,completed,61,86,87,70
159,male,group D,associate's degree,free/reduced,none,66,62,64,70
160,male,group B,associate's degree,free/reduced,completed,82,78,74,70
161,female,group E,some college,free/reduced,completed,75,88,85,70
162,male,group B,master's degree,free/reduced,none,49,53,52,70
163,male,group C,high school,standard,none,52,53,49,70
164,female,group E,master's degree,standard,none,81,92,91,70
165,female,group C,bachelor's degree,standard,completed,96,100,100,70
166,male,group C,high school,free/reduced,completed,53,51,51,70
167,female,group B,master's degree,free/reduced,completed,58,76,78,70
168,female,group B,high school,standard,completed,68,83,78,70
169,female,group C,some college,free/reduced,completed,67,75,70,70
170,male,group A,high school,standard,completed,72,73,74,70
171,male,group E,some high school,standard,none,94,88,78,70
172,female,group D,some college,standard,none,79,86,81,70
173,female,group C,associate's degree,standard,none,63,67,70,70
174,female,group C,bachelor's degree,free/reduced,completed,43,51,54,70
175,female,group C,master's degree,standard,completed,81,91,87,70
176,female,group B,high school,free/reduced,completed,46,54,58,70
177,female,group C,associate's degree,standard,completed,71,77,77,70
178,female,group B,master's degree,free/reduced,completed,52,70,62,70
179,female,group D,some high school,standard,completed,97,100,100,70
180,male,group C,master's degree,free/reduced,completed,62,68,75,70
181,female,group C,some college,free/reduced,none,46,64,66,70
182,female,group E,high school,standard,none,50,50,47,70
183,female,group D,associate's degree,standard,none,65,69,70,70
184,male,group C,some high school,free/reduced,completed,45,52,49,70
185,male,group C,associate's degree,free/reduced,completed,65,67,65,70
186,male,group E,high school,standard,none,80,76,65,70
187,male,group D,some high school,standard,completed,62,66,68,70
188,male,group B,some high school,free/reduced,none,48,52,45,70
189,female,group C,bachelor's degree,standard,none,77,88,87,70
190,female,group E,associate's degree,standard,none,66,65,69,70
191,male,group D,some college,standard,completed,76,83,79,70
192,female,group B,some high school,standard,none,62,64,66,70
193,male,group D,some college,standard,completed,77,62,62,70
194,female,group C,master's degree,standard,completed,69,84,85,70
195,male,group D,associate's degree,standard,none,61,55,52,70
196,male,group C,some high school,free/reduced,completed,59,69,65,70
197,male,group E,high school,free/reduced,none,55,56,51,70
198,female,group B,some college,free/reduced,none,45,53,55,70
199,female,group B,bachelor's degree,free/reduced,none,78,79,76,70
200,female,group C,associate's degree,standard,completed,67,84,86,70
201,female,group D,some college,free/reduced,none,65,81,77,70
202,male,group C,associate's degree,standard,none,69,77,69,70
203,female,group B,associate's degree,standard,none,57,69,68,70
204,male,group C,some college,standard,none,59,41,42,70
205,male,group D,some high school,standard,completed,74,71,78,70
206,male,group E,bachelor's degree,standard,none,82,62,62,70
207,male,group E,high school,standard,completed,81,80,76,70
208,female,group B,some college,free/reduced,none,74,81,76,70
209,female,group B,some college,free/reduced,none,58,61,66,70
210,male,group D,some high school,free/reduced,completed,80,79,79,70
211,male,group C,some college,free/reduced,none,35,28,27,70
212,female,group C,high school,free/reduced,none,42,62,60,70
213,male,group C,associate's degree,free/reduced,completed,60,51,56,70
214,male,group E,high school,standard,completed,87,91,81,70
215,male,group B,some high school,standard,completed,84,83,75,70
216,female,group E,associate's degree,free/reduced,completed,83,86,88,70
217,female,group C,high school,free/reduced,none,34,42,39,70
218,male,group B,high school,free/reduced,none,66,77,70,70
219,male,group B,some high school,standard,completed,61,56,56,70
220,female,group D,high school,standard,completed,56,68,74,70
221,male,group B,associate's degree,standard,none,87,85,73,70
222,female,group C,some high school,free/reduced,none,55,65,62,70
223,male,group D,some high school,standard,none,86,80,75,70
224,female,group B,associate's degree,standard,completed,52,66,73,70
225,female,group E,master's degree,free/reduced,none,45,56,54,70
226,female,group C,some college,standard,none,72,72,71,70
227,male,group D,high school,standard,none,57,50,54,70
228,male,group A,some high school,free/reduced,none,68,72,64,70
229,female,group C,some college,standard,completed,88,95,94,70
230,male,group D,some college,standard,none,76,64,66,70
231,male,group C,associate's degree,standard,none,46,43,42,70
232,female,group B,bachelor's degree,standard,none,67,86,83,70
233,male,group E,some high school,standard,none,92,87,78,70
234,male,group C,bachelor's degree,standard,completed,83,82,84,70
235,male,group D,associate's degree,standard,none,80,75,77,70
236,male,group D,bachelor's degree,free/reduced,none,63,66,67,70
237,female,group D,some high school,standard,completed,64,60,74,70
238,male,group B,some college,standard,none,54,52,51,70
239,male,group C,associate's degree,standard,none,84,80,80,70
240,male,group D,high school,free/reduced,completed,73,68,66,70
241,female,group E,bachelor's degree,standard,none,80,83,83,70
242,female,group D,high school,standard,none,56,52,55,70
243,male,group E,some college,standard,none,59,51,43,70
244,male,group D,some high school,standard,none,75,74,69,70
245,male,group C,associate's degree,standard,none,85,76,71,70
246,male,group E,associate's degree,standard,none,89,76,74,70
247,female,group B,high school,standard,completed,58,70,68,70
248,female,group B,high school,standard,none,65,64,62,70
249,male,group C,high school,standard,none,68,60,53,70
250,male,group A,some high school,standard,completed,47,49,49,70
251,female,group D,some college,free/reduced,none,71,83,83,70
252,female,group B,some high school,standard,completed,60,70,70,70
253,male,group D,master's degree,standard,none,80,80,72,70
254,male,group D,high school,standard,none,54,52,52,70
255,female,group E,some college,standard,none,62,73,70,70
256,female,group C,associate's degree,free/reduced,none,64,73,68,70
257,male,group C,associate's degree,standard,completed,78,77,77,70
258,female,group B,some college,standard,none,70,75,78,70
259,female,group C,master's degree,free/reduced,completed,65,81,81,70
260,female,group C,some high school,free/reduced,completed,64,79,77,70
261,male,group C,some college,standard,completed,79,79,78,70
262,female,group C,some high school,free/reduced,none,44,50,51,70
263,female,group E,high school,standard,none,99,93,90,70
264,male,group D,high school,standard,none,76,73,68,70
265,male,group D,some high school,free/reduced,none,59,42,41,70
266,female,group C,bachelor's degree,standard,none,63,75,81,70
267,female,group D,high school,standard,none,69,72,77,70
268,female,group D,associate's degree,standard,completed,88,92,95,70
269,female,group E,some college,free/reduced,none,71,76,70,70
270,male,group C,bachelor's degree,standard,none,69,63,61,70
271,male,group C,some college,standard,none,58,49,42,70
272,female,group D,associate's degree,free/reduced,none,47,53,58,70
273,female,group D,some college,standard,none,65,70,71,70
274,male,group B,some college,standard,completed,88,85,76,70
275,male,group C,bachelor's degree,standard,none,83,78,73,70
276,female,group C,some high school,standard,completed,85,92,93,70
277,female,group E,high school,standard,completed,59,63,75,70
278,female,group C,some high school,free/reduced,none,65,86,80,70
279,male,group B,bachelor's degree,free/reduced,none,73,56,57,70
280,male,group D,high school,standard,none,53,52,42,70
281,male,group D,high school,standard,none,45,48,46,70
282,female,group D,bachelor's degree,free/reduced,none,73,79,84,70
283,female,group D,some college,free/reduced,completed,70,78,78,70
284,female,group B,some high school,standard,none,37,46,46,70
285,male,group B,associate's degree,standard,completed,81,82,82,70
286,male,group E,associate's degree,standard,completed,97,82,88,70
287,female,group B,some high school,standard,none,67,89,82,70
288,male,group B,bachelor's degree,free/reduced,none,88,75,76,70
289,male,group E,some high school,standard,completed,77,76,77,70
290,male,group C,associate's degree,standard,none,76,70,68,70
291,male,group D,some high school,standard,none,86,73,70,70
292,male,group C,some high school,standard,completed,63,60,57,70
293,female,group E,bachelor's degree,standard,none,65,73,75,70
294,male,group D,high school,free/reduced,completed,78,77,80,70
295,male,group B,associate's degree,free/reduced,none,67,62,60,70
296,male,group A,some high school,standard,completed,46,41,43,70
297,male,group E,associate's degree,standard,completed,71,74,68,70
298,male,group C,high school,free/reduced,completed,40,46,50,70
299,male,group D,associate's degree,free/reduced,none,90,87,75,70
300,male,group A,some college,free/reduced,completed,81,78,81,70
301,male,group D,some high school,free/reduced,none,56,54,52,70
302,female,group C,associate's degree,standard,completed,67,84,81,70
303,male,group B,associate's degree,standard,none,80,76,64,70
304,female,group C,associate's degree,standard,completed,74,75,83,70
305,male,group A,some college,standard,none,69,67,69,70
306,male,group E,some college,standard,completed,99,87,81,70
307,male,group C,some high school,standard,none,51,52,44,70
308,female,group B,associate's degree,free/reduced,none,53,71,67,70
309,female,group D,high school,free/reduced,none,49,57,52,70
310,female,group B,associate's degree,standard,none,73,76,80,70
311,male,group B,bachelor's degree,standard,none,66,60,57,70
312,male,group D,bachelor's degree,standard,completed,67,61,68,70
313,female,group C,associate's degree,free/reduced,completed,68,67,69,70
314,female,group C,bachelor's degree,standard,completed,59,64,75,70
315,male,group C,high school,standard,none,71,66,65,70
316,female,group D,master's degree,standard,completed,77,82,91,70

## Adding a new column with an array

In [47]:
# create an array of 1000 elements
languageScoore = np.arange(0, 1000)

In [48]:
len(languageScoore)

1000

In [49]:
# populating column with data
df_exams['Language Score'] = languageScoore[:len(df_exams)]
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Language Score
0,female,group B,bachelor's degree,standard,none,72,72,74,0
1,female,group C,some college,standard,completed,69,90,88,1
2,female,group B,master's degree,standard,none,90,95,93,2
3,male,group A,associate's degree,free/reduced,none,47,57,44,3
4,male,group C,some college,standard,none,76,78,75,4
5,female,group B,associate's degree,standard,none,71,83,78,5
6,female,group B,some college,standard,completed,88,95,92,6
7,male,group B,some college,free/reduced,none,40,43,39,7
8,male,group D,high school,free/reduced,completed,64,64,67,8
9,female,group B,high school,free/reduced,none,38,60,50,9
10,male,group C,associate's degree,standard,none,58,54,52,10
11,male,group D,associate's degree,standard,none,40,52,43,11
12,female,group B,high school,standard,none,65,81,73,12
13,male,group A,some college,standard,completed,78,72,70,13
14,female,group A,master's degree,standard,none,50,53,58,14
15,female,group C,some high school,standard,none,69,75,78,15
16,male,group C,high school,standard,none,88,89,86,16
17,female,group B,some high school,free/reduced,none,18,32,28,17
18,male,group C,master's degree,free/reduced,completed,46,42,46,18
19,female,group C,associate's degree,free/reduced,none,54,58,61,19
20,male,group D,high school,standard,none,66,69,63,20
21,female,group B,some college,free/reduced,completed,65,75,70,21
22,male,group D,some college,standard,none,44,54,53,22
23,female,group C,some high school,standard,none,69,73,73,23
24,male,group D,bachelor's degree,free/reduced,completed,74,71,80,24
25,male,group A,master's degree,free/reduced,none,73,74,72,25
26,male,group B,some college,standard,none,69,54,55,26
27,female,group C,bachelor's degree,standard,none,67,69,75,27
28,male,group C,high school,standard,none,70,70,65,28
29,female,group D,master's degree,standard,none,62,70,75,29
30,female,group D,some college,standard,none,69,74,74,30
31,female,group B,some college,standard,none,63,65,61,31
32,female,group E,master's degree,free/reduced,none,56,72,65,32
33,male,group D,some college,standard,none,40,42,38,33
34,male,group E,some college,standard,none,97,87,82,34
35,male,group E,associate's degree,standard,completed,81,81,79,35
36,female,group D,associate's degree,standard,none,74,81,83,36
37,female,group D,some high school,free/reduced,none,50,64,59,37
38,female,group D,associate's degree,free/reduced,completed,75,90,88,38
39,male,group B,associate's degree,free/reduced,none,57,56,57,39
40,male,group C,associate's degree,free/reduced,none,55,61,54,40
41,female,group C,associate's degree,standard,none,58,73,68,41
42,female,group B,associate's degree,standard,none,53,58,65,42
43,male,group B,some college,free/reduced,completed,59,65,66,43
44,female,group E,associate's degree,free/reduced,none,50,56,54,44
45,male,group B,associate's degree,standard,none,65,54,57,45
46,female,group A,associate's degree,standard,completed,55,65,62,46
47,female,group C,high school,standard,none,66,71,76,47
48,female,group D,associate's degree,free/reduced,completed,57,74,76,48
49,male,group C,high school,standard,completed,82,84,82,49
50,male,group E,some college,standard,none,53,55,48,50
51,male,group E,associate's degree,free/reduced,completed,77,69,68,51
52,male,group C,some college,standard,none,53,44,42,52
53,male,group D,high school,standard,none,88,78,75,53
54,female,group C,some high school,free/reduced,completed,71,84,87,54
55,female,group C,high school,free/reduced,none,33,41,43,55
56,female,group E,associate's degree,standard,completed,82,85,86,56
57,male,group D,associate's degree,standard,none,52,55,49,57
58,male,group D,some college,standard,completed,58,59,58,58
59,female,group C,some high school,free/reduced,none,0,17,10,59
60,male,group E,bachelor's degree,free/reduced,completed,79,74,72,60
61,male,group A,some high school,free/reduced,none,39,39,34,61
62,male,group A,associate's degree,free/reduced,none,62,61,55,62
63,female,group C,associate's degree,standard,none,69,80,71,63
64,female,group D,some high school,standard,none,59,58,59,64
65,male,group B,some high school,standard,none,67,64,61,65
66,male,group D,some high school,free/reduced,none,45,37,37,66
67,female,group C,some college,standard,none,60,72,74,67
68,male,group B,associate's degree,free/reduced,none,61,58,56,68
69,female,group C,associate's degree,standard,none,39,64,57,69
70,female,group D,some college,free/reduced,completed,58,63,73,70
71,male,group D,some college,standard,completed,63,55,63,71
72,female,group A,associate's degree,free/reduced,none,41,51,48,72
73,male,group C,some high school,free/reduced,none,61,57,56,73
74,male,group C,some high school,standard,none,49,49,41,74
75,male,group B,associate's degree,free/reduced,none,44,41,38,75
76,male,group E,some high school,standard,none,30,26,22,76
77,male,group A,bachelor's degree,standard,completed,80,78,81,77
78,female,group D,some high school,standard,completed,61,74,72,78
79,female,group E,master's degree,standard,none,62,68,68,79
80,female,group B,associate's degree,standard,none,47,49,50,80
81,male,group B,high school,free/reduced,none,49,45,45,81
82,male,group A,some college,free/reduced,completed,50,47,54,82
83,male,group E,associate's degree,standard,none,72,64,63,83
84,male,group D,high school,free/reduced,none,42,39,34,84
85,female,group C,some college,standard,none,73,80,82,85
86,female,group C,some college,free/reduced,none,76,83,88,86
87,female,group D,associate's degree,standard,none,71,71,74,87
88,female,group A,some college,standard,none,58,70,67,88
89,female,group D,some high school,standard,none,73,86,82,89
90,female,group C,bachelor's degree,standard,none,65,72,74,90
91,male,group C,high school,free/reduced,none,27,34,36,91
92,male,group C,high school,standard,none,71,79,71,92
93,male,group C,associate's degree,free/reduced,completed,43,45,50,93
94,female,group B,some college,standard,none,79,86,92,94
95,male,group C,associate's degree,free/reduced,completed,78,81,82,95
96,male,group B,some high school,standard,completed,65,66,62,96
97,female,group E,some college,standard,completed,63,72,70,97
98,female,group D,some college,free/reduced,none,58,67,62,98
99,female,group D,bachelor's degree,standard,none,65,67,62,99
100,male,group B,some college,standard,none,79,67,67,100
101,male,group D,bachelor's degree,standard,completed,68,74,74,101
102,female,group D,associate's degree,standard,none,85,91,89,102
103,male,group B,high school,standard,completed,60,44,47,103
104,male,group C,some college,standard,completed,98,86,90,104
105,female,group C,some college,standard,none,58,67,72,105
106,female,group D,master's degree,standard,none,87,100,100,106
107,male,group E,associate's degree,standard,completed,66,63,64,107
108,female,group B,associate's degree,free/reduced,none,52,76,70,108
109,female,group B,some high school,standard,none,70,64,72,109
110,female,group D,associate's degree,free/reduced,completed,77,89,98,110
111,male,group C,high school,standard,none,62,55,49,111
112,male,group A,associate's degree,standard,none,54,53,47,112
113,female,group D,some college,standard,none,51,58,54,113
114,female,group E,bachelor's degree,standard,completed,99,100,100,114
115,male,group C,high school,standard,none,84,77,74,115
116,female,group B,bachelor's degree,free/reduced,none,75,85,82,116
117,female,group D,bachelor's degree,standard,none,78,82,79,117
118,female,group D,some high school,standard,none,51,63,61,118
119,female,group C,some college,standard,none,55,69,65,119
120,female,group C,bachelor's degree,standard,completed,79,92,89,120
121,male,group B,associate's degree,standard,completed,91,89,92,121
122,female,group C,some college,standard,completed,88,93,93,122
123,male,group D,high school,free/reduced,none,63,57,56,123
124,male,group E,some college,standard,none,83,80,73,124
125,female,group B,high school,standard,none,87,95,86,125
126,male,group B,some high school,standard,none,72,68,67,126
127,male,group D,some college,standard,completed,65,77,74,127
128,male,group D,master's degree,standard,none,82,82,74,128
129,female,group A,bachelor's degree,standard,none,51,49,51,129
130,male,group D,master's degree,standard,none,89,84,82,130
131,male,group C,some high school,free/reduced,completed,53,37,40,131
132,male,group E,some college,free/reduced,completed,87,74,70,132
133,female,group C,some college,standard,completed,75,81,84,133
134,male,group D,bachelor's degree,free/reduced,completed,74,79,75,134
135,male,group C,bachelor's degree,standard,none,58,55,48,135
136,male,group B,some high school,standard,completed,51,54,41,136
137,male,group E,high school,standard,none,70,55,56,137
138,female,group C,associate's degree,standard,none,59,66,67,138
139,male,group D,some college,standard,completed,71,61,69,139
140,female,group D,some high school,standard,none,76,72,71,140
141,female,group C,some college,free/reduced,none,59,62,64,141
142,female,group E,some college,free/reduced,completed,42,55,54,142
143,male,group A,high school,standard,none,57,43,47,143
144,male,group D,some college,standard,none,88,73,78,144
145,female,group C,some college,free/reduced,none,22,39,33,145
146,male,group B,some high school,standard,none,88,84,75,146
147,male,group C,associate's degree,free/reduced,none,73,68,66,147
148,female,group D,bachelor's degree,standard,completed,68,75,81,148
149,male,group E,associate's degree,free/reduced,completed,100,100,93,149
150,male,group A,some high school,standard,completed,62,67,69,150
151,male,group A,bachelor's degree,standard,none,77,67,68,151
152,female,group B,associate's degree,standard,completed,59,70,66,152
153,male,group D,bachelor's degree,standard,none,54,49,47,153
154,male,group D,some high school,standard,none,62,67,61,154
155,female,group C,some college,standard,completed,70,89,88,155
156,female,group E,high school,free/reduced,completed,66,74,78,156
157,male,group B,some college,free/reduced,none,60,60,60,157
158,female,group B,associate's degree,standard,completed,61,86,87,158
159,male,group D,associate's degree,free/reduced,none,66,62,64,159
160,male,group B,associate's degree,free/reduced,completed,82,78,74,160
161,female,group E,some college,free/reduced,completed,75,88,85,161
162,male,group B,master's degree,free/reduced,none,49,53,52,162
163,male,group C,high school,standard,none,52,53,49,163
164,female,group E,master's degree,standard,none,81,92,91,164
165,female,group C,bachelor's degree,standard,completed,96,100,100,165
166,male,group C,high school,free/reduced,completed,53,51,51,166
167,female,group B,master's degree,free/reduced,completed,58,76,78,167
168,female,group B,high school,standard,completed,68,83,78,168
169,female,group C,some college,free/reduced,completed,67,75,70,169
170,male,group A,high school,standard,completed,72,73,74,170
171,male,group E,some high school,standard,none,94,88,78,171
172,female,group D,some college,standard,none,79,86,81,172
173,female,group C,associate's degree,standard,none,63,67,70,173
174,female,group C,bachelor's degree,free/reduced,completed,43,51,54,174
175,female,group C,master's degree,standard,completed,81,91,87,175
176,female,group B,high school,free/reduced,completed,46,54,58,176
177,female,group C,associate's degree,standard,completed,71,77,77,177
178,female,group B,master's degree,free/reduced,completed,52,70,62,178
179,female,group D,some high school,standard,completed,97,100,100,179
180,male,group C,master's degree,free/reduced,completed,62,68,75,180
181,female,group C,some college,free/reduced,none,46,64,66,181
182,female,group E,high school,standard,none,50,50,47,182
183,female,group D,associate's degree,standard,none,65,69,70,183
184,male,group C,some high school,free/reduced,completed,45,52,49,184
185,male,group C,associate's degree,free/reduced,completed,65,67,65,185
186,male,group E,high school,standard,none,80,76,65,186
187,male,group D,some high school,standard,completed,62,66,68,187
188,male,group B,some high school,free/reduced,none,48,52,45,188
189,female,group C,bachelor's degree,standard,none,77,88,87,189
190,female,group E,associate's degree,standard,none,66,65,69,190
191,male,group D,some college,standard,completed,76,83,79,191
192,female,group B,some high school,standard,none,62,64,66,192
193,male,group D,some college,standard,completed,77,62,62,193
194,female,group C,master's degree,standard,completed,69,84,85,194
195,male,group D,associate's degree,standard,none,61,55,52,195
196,male,group C,some high school,free/reduced,completed,59,69,65,196
197,male,group E,high school,free/reduced,none,55,56,51,197
198,female,group B,some college,free/reduced,none,45,53,55,198
199,female,group B,bachelor's degree,free/reduced,none,78,79,76,199
200,female,group C,associate's degree,standard,completed,67,84,86,200
201,female,group D,some college,free/reduced,none,65,81,77,201
202,male,group C,associate's degree,standard,none,69,77,69,202
203,female,group B,associate's degree,standard,none,57,69,68,203
204,male,group C,some college,standard,none,59,41,42,204
205,male,group D,some high school,standard,completed,74,71,78,205
206,male,group E,bachelor's degree,standard,none,82,62,62,206
207,male,group E,high school,standard,completed,81,80,76,207
208,female,group B,some college,free/reduced,none,74,81,76,208
209,female,group B,some college,free/reduced,none,58,61,66,209
210,male,group D,some high school,free/reduced,completed,80,79,79,210
211,male,group C,some college,free/reduced,none,35,28,27,211
212,female,group C,high school,free/reduced,none,42,62,60,212
213,male,group C,associate's degree,free/reduced,completed,60,51,56,213
214,male,group E,high school,standard,completed,87,91,81,214
215,male,group B,some high school,standard,completed,84,83,75,215
216,female,group E,associate's degree,free/reduced,completed,83,86,88,216
217,female,group C,high school,free/reduced,none,34,42,39,217
218,male,group B,high school,free/reduced,none,66,77,70,218
219,male,group B,some high school,standard,completed,61,56,56,219
220,female,group D,high school,standard,completed,56,68,74,220
221,male,group B,associate's degree,standard,none,87,85,73,221
222,female,group C,some high school,free/reduced,none,55,65,62,222
223,male,group D,some high school,standard,none,86,80,75,223
224,female,group B,associate's degree,standard,completed,52,66,73,224
225,female,group E,master's degree,free/reduced,none,45,56,54,225
226,female,group C,some college,standard,none,72,72,71,226
227,male,group D,high school,standard,none,57,50,54,227
228,male,group A,some high school,free/reduced,none,68,72,64,228
229,female,group C,some college,standard,completed,88,95,94,229
230,male,group D,some college,standard,none,76,64,66,230
231,male,group C,associate's degree,standard,none,46,43,42,231
232,female,group B,bachelor's degree,standard,none,67,86,83,232
233,male,group E,some high school,standard,none,92,87,78,233
234,male,group C,bachelor's degree,standard,completed,83,82,84,234
235,male,group D,associate's degree,standard,none,80,75,77,235
236,male,group D,bachelor's degree,free/reduced,none,63,66,67,236
237,female,group D,some high school,standard,completed,64,60,74,237
238,male,group B,some college,standard,none,54,52,51,238
239,male,group C,associate's degree,standard,none,84,80,80,239
240,male,group D,high school,free/reduced,completed,73,68,66,240
241,female,group E,bachelor's degree,standard,none,80,83,83,241
242,female,group D,high school,standard,none,56,52,55,242
243,male,group E,some college,standard,none,59,51,43,243
244,male,group D,some high school,standard,none,75,74,69,244
245,male,group C,associate's degree,standard,none,85,76,71,245
246,male,group E,associate's degree,standard,none,89,76,74,246
247,female,group B,high school,standard,completed,58,70,68,247
248,female,group B,high school,standard,none,65,64,62,248
249,male,group C,high school,standard,none,68,60,53,249
250,male,group A,some high school,standard,completed,47,49,49,250
251,female,group D,some college,free/reduced,none,71,83,83,251
252,female,group B,some high school,standard,completed,60,70,70,252
253,male,group D,master's degree,standard,none,80,80,72,253
254,male,group D,high school,standard,none,54,52,52,254
255,female,group E,some college,standard,none,62,73,70,255
256,female,group C,associate's degree,free/reduced,none,64,73,68,256
257,male,group C,associate's degree,standard,completed,78,77,77,257
258,female,group B,some college,standard,none,70,75,78,258
259,female,group C,master's degree,free/reduced,completed,65,81,81,259
260,female,group C,some high school,free/reduced,completed,64,79,77,260
261,male,group C,some college,standard,completed,79,79,78,261
262,female,group C,some high school,free/reduced,none,44,50,51,262
263,female,group E,high school,standard,none,99,93,90,263
264,male,group D,high school,standard,none,76,73,68,264
265,male,group D,some high school,free/reduced,none,59,42,41,265
266,female,group C,bachelor's degree,standard,none,63,75,81,266
267,female,group D,high school,standard,none,69,72,77,267
268,female,group D,associate's degree,standard,completed,88,92,95,268
269,female,group E,some college,free/reduced,none,71,76,70,269
270,male,group C,bachelor's degree,standard,none,69,63,61,270
271,male,group C,some college,standard,none,58,49,42,271
272,female,group D,associate's degree,free/reduced,none,47,53,58,272
273,female,group D,some college,standard,none,65,70,71,273
274,male,group B,some college,standard,completed,88,85,76,274
275,male,group C,bachelor's degree,standard,none,83,78,73,275
276,female,group C,some high school,standard,completed,85,92,93,276
277,female,group E,high school,standard,completed,59,63,75,277
278,female,group C,some high school,free/reduced,none,65,86,80,278
279,male,group B,bachelor's degree,free/reduced,none,73,56,57,279
280,male,group D,high school,standard,none,53,52,42,280
281,male,group D,high school,standard,none,45,48,46,281
282,female,group D,bachelor's degree,free/reduced,none,73,79,84,282
283,female,group D,some college,free/reduced,completed,70,78,78,283
284,female,group B,some high school,standard,none,37,46,46,284
285,male,group B,associate's degree,standard,completed,81,82,82,285
286,male,group E,associate's degree,standard,completed,97,82,88,286
287,female,group B,some high school,standard,none,67,89,82,287
288,male,group B,bachelor's degree,free/reduced,none,88,75,76,288
289,male,group E,some high school,standard,completed,77,76,77,289
290,male,group C,associate's degree,standard,none,76,70,68,290
291,male,group D,some high school,standard,none,86,73,70,291
292,male,group C,some high school,standard,completed,63,60,57,292
293,female,group E,bachelor's degree,standard,none,65,73,75,293
294,male,group D,high school,free/reduced,completed,78,77,80,294
295,male,group B,associate's degree,free/reduced,none,67,62,60,295
296,male,group A,some high school,standard,completed,46,41,43,296
297,male,group E,associate's degree,standard,completed,71,74,68,297
298,male,group C,high school,free/reduced,completed,40,46,50,298
299,male,group D,associate's degree,free/reduced,none,90,87,75,299
300,male,group A,some college,free/reduced,completed,81,78,81,300
301,male,group D,some high school,free/reduced,none,56,54,52,301
302,female,group C,associate's degree,standard,completed,67,84,81,302
303,male,group B,associate's degree,standard,none,80,76,64,303
304,female,group C,associate's degree,standard,completed,74,75,83,304
305,male,group A,some college,standard,none,69,67,69,305
306,male,group E,some college,standard,completed,99,87,81,306
307,male,group C,some high school,standard,none,51,52,44,307
308,female,group B,associate's degree,free/reduced,none,53,71,67,308
309,female,group D,high school,free/reduced,none,49,57,52,309
310,female,group B,associate's degree,standard,none,73,76,80,310
311,male,group B,bachelor's degree,standard,none,66,60,57,311
312,male,group D,bachelor's degree,standard,completed,67,61,68,312

In [50]:
# create random int array
languageScoore = np.random.randint(0,101, size=(len(df_exams)))

In [51]:
df_exams["Language Score"] = languageScoore[:len(df_exams)]
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Language Score
0,female,group B,bachelor's degree,standard,none,72,72,74,34
1,female,group C,some college,standard,completed,69,90,88,71
2,female,group B,master's degree,standard,none,90,95,93,75
3,male,group A,associate's degree,free/reduced,none,47,57,44,86
4,male,group C,some college,standard,none,76,78,75,44
5,female,group B,associate's degree,standard,none,71,83,78,30
6,female,group B,some college,standard,completed,88,95,92,15
7,male,group B,some college,free/reduced,none,40,43,39,70
8,male,group D,high school,free/reduced,completed,64,64,67,56
9,female,group B,high school,free/reduced,none,38,60,50,81
10,male,group C,associate's degree,standard,none,58,54,52,76
11,male,group D,associate's degree,standard,none,40,52,43,43
12,female,group B,high school,standard,none,65,81,73,36
13,male,group A,some college,standard,completed,78,72,70,11
14,female,group A,master's degree,standard,none,50,53,58,43
15,female,group C,some high school,standard,none,69,75,78,67
16,male,group C,high school,standard,none,88,89,86,40
17,female,group B,some high school,free/reduced,none,18,32,28,90
18,male,group C,master's degree,free/reduced,completed,46,42,46,33
19,female,group C,associate's degree,free/reduced,none,54,58,61,98
20,male,group D,high school,standard,none,66,69,63,93
21,female,group B,some college,free/reduced,completed,65,75,70,58
22,male,group D,some college,standard,none,44,54,53,18
23,female,group C,some high school,standard,none,69,73,73,83
24,male,group D,bachelor's degree,free/reduced,completed,74,71,80,51
25,male,group A,master's degree,free/reduced,none,73,74,72,19
26,male,group B,some college,standard,none,69,54,55,1
27,female,group C,bachelor's degree,standard,none,67,69,75,11
28,male,group C,high school,standard,none,70,70,65,79
29,female,group D,master's degree,standard,none,62,70,75,2
30,female,group D,some college,standard,none,69,74,74,21
31,female,group B,some college,standard,none,63,65,61,94
32,female,group E,master's degree,free/reduced,none,56,72,65,9
33,male,group D,some college,standard,none,40,42,38,9
34,male,group E,some college,standard,none,97,87,82,49
35,male,group E,associate's degree,standard,completed,81,81,79,15
36,female,group D,associate's degree,standard,none,74,81,83,57
37,female,group D,some high school,free/reduced,none,50,64,59,33
38,female,group D,associate's degree,free/reduced,completed,75,90,88,6
39,male,group B,associate's degree,free/reduced,none,57,56,57,57
40,male,group C,associate's degree,free/reduced,none,55,61,54,34
41,female,group C,associate's degree,standard,none,58,73,68,12
42,female,group B,associate's degree,standard,none,53,58,65,41
43,male,group B,some college,free/reduced,completed,59,65,66,38
44,female,group E,associate's degree,free/reduced,none,50,56,54,98
45,male,group B,associate's degree,standard,none,65,54,57,10
46,female,group A,associate's degree,standard,completed,55,65,62,47
47,female,group C,high school,standard,none,66,71,76,87
48,female,group D,associate's degree,free/reduced,completed,57,74,76,55
49,male,group C,high school,standard,completed,82,84,82,37
50,male,group E,some college,standard,none,53,55,48,56
51,male,group E,associate's degree,free/reduced,completed,77,69,68,15
52,male,group C,some college,standard,none,53,44,42,34
53,male,group D,high school,standard,none,88,78,75,1
54,female,group C,some high school,free/reduced,completed,71,84,87,24
55,female,group C,high school,free/reduced,none,33,41,43,72
56,female,group E,associate's degree,standard,completed,82,85,86,24
57,male,group D,associate's degree,standard,none,52,55,49,43
58,male,group D,some college,standard,completed,58,59,58,18
59,female,group C,some high school,free/reduced,none,0,17,10,81
60,male,group E,bachelor's degree,free/reduced,completed,79,74,72,67
61,male,group A,some high school,free/reduced,none,39,39,34,99
62,male,group A,associate's degree,free/reduced,none,62,61,55,3
63,female,group C,associate's degree,standard,none,69,80,71,52
64,female,group D,some high school,standard,none,59,58,59,68
65,male,group B,some high school,standard,none,67,64,61,33
66,male,group D,some high school,free/reduced,none,45,37,37,62
67,female,group C,some college,standard,none,60,72,74,92
68,male,group B,associate's degree,free/reduced,none,61,58,56,99
69,female,group C,associate's degree,standard,none,39,64,57,91
70,female,group D,some college,free/reduced,completed,58,63,73,73
71,male,group D,some college,standard,completed,63,55,63,67
72,female,group A,associate's degree,free/reduced,none,41,51,48,10
73,male,group C,some high school,free/reduced,none,61,57,56,39
74,male,group C,some high school,standard,none,49,49,41,30
75,male,group B,associate's degree,free/reduced,none,44,41,38,16
76,male,group E,some high school,standard,none,30,26,22,75
77,male,group A,bachelor's degree,standard,completed,80,78,81,52
78,female,group D,some high school,standard,completed,61,74,72,53
79,female,group E,master's degree,standard,none,62,68,68,100
80,female,group B,associate's degree,standard,none,47,49,50,4
81,male,group B,high school,free/reduced,none,49,45,45,97
82,male,group A,some college,free/reduced,completed,50,47,54,73
83,male,group E,associate's degree,standard,none,72,64,63,30
84,male,group D,high school,free/reduced,none,42,39,34,54
85,female,group C,some college,standard,none,73,80,82,50
86,female,group C,some college,free/reduced,none,76,83,88,67
87,female,group D,associate's degree,standard,none,71,71,74,80
88,female,group A,some college,standard,none,58,70,67,65
89,female,group D,some high school,standard,none,73,86,82,47
90,female,group C,bachelor's degree,standard,none,65,72,74,4
91,male,group C,high school,free/reduced,none,27,34,36,23
92,male,group C,high school,standard,none,71,79,71,69
93,male,group C,associate's degree,free/reduced,completed,43,45,50,86
94,female,group B,some college,standard,none,79,86,92,48
95,male,group C,associate's degree,free/reduced,completed,78,81,82,72
96,male,group B,some high school,standard,completed,65,66,62,45
97,female,group E,some college,standard,completed,63,72,70,59
98,female,group D,some college,free/reduced,none,58,67,62,94
99,female,group D,bachelor's degree,standard,none,65,67,62,34
100,male,group B,some college,standard,none,79,67,67,96
101,male,group D,bachelor's degree,standard,completed,68,74,74,84
102,female,group D,associate's degree,standard,none,85,91,89,36
103,male,group B,high school,standard,completed,60,44,47,9
104,male,group C,some college,standard,completed,98,86,90,43
105,female,group C,some college,standard,none,58,67,72,86
106,female,group D,master's degree,standard,none,87,100,100,15
107,male,group E,associate's degree,standard,completed,66,63,64,92
108,female,group B,associate's degree,free/reduced,none,52,76,70,36
109,female,group B,some high school,standard,none,70,64,72,6
110,female,group D,associate's degree,free/reduced,completed,77,89,98,87
111,male,group C,high school,standard,none,62,55,49,55
112,male,group A,associate's degree,standard,none,54,53,47,34
113,female,group D,some college,standard,none,51,58,54,98
114,female,group E,bachelor's degree,standard,completed,99,100,100,37
115,male,group C,high school,standard,none,84,77,74,47
116,female,group B,bachelor's degree,free/reduced,none,75,85,82,28
117,female,group D,bachelor's degree,standard,none,78,82,79,42
118,female,group D,some high school,standard,none,51,63,61,34
119,female,group C,some college,standard,none,55,69,65,13
120,female,group C,bachelor's degree,standard,completed,79,92,89,79
121,male,group B,associate's degree,standard,completed,91,89,92,17
122,female,group C,some college,standard,completed,88,93,93,27
123,male,group D,high school,free/reduced,none,63,57,56,47
124,male,group E,some college,standard,none,83,80,73,73
125,female,group B,high school,standard,none,87,95,86,62
126,male,group B,some high school,standard,none,72,68,67,59
127,male,group D,some college,standard,completed,65,77,74,12
128,male,group D,master's degree,standard,none,82,82,74,38
129,female,group A,bachelor's degree,standard,none,51,49,51,75
130,male,group D,master's degree,standard,none,89,84,82,96
131,male,group C,some high school,free/reduced,completed,53,37,40,23
132,male,group E,some college,free/reduced,completed,87,74,70,63
133,female,group C,some college,standard,completed,75,81,84,93
134,male,group D,bachelor's degree,free/reduced,completed,74,79,75,91
135,male,group C,bachelor's degree,standard,none,58,55,48,66
136,male,group B,some high school,standard,completed,51,54,41,42
137,male,group E,high school,standard,none,70,55,56,29
138,female,group C,associate's degree,standard,none,59,66,67,83
139,male,group D,some college,standard,completed,71,61,69,25
140,female,group D,some high school,standard,none,76,72,71,31
141,female,group C,some college,free/reduced,none,59,62,64,15
142,female,group E,some college,free/reduced,completed,42,55,54,86
143,male,group A,high school,standard,none,57,43,47,79
144,male,group D,some college,standard,none,88,73,78,34
145,female,group C,some college,free/reduced,none,22,39,33,12
146,male,group B,some high school,standard,none,88,84,75,6
147,male,group C,associate's degree,free/reduced,none,73,68,66,24
148,female,group D,bachelor's degree,standard,completed,68,75,81,86
149,male,group E,associate's degree,free/reduced,completed,100,100,93,74
150,male,group A,some high school,standard,completed,62,67,69,58
151,male,group A,bachelor's degree,standard,none,77,67,68,18
152,female,group B,associate's degree,standard,completed,59,70,66,37
153,male,group D,bachelor's degree,standard,none,54,49,47,38
154,male,group D,some high school,standard,none,62,67,61,3
155,female,group C,some college,standard,completed,70,89,88,73
156,female,group E,high school,free/reduced,completed,66,74,78,40
157,male,group B,some college,free/reduced,none,60,60,60,69
158,female,group B,associate's degree,standard,completed,61,86,87,30
159,male,group D,associate's degree,free/reduced,none,66,62,64,61
160,male,group B,associate's degree,free/reduced,completed,82,78,74,25
161,female,group E,some college,free/reduced,completed,75,88,85,71
162,male,group B,master's degree,free/reduced,none,49,53,52,54
163,male,group C,high school,standard,none,52,53,49,33
164,female,group E,master's degree,standard,none,81,92,91,70
165,female,group C,bachelor's degree,standard,completed,96,100,100,58
166,male,group C,high school,free/reduced,completed,53,51,51,43
167,female,group B,master's degree,free/reduced,completed,58,76,78,6
168,female,group B,high school,standard,completed,68,83,78,78
169,female,group C,some college,free/reduced,completed,67,75,70,12
170,male,group A,high school,standard,completed,72,73,74,15
171,male,group E,some high school,standard,none,94,88,78,76
172,female,group D,some college,standard,none,79,86,81,9
173,female,group C,associate's degree,standard,none,63,67,70,31
174,female,group C,bachelor's degree,free/reduced,completed,43,51,54,74
175,female,group C,master's degree,standard,completed,81,91,87,58
176,female,group B,high school,free/reduced,completed,46,54,58,51
177,female,group C,associate's degree,standard,completed,71,77,77,75
178,female,group B,master's degree,free/reduced,completed,52,70,62,82
179,female,group D,some high school,standard,completed,97,100,100,15
180,male,group C,master's degree,free/reduced,completed,62,68,75,20
181,female,group C,some college,free/reduced,none,46,64,66,13
182,female,group E,high school,standard,none,50,50,47,13
183,female,group D,associate's degree,standard,none,65,69,70,43
184,male,group C,some high school,free/reduced,completed,45,52,49,26
185,male,group C,associate's degree,free/reduced,completed,65,67,65,57
186,male,group E,high school,standard,none,80,76,65,57
187,male,group D,some high school,standard,completed,62,66,68,92
188,male,group B,some high school,free/reduced,none,48,52,45,53
189,female,group C,bachelor's degree,standard,none,77,88,87,16
190,female,group E,associate's degree,standard,none,66,65,69,8
191,male,group D,some college,standard,completed,76,83,79,17
192,female,group B,some high school,standard,none,62,64,66,17
193,male,group D,some college,standard,completed,77,62,62,12
194,female,group C,master's degree,standard,completed,69,84,85,70
195,male,group D,associate's degree,standard,none,61,55,52,86
196,male,group C,some high school,free/reduced,completed,59,69,65,13
197,male,group E,high school,free/reduced,none,55,56,51,64
198,female,group B,some college,free/reduced,none,45,53,55,71
199,female,group B,bachelor's degree,free/reduced,none,78,79,76,99
200,female,group C,associate's degree,standard,completed,67,84,86,82
201,female,group D,some college,free/reduced,none,65,81,77,38
202,male,group C,associate's degree,standard,none,69,77,69,28
203,female,group B,associate's degree,standard,none,57,69,68,18
204,male,group C,some college,standard,none,59,41,42,69
205,male,group D,some high school,standard,completed,74,71,78,77
206,male,group E,bachelor's degree,standard,none,82,62,62,44
207,male,group E,high school,standard,completed,81,80,76,21
208,female,group B,some college,free/reduced,none,74,81,76,54
209,female,group B,some college,free/reduced,none,58,61,66,100
210,male,group D,some high school,free/reduced,completed,80,79,79,79
211,male,group C,some college,free/reduced,none,35,28,27,20
212,female,group C,high school,free/reduced,none,42,62,60,57
213,male,group C,associate's degree,free/reduced,completed,60,51,56,48
214,male,group E,high school,standard,completed,87,91,81,74
215,male,group B,some high school,standard,completed,84,83,75,94
216,female,group E,associate's degree,free/reduced,completed,83,86,88,26
217,female,group C,high school,free/reduced,none,34,42,39,97
218,male,group B,high school,free/reduced,none,66,77,70,69
219,male,group B,some high school,standard,completed,61,56,56,64
220,female,group D,high school,standard,completed,56,68,74,63
221,male,group B,associate's degree,standard,none,87,85,73,97
222,female,group C,some high school,free/reduced,none,55,65,62,41
223,male,group D,some high school,standard,none,86,80,75,81
224,female,group B,associate's degree,standard,completed,52,66,73,13
225,female,group E,master's degree,free/reduced,none,45,56,54,5
226,female,group C,some college,standard,none,72,72,71,83
227,male,group D,high school,standard,none,57,50,54,44
228,male,group A,some high school,free/reduced,none,68,72,64,70
229,female,group C,some college,standard,completed,88,95,94,38
230,male,group D,some college,standard,none,76,64,66,18
231,male,group C,associate's degree,standard,none,46,43,42,87
232,female,group B,bachelor's degree,standard,none,67,86,83,90
233,male,group E,some high school,standard,none,92,87,78,2
234,male,group C,bachelor's degree,standard,completed,83,82,84,22
235,male,group D,associate's degree,standard,none,80,75,77,65
236,male,group D,bachelor's degree,free/reduced,none,63,66,67,84
237,female,group D,some high school,standard,completed,64,60,74,100
238,male,group B,some college,standard,none,54,52,51,31
239,male,group C,associate's degree,standard,none,84,80,80,16
240,male,group D,high school,free/reduced,completed,73,68,66,92
241,female,group E,bachelor's degree,standard,none,80,83,83,41
242,female,group D,high school,standard,none,56,52,55,92
243,male,group E,some college,standard,none,59,51,43,61
244,male,group D,some high school,standard,none,75,74,69,86
245,male,group C,associate's degree,standard,none,85,76,71,8
246,male,group E,associate's degree,standard,none,89,76,74,95
247,female,group B,high school,standard,completed,58,70,68,43
248,female,group B,high school,standard,none,65,64,62,33
249,male,group C,high school,standard,none,68,60,53,96
250,male,group A,some high school,standard,completed,47,49,49,26
251,female,group D,some college,free/reduced,none,71,83,83,20
252,female,group B,some high school,standard,completed,60,70,70,23
253,male,group D,master's degree,standard,none,80,80,72,17
254,male,group D,high school,standard,none,54,52,52,97
255,female,group E,some college,standard,none,62,73,70,54
256,female,group C,associate's degree,free/reduced,none,64,73,68,81
257,male,group C,associate's degree,standard,completed,78,77,77,54
258,female,group B,some college,standard,none,70,75,78,15
259,female,group C,master's degree,free/reduced,completed,65,81,81,99
260,female,group C,some high school,free/reduced,completed,64,79,77,5
261,male,group C,some college,standard,completed,79,79,78,64
262,female,group C,some high school,free/reduced,none,44,50,51,0
263,female,group E,high school,standard,none,99,93,90,3
264,male,group D,high school,standard,none,76,73,68,88
265,male,group D,some high school,free/reduced,none,59,42,41,55
266,female,group C,bachelor's degree,standard,none,63,75,81,34
267,female,group D,high school,standard,none,69,72,77,25
268,female,group D,associate's degree,standard,completed,88,92,95,4
269,female,group E,some college,free/reduced,none,71,76,70,99
270,male,group C,bachelor's degree,standard,none,69,63,61,62
271,male,group C,some college,standard,none,58,49,42,98
272,female,group D,associate's degree,free/reduced,none,47,53,58,83
273,female,group D,some college,standard,none,65,70,71,34
274,male,group B,some college,standard,completed,88,85,76,58
275,male,group C,bachelor's degree,standard,none,83,78,73,78
276,female,group C,some high school,standard,completed,85,92,93,47
277,female,group E,high school,standard,completed,59,63,75,71
278,female,group C,some high school,free/reduced,none,65,86,80,68
279,male,group B,bachelor's degree,free/reduced,none,73,56,57,66
280,male,group D,high school,standard,none,53,52,42,33
281,male,group D,high school,standard,none,45,48,46,38
282,female,group D,bachelor's degree,free/reduced,none,73,79,84,12
283,female,group D,some college,free/reduced,completed,70,78,78,40
284,female,group B,some high school,standard,none,37,46,46,55
285,male,group B,associate's degree,standard,completed,81,82,82,52
286,male,group E,associate's degree,standard,completed,97,82,88,74
287,female,group B,some high school,standard,none,67,89,82,52
288,male,group B,bachelor's degree,free/reduced,none,88,75,76,52
289,male,group E,some high school,standard,completed,77,76,77,57
290,male,group C,associate's degree,standard,none,76,70,68,70
291,male,group D,some high school,standard,none,86,73,70,99
292,male,group C,some high school,standard,completed,63,60,57,62
293,female,group E,bachelor's degree,standard,none,65,73,75,69
294,male,group D,high school,free/reduced,completed,78,77,80,3
295,male,group B,associate's degree,free/reduced,none,67,62,60,66
296,male,group A,some high school,standard,completed,46,41,43,92
297,male,group E,associate's degree,standard,completed,71,74,68,16
298,male,group C,high school,free/reduced,completed,40,46,50,85
299,male,group D,associate's degree,free/reduced,none,90,87,75,77
300,male,group A,some college,free/reduced,completed,81,78,81,10
301,male,group D,some high school,free/reduced,none,56,54,52,50
302,female,group C,associate's degree,standard,completed,67,84,81,75
303,male,group B,associate's degree,standard,none,80,76,64,31
304,female,group C,associate's degree,standard,completed,74,75,83,40
305,male,group A,some college,standard,none,69,67,69,71
306,male,group E,some college,standard,completed,99,87,81,94
307,male,group C,some high school,standard,none,51,52,44,36
308,female,group B,associate's degree,free/reduced,none,53,71,67,23
309,female,group D,high school,free/reduced,none,49,57,52,16
310,female,group B,associate's degree,standard,none,73,76,80,35
311,male,group B,bachelor's degree,standard,none,66,60,57,39
312,male,group D,bachelor's degree,standard,completed,67,61,68,39
313,female,group C,associate's degree,free/reduced,completed,68,67,69,100
314,female,group C,bachelor's degree,standard,completed,59,64,75,96
315,male,group C,high school,standard,none,71,66,65,21
316,female,group D,master's degree,standard,completed,77,82,91,35

In [52]:
# create random float array
print(np.random.uniform(0, 100, 20)
      )

[80.49063197 62.38350059 23.20685594 48.26037931 89.80618754 72.33201881
 24.21905614 49.54307985 28.63164238  9.46997338 54.92948183 48.73984494
  5.96653708 11.90075011 15.19139216  4.21476725 69.48815399 70.03807527
 50.29759639 67.15152181]

# Adding a new column

## assign()

In [53]:
# create random numbers
score1 = np.random.randint(0,101, size=(len(df_exams)))
score2 = np.random.randint(0, 101, size=(len(df_exams)))

In [54]:
# create series 
series1 = pd.Series(score1)
series2 = pd.Series(score2)

In [55]:
series2

0      100
1       11
2       27
3        6
4       19
5        6
6       74
7       21
8       51
9       50
10      13
11      42
12      78
13      24
14      94
15      64
16      13
17      94
18      44
19      27
20       1
21      65
22      80
23      23
24      46
25       1
26      42
27      54
28      82
29       1
30      88
31      49
32      99
33       2
34      27
35      40
36      14
37      20
38     100
39      34
40      70
41      99
42      43
43      34
44      35
45      67
46      85
47      38
48      22
49      34
50      74
51      56
52      94
53      33
54      76
55      23
56      93
57      96
58      39
59       6
60      53
61      86
62      20
63       4
64      38
65       2
66      68
67      65
68      24
69      98
70      60
71      50
72      39
73      56
74      12
75      38
76      86
77       3
78       2
79      42
80      98
81      34
82      16
83      92
84      16
85      87
86      46
87      87
88      79
89      47
90      63
91     100
92      97
93      58
94      66
95      87
96      67
97      10
98      35
99      74
100     71
101     49
102      9
103     80
104     79
105     12
106     25
107     87
108     13
109     52
110     76
111     32
112     82
113     88
114     54
115     85
116     45
117     69
118     24
119     75
120     49
121     18
122     55
123     40
124      0
125     62
126     60
127     30
128     48
129     80
130     51
131     70
132     70
133     32
134     40
135     63
136     20
137      6
138     42
139     61
140     78
141      4
142     91
143     64
144     25
145     58
146     74
147     11
148      2
149     62
150     84
151     73
152    100
153     40
154     96
155      6
156     54
157     43
158      5
159     90
160     42
161     93
162     16
163     60
164     51
165     81
166     94
167     24
168     28
169     21
170     92
171     61
172     36
173     30
174     23
175      8
176     33
177     12
178     92
179     43
180     10
181     40
182     54
183     98
184     25
185      7
186     23
187     18
188     42
189     81
190     73
191     64
192     46
193     60
194     59
195     90
196     15
197     20
198     33
199     65
200      7
201     43
202     81
203      6
204     89
205     56
206     29
207     53
208     13
209     71
210     92
211     65
212     63
213     71
214     77
215      3
216     99
217     59
218     69
219     41
220     30
221     66
222      1
223     55
224     22
225     47
226     46
227    100
228     45
229     16
230     90
231     80
232     45
233     31
234      6
235     73
236     47
237     20
238      2
239     40
240     95
241     47
242    100
243     11
244     24
245     45
246      4
247     20
248     60
249     65
250     56
251     69
252      9
253     34
254     47
255     23
256     12
257     32
258     59
259      7
260     97
261     26
262     53
263     64
264     54
265      5
266     81
267      3
268     31
269     67
270     96
271     23
272     34
273     15
274     34
275      1
276     35
277     37
278     39
279     66
280     58
281     40
282     57
283     64
284     11
285     62
286     17
287     58
288     26
289     42
290      3
291     75
292     30
293     39
294     37
295     27
296     93
297     53
298     43
299     76
300     59
301     67
302      4
303     55
304     94
305     79
306     86
307     45
308     21
309     74
310     31
311     68
312     11
313     77
314     57
315     22
316     93
317     47
318     35
319      6
320     70
321     55
322      2
323     47
324     53
325     87
326     51
327     59
328     21
329     65
330      6
331     59
332     98
333     27
334     52
335     77
336     65
337      5
338     32
339     22
340     12
341      4
342     32
343     91
344     58
345     69
346     85
347     72
348     51
349      3
350     76
351     89
352     83
353     42
354     79
355     47
356     27
357     57
358      6
359     25
360     70
361     85
362     77
363     67
364      4
365     25
366      0
367     22
368     68
369     43
370     38
371     87
372     94
373     58
374     87
375     42
376     30
377     21
378     70
379     72
380     85
381      2
382     39
383     36
384     96
385     66
386     76
387     99
388     99
389     29
390     91
391     74
392     98
393     85
394     79
395     81
396     69
397     90
398     47
399     59
400     46
401     46
402     14
403     24
404     68
405     15
406    100
407     88
408     43
409     60
410     12
411     26
412     15
413     27
414     69
415     26
416     51
417     88
418      0
419     67
420     38
421     14
422     52
423     25
424     92
425    100
426     53
427      1
428     90
429     57
430     27
431      8
432     10
433     69
434     64
435     97
436     14
437     27
438     50
439     41
440     21
441     43
442    100
443     37
444     28
445     68
446     70
447      8
448     60
449     72
450     27
451     35
452     96
453     30
454     39
455     61
456     64
457     72
458     39
459     96
460     80
461     24
462     32
463     13
464     56
465    100
466     78
467     85
468     92
469     72
470     49
471     89
472     48
473     11
474     31
475     89
476     67
477     56
478     33
479     30
480     97
481     89
482     71
483     26
484     70
485     24
486     28
487      7
488     23
489     43
490     27
491     73
492      4
493     86
494     30
495      0
496     22
497     64
498      6
499     68
500     19
501     13
502     21
503     80
504     71
505      2
506     30
507     23
508     45
509     88
510     75
511     53
512     41
513     34
514      4
515     26
516     38
517     64
518     79
519     90
520     14
521     37
522     85
523      2
524     60
525     64
526     11
527      4
528     22
529     62
530     95
531      3
532     81
533     48
534     65
535     46
536     91
537     52
538     53
539     17
540      0
541     86
542     98
543     86
544     86
545     46
546      3
547     27
548     64
549     29
550     30
551     74
552     74
553     55
554     64
555      1
556      1
557     18
558      3
559      0
560     92
561     84
562     83
563     33
564     52
565     57
566     44
567     10
568     20
569     54
570     63
571     39
572     68
573      3
574      1
575     32
576     29
577     36
578     77
579     83
580     62
581      5
582     43
583     98
584     88
585     95
586     25
587     97
588     35
589     44
590     49
591     11
592     12
593     34
594     31
595      1
596     15
597     75
598     92
599     49
600     70
601     37
602     24
603     84
604     77
605     71
606     98
607     50
608     49
609     98
610     31
611      4
612     75
613     93
614     63
615     35
616     83
617      6
618     38
619      0
620     50
621     92
622     63
623     41
624     65
625     42
626      2
627     23
628     53
629     64
630     49
631     72
632     22
633     86
634     35
635     84
636     79
637     64
638     71
639     73
640      5
641     96
642     24
643     63
644     79
645     90
646     70
647     34
648     50
649     94
650     64
651      6
652      9
653     76
654     40
655     33
656     62
657     45
658     50
659     48
660     45
661     91
662     44
663     18
664     61
665     46
666     54
667     20
668      0
669     49
670     99
671     40
672     97
673     79
674     90
675     60
676      0
677     93
678     40
679     95
680     97
681     31
682     46
683     66
684     67
685     92
686      7
687     36
688     90
689     28
690     80
691     52
692      0
693     79
694     98
695     86
696    100
697      6
698     67
699     78
700     16
701     78
702     25
703     84
704     37
705     25
706     99
707     12
708     27
709     89
710     43
711     71
712     72
713     50
714     38
715     61
716     93
717     60
718     18
719     48
720     57
721     87
722     60
723     14
724      7
725     15
726     96
727    100
728     25
729     53
730     83
731      8
732     91
733     55
734     75
735     87
736     79
737     84
738      1
739     94
740     65
741      2
742     16
743     79
744     76
745     83
746     48
747     89
748     53
749     81
750     42
751     79
752     61
753     71
754     31
755      9
756     28
757     24
758      9
759     25
760     38
761      1
762      7
763     68
764     60
765     75
766     70
767     55
768     30
769     23
770     33
771     14
772     97
773     16
774     75
775     31
776     97
777     20
778     82
779      5
780     56
781     19
782     97
783     93
784     33
785     42
786     18
787     70
788     81
789     76
790     85
791     93
792     37
793     85
794     84
795      8
796     43
797     95
798     70
799     67
800     48
801     55
802     84
803     53
804     20
805     58
806     36
807     68
808     57
809     93
810    100
811     84
812     29
813     72
814     88
815     44
816     14
817      9
818      9
819     50
820     24
821     95
822     22
823     62
824     43
825     30
826     69
827     29
828     58
829     11
830      6
831      2
832      6
833     67
834     24
835     57
836     76
837     10
838     62
839     84
840     36
841     21
842     36
843      6
844     69
845      3
846     83
847     45
848     65
849     21
850     35
851      6
852     96
853     20
854     52
855     50
856     96
857     51
858     22
859     12
860     56
861     16
862     73
863      8
864     50
865     83
866     52
867     55
868      7
869     48
870     80
871     36
872     16
873      2
874     66
875     71
876     41
877     30
878     97
879     83
880     78
881     84
882     70
883      4
884     61
885     85
886     65
887     59
888     36
889      8
890     52
891     89
892     68
893     37
894     27
895     84
896     63
897     67
898     14
899     16
900     99
901     85
902     33
903     80
904     21
905     90
906     12
907     33
908      4
909      7
910     94
911      1
912     84
913     32
914     92
915     69
916     41
917     76
918     50
919     21
920     84
921     80
922     59
923      4
924     35
925     40
926     13
927     18
928     48
929      2
930     11
931     97
932      8
933     60
934     89
935     73
936     86
937     49
938     11
939     61
940     69
941     42
942     23
943     23
944     59
945     20
946     57
947     17
948     82
949      1
950      8
951     44
952     76
953     75
954     19
955     99
956     35
957     10
958     36
959     77
960     68
961     95
962     52
963     32
964     23
965     91
966     46
967     39
968     27
969     94
970     50
971     48
972     50
973      1
974     59
975     59
976     40
977      1
978     37
979     26
980     95
981     92
982     18
983     89
984     71
985      5
986      2
987     39
988     80
989     55
990     48
991     71
992     51
993     23
994     94
995     21
996     42
997      4
998     75
999     66
dtype: int32

In [56]:
df_exams.assign(score1=series1, score2=series2)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Language Score,score1,score2
0,female,group B,bachelor's degree,standard,none,72,72,74,34,63,100
1,female,group C,some college,standard,completed,69,90,88,71,80,11
2,female,group B,master's degree,standard,none,90,95,93,75,20,27
3,male,group A,associate's degree,free/reduced,none,47,57,44,86,32,6
4,male,group C,some college,standard,none,76,78,75,44,52,19
5,female,group B,associate's degree,standard,none,71,83,78,30,15,6
6,female,group B,some college,standard,completed,88,95,92,15,67,74
7,male,group B,some college,free/reduced,none,40,43,39,70,73,21
8,male,group D,high school,free/reduced,completed,64,64,67,56,8,51
9,female,group B,high school,free/reduced,none,38,60,50,81,100,50
10,male,group C,associate's degree,standard,none,58,54,52,76,81,13
11,male,group D,associate's degree,standard,none,40,52,43,43,17,42
12,female,group B,high school,standard,none,65,81,73,36,26,78
13,male,group A,some college,standard,completed,78,72,70,11,20,24
14,female,group A,master's degree,standard,none,50,53,58,43,0,94
15,female,group C,some high school,standard,none,69,75,78,67,14,64
16,male,group C,high school,standard,none,88,89,86,40,1,13
17,female,group B,some high school,free/reduced,none,18,32,28,90,64,94
18,male,group C,master's degree,free/reduced,completed,46,42,46,33,86,44
19,female,group C,associate's degree,free/reduced,none,54,58,61,98,13,27
20,male,group D,high school,standard,none,66,69,63,93,71,1
21,female,group B,some college,free/reduced,completed,65,75,70,58,67,65
22,male,group D,some college,standard,none,44,54,53,18,10,80
23,female,group C,some high school,standard,none,69,73,73,83,63,23
24,male,group D,bachelor's degree,free/reduced,completed,74,71,80,51,94,46
25,male,group A,master's degree,free/reduced,none,73,74,72,19,22,1
26,male,group B,some college,standard,none,69,54,55,1,29,42
27,female,group C,bachelor's degree,standard,none,67,69,75,11,56,54
28,male,group C,high school,standard,none,70,70,65,79,18,82
29,female,group D,master's degree,standard,none,62,70,75,2,39,1
30,female,group D,some college,standard,none,69,74,74,21,89,88
31,female,group B,some college,standard,none,63,65,61,94,51,49
32,female,group E,master's degree,free/reduced,none,56,72,65,9,83,99
33,male,group D,some college,standard,none,40,42,38,9,91,2
34,male,group E,some college,standard,none,97,87,82,49,6,27
35,male,group E,associate's degree,standard,completed,81,81,79,15,20,40
36,female,group D,associate's degree,standard,none,74,81,83,57,77,14
37,female,group D,some high school,free/reduced,none,50,64,59,33,3,20
38,female,group D,associate's degree,free/reduced,completed,75,90,88,6,12,100
39,male,group B,associate's degree,free/reduced,none,57,56,57,57,4,34
40,male,group C,associate's degree,free/reduced,none,55,61,54,34,68,70
41,female,group C,associate's degree,standard,none,58,73,68,12,46,99
42,female,group B,associate's degree,standard,none,53,58,65,41,64,43
43,male,group B,some college,free/reduced,completed,59,65,66,38,0,34
44,female,group E,associate's degree,free/reduced,none,50,56,54,98,81,35
45,male,group B,associate's degree,standard,none,65,54,57,10,0,67
46,female,group A,associate's degree,standard,completed,55,65,62,47,41,85
47,female,group C,high school,standard,none,66,71,76,87,22,38
48,female,group D,associate's degree,free/reduced,completed,57,74,76,55,63,22
49,male,group C,high school,standard,completed,82,84,82,37,100,34
50,male,group E,some college,standard,none,53,55,48,56,42,74
51,male,group E,associate's degree,free/reduced,completed,77,69,68,15,56,56
52,male,group C,some college,standard,none,53,44,42,34,94,94
53,male,group D,high school,standard,none,88,78,75,1,49,33
54,female,group C,some high school,free/reduced,completed,71,84,87,24,72,76
55,female,group C,high school,free/reduced,none,33,41,43,72,94,23
56,female,group E,associate's degree,standard,completed,82,85,86,24,52,93
57,male,group D,associate's degree,standard,none,52,55,49,43,99,96
58,male,group D,some college,standard,completed,58,59,58,18,88,39
59,female,group C,some high school,free/reduced,none,0,17,10,81,49,6
60,male,group E,bachelor's degree,free/reduced,completed,79,74,72,67,31,53
61,male,group A,some high school,free/reduced,none,39,39,34,99,61,86
62,male,group A,associate's degree,free/reduced,none,62,61,55,3,6,20
63,female,group C,associate's degree,standard,none,69,80,71,52,43,4
64,female,group D,some high school,standard,none,59,58,59,68,9,38
65,male,group B,some high school,standard,none,67,64,61,33,11,2
66,male,group D,some high school,free/reduced,none,45,37,37,62,76,68
67,female,group C,some college,standard,none,60,72,74,92,18,65
68,male,group B,associate's degree,free/reduced,none,61,58,56,99,66,24
69,female,group C,associate's degree,standard,none,39,64,57,91,99,98
70,female,group D,some college,free/reduced,completed,58,63,73,73,33,60
71,male,group D,some college,standard,completed,63,55,63,67,63,50
72,female,group A,associate's degree,free/reduced,none,41,51,48,10,32,39
73,male,group C,some high school,free/reduced,none,61,57,56,39,34,56
74,male,group C,some high school,standard,none,49,49,41,30,52,12
75,male,group B,associate's degree,free/reduced,none,44,41,38,16,16,38
76,male,group E,some high school,standard,none,30,26,22,75,58,86
77,male,group A,bachelor's degree,standard,completed,80,78,81,52,40,3
78,female,group D,some high school,standard,completed,61,74,72,53,78,2
79,female,group E,master's degree,standard,none,62,68,68,100,58,42
80,female,group B,associate's degree,standard,none,47,49,50,4,96,98
81,male,group B,high school,free/reduced,none,49,45,45,97,80,34
82,male,group A,some college,free/reduced,completed,50,47,54,73,97,16
83,male,group E,associate's degree,standard,none,72,64,63,30,47,92
84,male,group D,high school,free/reduced,none,42,39,34,54,98,16
85,female,group C,some college,standard,none,73,80,82,50,24,87
86,female,group C,some college,free/reduced,none,76,83,88,67,38,46
87,female,group D,associate's degree,standard,none,71,71,74,80,58,87
88,female,group A,some college,standard,none,58,70,67,65,62,79
89,female,group D,some high school,standard,none,73,86,82,47,3,47
90,female,group C,bachelor's degree,standard,none,65,72,74,4,80,63
91,male,group C,high school,free/reduced,none,27,34,36,23,41,100
92,male,group C,high school,standard,none,71,79,71,69,72,97
93,male,group C,associate's degree,free/reduced,completed,43,45,50,86,8,58
94,female,group B,some college,standard,none,79,86,92,48,5,66
95,male,group C,associate's degree,free/reduced,completed,78,81,82,72,34,87
96,male,group B,some high school,standard,completed,65,66,62,45,94,67
97,female,group E,some college,standard,completed,63,72,70,59,11,10
98,female,group D,some college,free/reduced,none,58,67,62,94,93,35
99,female,group D,bachelor's degree,standard,none,65,67,62,34,54,74
100,male,group B,some college,standard,none,79,67,67,96,88,71
101,male,group D,bachelor's degree,standard,completed,68,74,74,84,47,49
102,female,group D,associate's degree,standard,none,85,91,89,36,22,9
103,male,group B,high school,standard,completed,60,44,47,9,23,80
104,male,group C,some college,standard,completed,98,86,90,43,2,79
105,female,group C,some college,standard,none,58,67,72,86,30,12
106,female,group D,master's degree,standard,none,87,100,100,15,75,25
107,male,group E,associate's degree,standard,completed,66,63,64,92,4,87
108,female,group B,associate's degree,free/reduced,none,52,76,70,36,76,13
109,female,group B,some high school,standard,none,70,64,72,6,87,52
110,female,group D,associate's degree,free/reduced,completed,77,89,98,87,67,76
111,male,group C,high school,standard,none,62,55,49,55,50,32
112,male,group A,associate's degree,standard,none,54,53,47,34,45,82
113,female,group D,some college,standard,none,51,58,54,98,80,88
114,female,group E,bachelor's degree,standard,completed,99,100,100,37,2,54
115,male,group C,high school,standard,none,84,77,74,47,82,85
116,female,group B,bachelor's degree,free/reduced,none,75,85,82,28,5,45
117,female,group D,bachelor's degree,standard,none,78,82,79,42,26,69
118,female,group D,some high school,standard,none,51,63,61,34,70,24
119,female,group C,some college,standard,none,55,69,65,13,29,75
120,female,group C,bachelor's degree,standard,completed,79,92,89,79,19,49
121,male,group B,associate's degree,standard,completed,91,89,92,17,45,18
122,female,group C,some college,standard,completed,88,93,93,27,6,55
123,male,group D,high school,free/reduced,none,63,57,56,47,26,40
124,male,group E,some college,standard,none,83,80,73,73,11,0
125,female,group B,high school,standard,none,87,95,86,62,7,62
126,male,group B,some high school,standard,none,72,68,67,59,22,60
127,male,group D,some college,standard,completed,65,77,74,12,8,30
128,male,group D,master's degree,standard,none,82,82,74,38,63,48
129,female,group A,bachelor's degree,standard,none,51,49,51,75,14,80
130,male,group D,master's degree,standard,none,89,84,82,96,15,51
131,male,group C,some high school,free/reduced,completed,53,37,40,23,84,70
132,male,group E,some college,free/reduced,completed,87,74,70,63,39,70
133,female,group C,some college,standard,completed,75,81,84,93,44,32
134,male,group D,bachelor's degree,free/reduced,completed,74,79,75,91,59,40
135,male,group C,bachelor's degree,standard,none,58,55,48,66,13,63
136,male,group B,some high school,standard,completed,51,54,41,42,85,20
137,male,group E,high school,standard,none,70,55,56,29,83,6
138,female,group C,associate's degree,standard,none,59,66,67,83,0,42
139,male,group D,some college,standard,completed,71,61,69,25,62,61
140,female,group D,some high school,standard,none,76,72,71,31,47,78
141,female,group C,some college,free/reduced,none,59,62,64,15,21,4
142,female,group E,some college,free/reduced,completed,42,55,54,86,37,91
143,male,group A,high school,standard,none,57,43,47,79,67,64
144,male,group D,some college,standard,none,88,73,78,34,74,25
145,female,group C,some college,free/reduced,none,22,39,33,12,94,58
146,male,group B,some high school,standard,none,88,84,75,6,3,74
147,male,group C,associate's degree,free/reduced,none,73,68,66,24,99,11
148,female,group D,bachelor's degree,standard,completed,68,75,81,86,61,2
149,male,group E,associate's degree,free/reduced,completed,100,100,93,74,83,62
150,male,group A,some high school,standard,completed,62,67,69,58,56,84
151,male,group A,bachelor's degree,standard,none,77,67,68,18,55,73
152,female,group B,associate's degree,standard,completed,59,70,66,37,38,100
153,male,group D,bachelor's degree,standard,none,54,49,47,38,87,40
154,male,group D,some high school,standard,none,62,67,61,3,17,96
155,female,group C,some college,standard,completed,70,89,88,73,22,6
156,female,group E,high school,free/reduced,completed,66,74,78,40,16,54
157,male,group B,some college,free/reduced,none,60,60,60,69,95,43
158,female,group B,associate's degree,standard,completed,61,86,87,30,76,5
159,male,group D,associate's degree,free/reduced,none,66,62,64,61,60,90
160,male,group B,associate's degree,free/reduced,completed,82,78,74,25,60,42
161,female,group E,some college,free/reduced,completed,75,88,85,71,69,93
162,male,group B,master's degree,free/reduced,none,49,53,52,54,55,16
163,male,group C,high school,standard,none,52,53,49,33,57,60
164,female,group E,master's degree,standard,none,81,92,91,70,8,51
165,female,group C,bachelor's degree,standard,completed,96,100,100,58,80,81
166,male,group C,high school,free/reduced,completed,53,51,51,43,23,94
167,female,group B,master's degree,free/reduced,completed,58,76,78,6,93,24
168,female,group B,high school,standard,completed,68,83,78,78,15,28
169,female,group C,some college,free/reduced,completed,67,75,70,12,35,21
170,male,group A,high school,standard,completed,72,73,74,15,31,92
171,male,group E,some high school,standard,none,94,88,78,76,18,61
172,female,group D,some college,standard,none,79,86,81,9,54,36
173,female,group C,associate's degree,standard,none,63,67,70,31,25,30
174,female,group C,bachelor's degree,free/reduced,completed,43,51,54,74,88,23
175,female,group C,master's degree,standard,completed,81,91,87,58,74,8
176,female,group B,high school,free/reduced,completed,46,54,58,51,89,33
177,female,group C,associate's degree,standard,completed,71,77,77,75,32,12
178,female,group B,master's degree,free/reduced,completed,52,70,62,82,18,92
179,female,group D,some high school,standard,completed,97,100,100,15,45,43
180,male,group C,master's degree,free/reduced,completed,62,68,75,20,18,10
181,female,group C,some college,free/reduced,none,46,64,66,13,9,40
182,female,group E,high school,standard,none,50,50,47,13,61,54
183,female,group D,associate's degree,standard,none,65,69,70,43,90,98
184,male,group C,some high school,free/reduced,completed,45,52,49,26,42,25
185,male,group C,associate's degree,free/reduced,completed,65,67,65,57,17,7
186,male,group E,high school,standard,none,80,76,65,57,23,23
187,male,group D,some high school,standard,completed,62,66,68,92,38,18
188,male,group B,some high school,free/reduced,none,48,52,45,53,95,42
189,female,group C,bachelor's degree,standard,none,77,88,87,16,65,81
190,female,group E,associate's degree,standard,none,66,65,69,8,95,73
191,male,group D,some college,standard,completed,76,83,79,17,51,64
192,female,group B,some high school,standard,none,62,64,66,17,82,46
193,male,group D,some college,standard,completed,77,62,62,12,1,60
194,female,group C,master's degree,standard,completed,69,84,85,70,42,59
195,male,group D,associate's degree,standard,none,61,55,52,86,26,90
196,male,group C,some high school,free/reduced,completed,59,69,65,13,7,15
197,male,group E,high school,free/reduced,none,55,56,51,64,28,20
198,female,group B,some college,free/reduced,none,45,53,55,71,64,33
199,female,group B,bachelor's degree,free/reduced,none,78,79,76,99,74,65
200,female,group C,associate's degree,standard,completed,67,84,86,82,85,7
201,female,group D,some college,free/reduced,none,65,81,77,38,87,43
202,male,group C,associate's degree,standard,none,69,77,69,28,45,81
203,female,group B,associate's degree,standard,none,57,69,68,18,40,6
204,male,group C,some college,standard,none,59,41,42,69,25,89
205,male,group D,some high school,standard,completed,74,71,78,77,49,56
206,male,group E,bachelor's degree,standard,none,82,62,62,44,21,29
207,male,group E,high school,standard,completed,81,80,76,21,29,53
208,female,group B,some college,free/reduced,none,74,81,76,54,9,13
209,female,group B,some college,free/reduced,none,58,61,66,100,43,71
210,male,group D,some high school,free/reduced,completed,80,79,79,79,55,92
211,male,group C,some college,free/reduced,none,35,28,27,20,22,65
212,female,group C,high school,free/reduced,none,42,62,60,57,33,63
213,male,group C,associate's degree,free/reduced,completed,60,51,56,48,30,71
214,male,group E,high school,standard,completed,87,91,81,74,93,77
215,male,group B,some high school,standard,completed,84,83,75,94,50,3
216,female,group E,associate's degree,free/reduced,completed,83,86,88,26,7,99
217,female,group C,high school,free/reduced,none,34,42,39,97,76,59
218,male,group B,high school,free/reduced,none,66,77,70,69,69,69
219,male,group B,some high school,standard,completed,61,56,56,64,50,41
220,female,group D,high school,standard,completed,56,68,74,63,27,30
221,male,group B,associate's degree,standard,none,87,85,73,97,55,66
222,female,group C,some high school,free/reduced,none,55,65,62,41,81,1
223,male,group D,some high school,standard,none,86,80,75,81,69,55
224,female,group B,associate's degree,standard,completed,52,66,73,13,25,22
225,female,group E,master's degree,free/reduced,none,45,56,54,5,70,47
226,female,group C,some college,standard,none,72,72,71,83,20,46
227,male,group D,high school,standard,none,57,50,54,44,26,100
228,male,group A,some high school,free/reduced,none,68,72,64,70,75,45
229,female,group C,some college,standard,completed,88,95,94,38,69,16
230,male,group D,some college,standard,none,76,64,66,18,95,90
231,male,group C,associate's degree,standard,none,46,43,42,87,19,80
232,female,group B,bachelor's degree,standard,none,67,86,83,90,81,45
233,male,group E,some high school,standard,none,92,87,78,2,96,31
234,male,group C,bachelor's degree,standard,completed,83,82,84,22,57,6
235,male,group D,associate's degree,standard,none,80,75,77,65,24,73
236,male,group D,bachelor's degree,free/reduced,none,63,66,67,84,0,47
237,female,group D,some high school,standard,completed,64,60,74,100,38,20
238,male,group B,some college,standard,none,54,52,51,31,33,2
239,male,group C,associate's degree,standard,none,84,80,80,16,9,40
240,male,group D,high school,free/reduced,completed,73,68,66,92,40,95
241,female,group E,bachelor's degree,standard,none,80,83,83,41,67,47
242,female,group D,high school,standard,none,56,52,55,92,100,100
243,male,group E,some college,standard,none,59,51,43,61,100,11
244,male,group D,some high school,standard,none,75,74,69,86,87,24
245,male,group C,associate's degree,standard,none,85,76,71,8,19,45
246,male,group E,associate's degree,standard,none,89,76,74,95,91,4
247,female,group B,high school,standard,completed,58,70,68,43,74,20
248,female,group B,high school,standard,none,65,64,62,33,28,60
249,male,group C,high school,standard,none,68,60,53,96,0,65
250,male,group A,some high school,standard,completed,47,49,49,26,49,56
251,female,group D,some college,free/reduced,none,71,83,83,20,38,69
252,female,group B,some high school,standard,completed,60,70,70,23,86,9
253,male,group D,master's degree,standard,none,80,80,72,17,97,34
254,male,group D,high school,standard,none,54,52,52,97,66,47
255,female,group E,some college,standard,none,62,73,70,54,48,23
256,female,group C,associate's degree,free/reduced,none,64,73,68,81,44,12
257,male,group C,associate's degree,standard,completed,78,77,77,54,29,32
258,female,group B,some college,standard,none,70,75,78,15,79,59
259,female,group C,master's degree,free/reduced,completed,65,81,81,99,9,7
260,female,group C,some high school,free/reduced,completed,64,79,77,5,37,97
261,male,group C,some college,standard,completed,79,79,78,64,45,26
262,female,group C,some high school,free/reduced,none,44,50,51,0,28,53
263,female,group E,high school,standard,none,99,93,90,3,58,64
264,male,group D,high school,standard,none,76,73,68,88,37,54
265,male,group D,some high school,free/reduced,none,59,42,41,55,87,5
266,female,group C,bachelor's degree,standard,none,63,75,81,34,48,81
267,female,group D,high school,standard,none,69,72,77,25,4,3
268,female,group D,associate's degree,standard,completed,88,92,95,4,55,31
269,female,group E,some college,free/reduced,none,71,76,70,99,12,67
270,male,group C,bachelor's degree,standard,none,69,63,61,62,48,96
271,male,group C,some college,standard,none,58,49,42,98,100,23
272,female,group D,associate's degree,free/reduced,none,47,53,58,83,28,34
273,female,group D,some college,standard,none,65,70,71,34,36,15
274,male,group B,some college,standard,completed,88,85,76,58,3,34
275,male,group C,bachelor's degree,standard,none,83,78,73,78,16,1
276,female,group C,some high school,standard,completed,85,92,93,47,93,35
277,female,group E,high school,standard,completed,59,63,75,71,27,37
278,female,group C,some high school,free/reduced,none,65,86,80,68,22,39
279,male,group B,bachelor's degree,free/reduced,none,73,56,57,66,57,66
280,male,group D,high school,standard,none,53,52,42,33,64,58
281,male,group D,high school,standard,none,45,48,46,38,26,40
282,female,group D,bachelor's degree,free/reduced,none,73,79,84,12,70,57
283,female,group D,some college,free/reduced,completed,70,78,78,40,32,64
284,female,group B,some high school,standard,none,37,46,46,55,41,11
285,male,group B,associate's degree,standard,completed,81,82,82,52,76,62
286,male,group E,associate's degree,standard,completed,97,82,88,74,86,17
287,female,group B,some high school,standard,none,67,89,82,52,53,58
288,male,group B,bachelor's degree,free/reduced,none,88,75,76,52,62,26
289,male,group E,some high school,standard,completed,77,76,77,57,47,42

In [57]:
df_exams = df_exams.assign(score1=series1, score2=series2)
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Language Score,score1,score2
0,female,group B,bachelor's degree,standard,none,72,72,74,34,63,100
1,female,group C,some college,standard,completed,69,90,88,71,80,11
2,female,group B,master's degree,standard,none,90,95,93,75,20,27
3,male,group A,associate's degree,free/reduced,none,47,57,44,86,32,6
4,male,group C,some college,standard,none,76,78,75,44,52,19
5,female,group B,associate's degree,standard,none,71,83,78,30,15,6
6,female,group B,some college,standard,completed,88,95,92,15,67,74
7,male,group B,some college,free/reduced,none,40,43,39,70,73,21
8,male,group D,high school,free/reduced,completed,64,64,67,56,8,51
9,female,group B,high school,free/reduced,none,38,60,50,81,100,50
10,male,group C,associate's degree,standard,none,58,54,52,76,81,13
11,male,group D,associate's degree,standard,none,40,52,43,43,17,42
12,female,group B,high school,standard,none,65,81,73,36,26,78
13,male,group A,some college,standard,completed,78,72,70,11,20,24
14,female,group A,master's degree,standard,none,50,53,58,43,0,94
15,female,group C,some high school,standard,none,69,75,78,67,14,64
16,male,group C,high school,standard,none,88,89,86,40,1,13
17,female,group B,some high school,free/reduced,none,18,32,28,90,64,94
18,male,group C,master's degree,free/reduced,completed,46,42,46,33,86,44
19,female,group C,associate's degree,free/reduced,none,54,58,61,98,13,27
20,male,group D,high school,standard,none,66,69,63,93,71,1
21,female,group B,some college,free/reduced,completed,65,75,70,58,67,65
22,male,group D,some college,standard,none,44,54,53,18,10,80
23,female,group C,some high school,standard,none,69,73,73,83,63,23
24,male,group D,bachelor's degree,free/reduced,completed,74,71,80,51,94,46
25,male,group A,master's degree,free/reduced,none,73,74,72,19,22,1
26,male,group B,some college,standard,none,69,54,55,1,29,42
27,female,group C,bachelor's degree,standard,none,67,69,75,11,56,54
28,male,group C,high school,standard,none,70,70,65,79,18,82
29,female,group D,master's degree,standard,none,62,70,75,2,39,1
30,female,group D,some college,standard,none,69,74,74,21,89,88
31,female,group B,some college,standard,none,63,65,61,94,51,49
32,female,group E,master's degree,free/reduced,none,56,72,65,9,83,99
33,male,group D,some college,standard,none,40,42,38,9,91,2
34,male,group E,some college,standard,none,97,87,82,49,6,27
35,male,group E,associate's degree,standard,completed,81,81,79,15,20,40
36,female,group D,associate's degree,standard,none,74,81,83,57,77,14
37,female,group D,some high school,free/reduced,none,50,64,59,33,3,20
38,female,group D,associate's degree,free/reduced,completed,75,90,88,6,12,100
39,male,group B,associate's degree,free/reduced,none,57,56,57,57,4,34
40,male,group C,associate's degree,free/reduced,none,55,61,54,34,68,70
41,female,group C,associate's degree,standard,none,58,73,68,12,46,99
42,female,group B,associate's degree,standard,none,53,58,65,41,64,43
43,male,group B,some college,free/reduced,completed,59,65,66,38,0,34
44,female,group E,associate's degree,free/reduced,none,50,56,54,98,81,35
45,male,group B,associate's degree,standard,none,65,54,57,10,0,67
46,female,group A,associate's degree,standard,completed,55,65,62,47,41,85
47,female,group C,high school,standard,none,66,71,76,87,22,38
48,female,group D,associate's degree,free/reduced,completed,57,74,76,55,63,22
49,male,group C,high school,standard,completed,82,84,82,37,100,34
50,male,group E,some college,standard,none,53,55,48,56,42,74
51,male,group E,associate's degree,free/reduced,completed,77,69,68,15,56,56
52,male,group C,some college,standard,none,53,44,42,34,94,94
53,male,group D,high school,standard,none,88,78,75,1,49,33
54,female,group C,some high school,free/reduced,completed,71,84,87,24,72,76
55,female,group C,high school,free/reduced,none,33,41,43,72,94,23
56,female,group E,associate's degree,standard,completed,82,85,86,24,52,93
57,male,group D,associate's degree,standard,none,52,55,49,43,99,96
58,male,group D,some college,standard,completed,58,59,58,18,88,39
59,female,group C,some high school,free/reduced,none,0,17,10,81,49,6
60,male,group E,bachelor's degree,free/reduced,completed,79,74,72,67,31,53
61,male,group A,some high school,free/reduced,none,39,39,34,99,61,86
62,male,group A,associate's degree,free/reduced,none,62,61,55,3,6,20
63,female,group C,associate's degree,standard,none,69,80,71,52,43,4
64,female,group D,some high school,standard,none,59,58,59,68,9,38
65,male,group B,some high school,standard,none,67,64,61,33,11,2
66,male,group D,some high school,free/reduced,none,45,37,37,62,76,68
67,female,group C,some college,standard,none,60,72,74,92,18,65
68,male,group B,associate's degree,free/reduced,none,61,58,56,99,66,24
69,female,group C,associate's degree,standard,none,39,64,57,91,99,98
70,female,group D,some college,free/reduced,completed,58,63,73,73,33,60
71,male,group D,some college,standard,completed,63,55,63,67,63,50
72,female,group A,associate's degree,free/reduced,none,41,51,48,10,32,39
73,male,group C,some high school,free/reduced,none,61,57,56,39,34,56
74,male,group C,some high school,standard,none,49,49,41,30,52,12
75,male,group B,associate's degree,free/reduced,none,44,41,38,16,16,38
76,male,group E,some high school,standard,none,30,26,22,75,58,86
77,male,group A,bachelor's degree,standard,completed,80,78,81,52,40,3
78,female,group D,some high school,standard,completed,61,74,72,53,78,2
79,female,group E,master's degree,standard,none,62,68,68,100,58,42
80,female,group B,associate's degree,standard,none,47,49,50,4,96,98
81,male,group B,high school,free/reduced,none,49,45,45,97,80,34
82,male,group A,some college,free/reduced,completed,50,47,54,73,97,16
83,male,group E,associate's degree,standard,none,72,64,63,30,47,92
84,male,group D,high school,free/reduced,none,42,39,34,54,98,16
85,female,group C,some college,standard,none,73,80,82,50,24,87
86,female,group C,some college,free/reduced,none,76,83,88,67,38,46
87,female,group D,associate's degree,standard,none,71,71,74,80,58,87
88,female,group A,some college,standard,none,58,70,67,65,62,79
89,female,group D,some high school,standard,none,73,86,82,47,3,47
90,female,group C,bachelor's degree,standard,none,65,72,74,4,80,63
91,male,group C,high school,free/reduced,none,27,34,36,23,41,100
92,male,group C,high school,standard,none,71,79,71,69,72,97
93,male,group C,associate's degree,free/reduced,completed,43,45,50,86,8,58
94,female,group B,some college,standard,none,79,86,92,48,5,66
95,male,group C,associate's degree,free/reduced,completed,78,81,82,72,34,87
96,male,group B,some high school,standard,completed,65,66,62,45,94,67
97,female,group E,some college,standard,completed,63,72,70,59,11,10
98,female,group D,some college,free/reduced,none,58,67,62,94,93,35
99,female,group D,bachelor's degree,standard,none,65,67,62,34,54,74
100,male,group B,some college,standard,none,79,67,67,96,88,71
101,male,group D,bachelor's degree,standard,completed,68,74,74,84,47,49
102,female,group D,associate's degree,standard,none,85,91,89,36,22,9
103,male,group B,high school,standard,completed,60,44,47,9,23,80
104,male,group C,some college,standard,completed,98,86,90,43,2,79
105,female,group C,some college,standard,none,58,67,72,86,30,12
106,female,group D,master's degree,standard,none,87,100,100,15,75,25
107,male,group E,associate's degree,standard,completed,66,63,64,92,4,87
108,female,group B,associate's degree,free/reduced,none,52,76,70,36,76,13
109,female,group B,some high school,standard,none,70,64,72,6,87,52
110,female,group D,associate's degree,free/reduced,completed,77,89,98,87,67,76
111,male,group C,high school,standard,none,62,55,49,55,50,32
112,male,group A,associate's degree,standard,none,54,53,47,34,45,82
113,female,group D,some college,standard,none,51,58,54,98,80,88
114,female,group E,bachelor's degree,standard,completed,99,100,100,37,2,54
115,male,group C,high school,standard,none,84,77,74,47,82,85
116,female,group B,bachelor's degree,free/reduced,none,75,85,82,28,5,45
117,female,group D,bachelor's degree,standard,none,78,82,79,42,26,69
118,female,group D,some high school,standard,none,51,63,61,34,70,24
119,female,group C,some college,standard,none,55,69,65,13,29,75
120,female,group C,bachelor's degree,standard,completed,79,92,89,79,19,49
121,male,group B,associate's degree,standard,completed,91,89,92,17,45,18
122,female,group C,some college,standard,completed,88,93,93,27,6,55
123,male,group D,high school,free/reduced,none,63,57,56,47,26,40
124,male,group E,some college,standard,none,83,80,73,73,11,0
125,female,group B,high school,standard,none,87,95,86,62,7,62
126,male,group B,some high school,standard,none,72,68,67,59,22,60
127,male,group D,some college,standard,completed,65,77,74,12,8,30
128,male,group D,master's degree,standard,none,82,82,74,38,63,48
129,female,group A,bachelor's degree,standard,none,51,49,51,75,14,80
130,male,group D,master's degree,standard,none,89,84,82,96,15,51
131,male,group C,some high school,free/reduced,completed,53,37,40,23,84,70
132,male,group E,some college,free/reduced,completed,87,74,70,63,39,70
133,female,group C,some college,standard,completed,75,81,84,93,44,32
134,male,group D,bachelor's degree,free/reduced,completed,74,79,75,91,59,40
135,male,group C,bachelor's degree,standard,none,58,55,48,66,13,63
136,male,group B,some high school,standard,completed,51,54,41,42,85,20
137,male,group E,high school,standard,none,70,55,56,29,83,6
138,female,group C,associate's degree,standard,none,59,66,67,83,0,42
139,male,group D,some college,standard,completed,71,61,69,25,62,61
140,female,group D,some high school,standard,none,76,72,71,31,47,78
141,female,group C,some college,free/reduced,none,59,62,64,15,21,4
142,female,group E,some college,free/reduced,completed,42,55,54,86,37,91
143,male,group A,high school,standard,none,57,43,47,79,67,64
144,male,group D,some college,standard,none,88,73,78,34,74,25
145,female,group C,some college,free/reduced,none,22,39,33,12,94,58
146,male,group B,some high school,standard,none,88,84,75,6,3,74
147,male,group C,associate's degree,free/reduced,none,73,68,66,24,99,11
148,female,group D,bachelor's degree,standard,completed,68,75,81,86,61,2
149,male,group E,associate's degree,free/reduced,completed,100,100,93,74,83,62
150,male,group A,some high school,standard,completed,62,67,69,58,56,84
151,male,group A,bachelor's degree,standard,none,77,67,68,18,55,73
152,female,group B,associate's degree,standard,completed,59,70,66,37,38,100
153,male,group D,bachelor's degree,standard,none,54,49,47,38,87,40
154,male,group D,some high school,standard,none,62,67,61,3,17,96
155,female,group C,some college,standard,completed,70,89,88,73,22,6
156,female,group E,high school,free/reduced,completed,66,74,78,40,16,54
157,male,group B,some college,free/reduced,none,60,60,60,69,95,43
158,female,group B,associate's degree,standard,completed,61,86,87,30,76,5
159,male,group D,associate's degree,free/reduced,none,66,62,64,61,60,90
160,male,group B,associate's degree,free/reduced,completed,82,78,74,25,60,42
161,female,group E,some college,free/reduced,completed,75,88,85,71,69,93
162,male,group B,master's degree,free/reduced,none,49,53,52,54,55,16
163,male,group C,high school,standard,none,52,53,49,33,57,60
164,female,group E,master's degree,standard,none,81,92,91,70,8,51
165,female,group C,bachelor's degree,standard,completed,96,100,100,58,80,81
166,male,group C,high school,free/reduced,completed,53,51,51,43,23,94
167,female,group B,master's degree,free/reduced,completed,58,76,78,6,93,24
168,female,group B,high school,standard,completed,68,83,78,78,15,28
169,female,group C,some college,free/reduced,completed,67,75,70,12,35,21
170,male,group A,high school,standard,completed,72,73,74,15,31,92
171,male,group E,some high school,standard,none,94,88,78,76,18,61
172,female,group D,some college,standard,none,79,86,81,9,54,36
173,female,group C,associate's degree,standard,none,63,67,70,31,25,30
174,female,group C,bachelor's degree,free/reduced,completed,43,51,54,74,88,23
175,female,group C,master's degree,standard,completed,81,91,87,58,74,8
176,female,group B,high school,free/reduced,completed,46,54,58,51,89,33
177,female,group C,associate's degree,standard,completed,71,77,77,75,32,12
178,female,group B,master's degree,free/reduced,completed,52,70,62,82,18,92
179,female,group D,some high school,standard,completed,97,100,100,15,45,43
180,male,group C,master's degree,free/reduced,completed,62,68,75,20,18,10
181,female,group C,some college,free/reduced,none,46,64,66,13,9,40
182,female,group E,high school,standard,none,50,50,47,13,61,54
183,female,group D,associate's degree,standard,none,65,69,70,43,90,98
184,male,group C,some high school,free/reduced,completed,45,52,49,26,42,25
185,male,group C,associate's degree,free/reduced,completed,65,67,65,57,17,7
186,male,group E,high school,standard,none,80,76,65,57,23,23
187,male,group D,some high school,standard,completed,62,66,68,92,38,18
188,male,group B,some high school,free/reduced,none,48,52,45,53,95,42
189,female,group C,bachelor's degree,standard,none,77,88,87,16,65,81
190,female,group E,associate's degree,standard,none,66,65,69,8,95,73
191,male,group D,some college,standard,completed,76,83,79,17,51,64
192,female,group B,some high school,standard,none,62,64,66,17,82,46
193,male,group D,some college,standard,completed,77,62,62,12,1,60
194,female,group C,master's degree,standard,completed,69,84,85,70,42,59
195,male,group D,associate's degree,standard,none,61,55,52,86,26,90
196,male,group C,some high school,free/reduced,completed,59,69,65,13,7,15
197,male,group E,high school,free/reduced,none,55,56,51,64,28,20
198,female,group B,some college,free/reduced,none,45,53,55,71,64,33
199,female,group B,bachelor's degree,free/reduced,none,78,79,76,99,74,65
200,female,group C,associate's degree,standard,completed,67,84,86,82,85,7
201,female,group D,some college,free/reduced,none,65,81,77,38,87,43
202,male,group C,associate's degree,standard,none,69,77,69,28,45,81
203,female,group B,associate's degree,standard,none,57,69,68,18,40,6
204,male,group C,some college,standard,none,59,41,42,69,25,89
205,male,group D,some high school,standard,completed,74,71,78,77,49,56
206,male,group E,bachelor's degree,standard,none,82,62,62,44,21,29
207,male,group E,high school,standard,completed,81,80,76,21,29,53
208,female,group B,some college,free/reduced,none,74,81,76,54,9,13
209,female,group B,some college,free/reduced,none,58,61,66,100,43,71
210,male,group D,some high school,free/reduced,completed,80,79,79,79,55,92
211,male,group C,some college,free/reduced,none,35,28,27,20,22,65
212,female,group C,high school,free/reduced,none,42,62,60,57,33,63
213,male,group C,associate's degree,free/reduced,completed,60,51,56,48,30,71
214,male,group E,high school,standard,completed,87,91,81,74,93,77
215,male,group B,some high school,standard,completed,84,83,75,94,50,3
216,female,group E,associate's degree,free/reduced,completed,83,86,88,26,7,99
217,female,group C,high school,free/reduced,none,34,42,39,97,76,59
218,male,group B,high school,free/reduced,none,66,77,70,69,69,69
219,male,group B,some high school,standard,completed,61,56,56,64,50,41
220,female,group D,high school,standard,completed,56,68,74,63,27,30
221,male,group B,associate's degree,standard,none,87,85,73,97,55,66
222,female,group C,some high school,free/reduced,none,55,65,62,41,81,1
223,male,group D,some high school,standard,none,86,80,75,81,69,55
224,female,group B,associate's degree,standard,completed,52,66,73,13,25,22
225,female,group E,master's degree,free/reduced,none,45,56,54,5,70,47
226,female,group C,some college,standard,none,72,72,71,83,20,46
227,male,group D,high school,standard,none,57,50,54,44,26,100
228,male,group A,some high school,free/reduced,none,68,72,64,70,75,45
229,female,group C,some college,standard,completed,88,95,94,38,69,16
230,male,group D,some college,standard,none,76,64,66,18,95,90
231,male,group C,associate's degree,standard,none,46,43,42,87,19,80
232,female,group B,bachelor's degree,standard,none,67,86,83,90,81,45
233,male,group E,some high school,standard,none,92,87,78,2,96,31
234,male,group C,bachelor's degree,standard,completed,83,82,84,22,57,6
235,male,group D,associate's degree,standard,none,80,75,77,65,24,73
236,male,group D,bachelor's degree,free/reduced,none,63,66,67,84,0,47
237,female,group D,some high school,standard,completed,64,60,74,100,38,20
238,male,group B,some college,standard,none,54,52,51,31,33,2
239,male,group C,associate's degree,standard,none,84,80,80,16,9,40
240,male,group D,high school,free/reduced,completed,73,68,66,92,40,95
241,female,group E,bachelor's degree,standard,none,80,83,83,41,67,47
242,female,group D,high school,standard,none,56,52,55,92,100,100
243,male,group E,some college,standard,none,59,51,43,61,100,11
244,male,group D,some high school,standard,none,75,74,69,86,87,24
245,male,group C,associate's degree,standard,none,85,76,71,8,19,45
246,male,group E,associate's degree,standard,none,89,76,74,95,91,4
247,female,group B,high school,standard,completed,58,70,68,43,74,20
248,female,group B,high school,standard,none,65,64,62,33,28,60
249,male,group C,high school,standard,none,68,60,53,96,0,65
250,male,group A,some high school,standard,completed,47,49,49,26,49,56
251,female,group D,some college,free/reduced,none,71,83,83,20,38,69
252,female,group B,some high school,standard,completed,60,70,70,23,86,9
253,male,group D,master's degree,standard,none,80,80,72,17,97,34
254,male,group D,high school,standard,none,54,52,52,97,66,47
255,female,group E,some college,standard,none,62,73,70,54,48,23
256,female,group C,associate's degree,free/reduced,none,64,73,68,81,44,12
257,male,group C,associate's degree,standard,completed,78,77,77,54,29,32
258,female,group B,some college,standard,none,70,75,78,15,79,59
259,female,group C,master's degree,free/reduced,completed,65,81,81,99,9,7
260,female,group C,some high school,free/reduced,completed,64,79,77,5,37,97
261,male,group C,some college,standard,completed,79,79,78,64,45,26
262,female,group C,some high school,free/reduced,none,44,50,51,0,28,53
263,female,group E,high school,standard,none,99,93,90,3,58,64
264,male,group D,high school,standard,none,76,73,68,88,37,54
265,male,group D,some high school,free/reduced,none,59,42,41,55,87,5
266,female,group C,bachelor's degree,standard,none,63,75,81,34,48,81
267,female,group D,high school,standard,none,69,72,77,25,4,3
268,female,group D,associate's degree,standard,completed,88,92,95,4,55,31
269,female,group E,some college,free/reduced,none,71,76,70,99,12,67
270,male,group C,bachelor's degree,standard,none,69,63,61,62,48,96
271,male,group C,some college,standard,none,58,49,42,98,100,23
272,female,group D,associate's degree,free/reduced,none,47,53,58,83,28,34
273,female,group D,some college,standard,none,65,70,71,34,36,15
274,male,group B,some college,standard,completed,88,85,76,58,3,34
275,male,group C,bachelor's degree,standard,none,83,78,73,78,16,1
276,female,group C,some high school,standard,completed,85,92,93,47,93,35
277,female,group E,high school,standard,completed,59,63,75,71,27,37
278,female,group C,some high school,free/reduced,none,65,86,80,68,22,39
279,male,group B,bachelor's degree,free/reduced,none,73,56,57,66,57,66
280,male,group D,high school,standard,none,53,52,42,33,64,58
281,male,group D,high school,standard,none,45,48,46,38,26,40
282,female,group D,bachelor's degree,free/reduced,none,73,79,84,12,70,57
283,female,group D,some college,free/reduced,completed,70,78,78,40,32,64
284,female,group B,some high school,standard,none,37,46,46,55,41,11
285,male,group B,associate's degree,standard,completed,81,82,82,52,76,62
286,male,group E,associate's degree,standard,completed,97,82,88,74,86,17
287,female,group B,some high school,standard,none,67,89,82,52,53,58
288,male,group B,bachelor's degree,free/reduced,none,88,75,76,52,62,26
289,male,group E,some high school,standard,completed,77,76,77,57,47,42

## insert()

In [ ]:
# using insert() to add column
df_exams.insert(2, "test", series1)

In [59]:
df_exams

,gender,race/ethnicity,test,parental level of education,lunch,test preparation course,math score,reading score,writing score,Language Score,score1,score2
0,female,group B,63,bachelor's degree,standard,none,72,72,74,34,63,100
1,female,group C,80,some college,standard,completed,69,90,88,71,80,11
2,female,group B,20,master's degree,standard,none,90,95,93,75,20,27
3,male,group A,32,associate's degree,free/reduced,none,47,57,44,86,32,6
4,male,group C,52,some college,standard,none,76,78,75,44,52,19
5,female,group B,15,associate's degree,standard,none,71,83,78,30,15,6
6,female,group B,67,some college,standard,completed,88,95,92,15,67,74
7,male,group B,73,some college,free/reduced,none,40,43,39,70,73,21
8,male,group D,8,high school,free/reduced,completed,64,64,67,56,8,51
9,female,group B,100,high school,free/reduced,none,38,60,50,81,100,50
10,male,group C,81,associate's degree,standard,none,58,54,52,76,81,13
11,male,group D,17,associate's degree,standard,none,40,52,43,43,17,42
12,female,group B,26,high school,standard,none,65,81,73,36,26,78
13,male,group A,20,some college,standard,completed,78,72,70,11,20,24
14,female,group A,0,master's degree,standard,none,50,53,58,43,0,94
15,female,group C,14,some high school,standard,none,69,75,78,67,14,64
16,male,group C,1,high school,standard,none,88,89,86,40,1,13
17,female,group B,64,some high school,free/reduced,none,18,32,28,90,64,94
18,male,group C,86,master's degree,free/reduced,completed,46,42,46,33,86,44
19,female,group C,13,associate's degree,free/reduced,none,54,58,61,98,13,27
20,male,group D,71,high school,standard,none,66,69,63,93,71,1
21,female,group B,67,some college,free/reduced,completed,65,75,70,58,67,65
22,male,group D,10,some college,standard,none,44,54,53,18,10,80
23,female,group C,63,some high school,standard,none,69,73,73,83,63,23
24,male,group D,94,bachelor's degree,free/reduced,completed,74,71,80,51,94,46
25,male,group A,22,master's degree,free/reduced,none,73,74,72,19,22,1
26,male,group B,29,some college,standard,none,69,54,55,1,29,42
27,female,group C,56,bachelor's degree,standard,none,67,69,75,11,56,54
28,male,group C,18,high school,standard,none,70,70,65,79,18,82
29,female,group D,39,master's degree,standard,none,62,70,75,2,39,1
30,female,group D,89,some college,standard,none,69,74,74,21,89,88
31,female,group B,51,some college,standard,none,63,65,61,94,51,49
32,female,group E,83,master's degree,free/reduced,none,56,72,65,9,83,99
33,male,group D,91,some college,standard,none,40,42,38,9,91,2
34,male,group E,6,some college,standard,none,97,87,82,49,6,27
35,male,group E,20,associate's degree,standard,completed,81,81,79,15,20,40
36,female,group D,77,associate's degree,standard,none,74,81,83,57,77,14
37,female,group D,3,some high school,free/reduced,none,50,64,59,33,3,20
38,female,group D,12,associate's degree,free/reduced,completed,75,90,88,6,12,100
39,male,group B,4,associate's degree,free/reduced,none,57,56,57,57,4,34
40,male,group C,68,associate's degree,free/reduced,none,55,61,54,34,68,70
41,female,group C,46,associate's degree,standard,none,58,73,68,12,46,99
42,female,group B,64,associate's degree,standard,none,53,58,65,41,64,43
43,male,group B,0,some college,free/reduced,completed,59,65,66,38,0,34
44,female,group E,81,associate's degree,free/reduced,none,50,56,54,98,81,35
45,male,group B,0,associate's degree,standard,none,65,54,57,10,0,67
46,female,group A,41,associate's degree,standard,completed,55,65,62,47,41,85
47,female,group C,22,high school,standard,none,66,71,76,87,22,38
48,female,group D,63,associate's degree,free/reduced,completed,57,74,76,55,63,22
49,male,group C,100,high school,standard,completed,82,84,82,37,100,34
50,male,group E,42,some college,standard,none,53,55,48,56,42,74
51,male,group E,56,associate's degree,free/reduced,completed,77,69,68,15,56,56
52,male,group C,94,some college,standard,none,53,44,42,34,94,94
53,male,group D,49,high school,standard,none,88,78,75,1,49,33
54,female,group C,72,some high school,free/reduced,completed,71,84,87,24,72,76
55,female,group C,94,high school,free/reduced,none,33,41,43,72,94,23
56,female,group E,52,associate's degree,standard,completed,82,85,86,24,52,93
57,male,group D,99,associate's degree,standard,none,52,55,49,43,99,96
58,male,group D,88,some college,standard,completed,58,59,58,18,88,39
59,female,group C,49,some high school,free/reduced,none,0,17,10,81,49,6
60,male,group E,31,bachelor's degree,free/reduced,completed,79,74,72,67,31,53
61,male,group A,61,some high school,free/reduced,none,39,39,34,99,61,86
62,male,group A,6,associate's degree,free/reduced,none,62,61,55,3,6,20
63,female,group C,43,associate's degree,standard,none,69,80,71,52,43,4
64,female,group D,9,some high school,standard,none,59,58,59,68,9,38
65,male,group B,11,some high school,standard,none,67,64,61,33,11,2
66,male,group D,76,some high school,free/reduced,none,45,37,37,62,76,68
67,female,group C,18,some college,standard,none,60,72,74,92,18,65
68,male,group B,66,associate's degree,free/reduced,none,61,58,56,99,66,24
69,female,group C,99,associate's degree,standard,none,39,64,57,91,99,98
70,female,group D,33,some college,free/reduced,completed,58,63,73,73,33,60
71,male,group D,63,some college,standard,completed,63,55,63,67,63,50
72,female,group A,32,associate's degree,free/reduced,none,41,51,48,10,32,39
73,male,group C,34,some high school,free/reduced,none,61,57,56,39,34,56
74,male,group C,52,some high school,standard,none,49,49,41,30,52,12
75,male,group B,16,associate's degree,free/reduced,none,44,41,38,16,16,38
76,male,group E,58,some high school,standard,none,30,26,22,75,58,86
77,male,group A,40,bachelor's degree,standard,completed,80,78,81,52,40,3
78,female,group D,78,some high school,standard,completed,61,74,72,53,78,2
79,female,group E,58,master's degree,standard,none,62,68,68,100,58,42
80,female,group B,96,associate's degree,standard,none,47,49,50,4,96,98
81,male,group B,80,high school,free/reduced,none,49,45,45,97,80,34
82,male,group A,97,some college,free/reduced,completed,50,47,54,73,97,16
83,male,group E,47,associate's degree,standard,none,72,64,63,30,47,92
84,male,group D,98,high school,free/reduced,none,42,39,34,54,98,16
85,female,group C,24,some college,standard,none,73,80,82,50,24,87
86,female,group C,38,some college,free/reduced,none,76,83,88,67,38,46
87,female,group D,58,associate's degree,standard,none,71,71,74,80,58,87
88,female,group A,62,some college,standard,none,58,70,67,65,62,79
89,female,group D,3,some high school,standard,none,73,86,82,47,3,47
90,female,group C,80,bachelor's degree,standard,none,65,72,74,4,80,63
91,male,group C,41,high school,free/reduced,none,27,34,36,23,41,100
92,male,group C,72,high school,standard,none,71,79,71,69,72,97
93,male,group C,8,associate's degree,free/reduced,completed,43,45,50,86,8,58
94,female,group B,5,some college,standard,none,79,86,92,48,5,66
95,male,group C,34,associate's degree,free/reduced,completed,78,81,82,72,34,87
96,male,group B,94,some high school,standard,completed,65,66,62,45,94,67
97,female,group E,11,some college,standard,completed,63,72,70,59,11,10
98,female,group D,93,some college,free/reduced,none,58,67,62,94,93,35
99,female,group D,54,bachelor's degree,standard,none,65,67,62,34,54,74
100,male,group B,88,some college,standard,none,79,67,67,96,88,71
101,male,group D,47,bachelor's degree,standard,completed,68,74,74,84,47,49
102,female,group D,22,associate's degree,standard,none,85,91,89,36,22,9
103,male,group B,23,high school,standard,completed,60,44,47,9,23,80
104,male,group C,2,some college,standard,completed,98,86,90,43,2,79
105,female,group C,30,some college,standard,none,58,67,72,86,30,12
106,female,group D,75,master's degree,standard,none,87,100,100,15,75,25
107,male,group E,4,associate's degree,standard,completed,66,63,64,92,4,87
108,female,group B,76,associate's degree,free/reduced,none,52,76,70,36,76,13
109,female,group B,87,some high school,standard,none,70,64,72,6,87,52
110,female,group D,67,associate's degree,free/reduced,completed,77,89,98,87,67,76
111,male,group C,50,high school,standard,none,62,55,49,55,50,32
112,male,group A,45,associate's degree,standard,none,54,53,47,34,45,82
113,female,group D,80,some college,standard,none,51,58,54,98,80,88
114,female,group E,2,bachelor's degree,standard,completed,99,100,100,37,2,54
115,male,group C,82,high school,standard,none,84,77,74,47,82,85
116,female,group B,5,bachelor's degree,free/reduced,none,75,85,82,28,5,45
117,female,group D,26,bachelor's degree,standard,none,78,82,79,42,26,69
118,female,group D,70,some high school,standard,none,51,63,61,34,70,24
119,female,group C,29,some college,standard,none,55,69,65,13,29,75
120,female,group C,19,bachelor's degree,standard,completed,79,92,89,79,19,49
121,male,group B,45,associate's degree,standard,completed,91,89,92,17,45,18
122,female,group C,6,some college,standard,completed,88,93,93,27,6,55
123,male,group D,26,high school,free/reduced,none,63,57,56,47,26,40
124,male,group E,11,some college,standard,none,83,80,73,73,11,0
125,female,group B,7,high school,standard,none,87,95,86,62,7,62
126,male,group B,22,some high school,standard,none,72,68,67,59,22,60
127,male,group D,8,some college,standard,completed,65,77,74,12,8,30
128,male,group D,63,master's degree,standard,none,82,82,74,38,63,48
129,female,group A,14,bachelor's degree,standard,none,51,49,51,75,14,80
130,male,group D,15,master's degree,standard,none,89,84,82,96,15,51
131,male,group C,84,some high school,free/reduced,completed,53,37,40,23,84,70
132,male,group E,39,some college,free/reduced,completed,87,74,70,63,39,70
133,female,group C,44,some college,standard,completed,75,81,84,93,44,32
134,male,group D,59,bachelor's degree,free/reduced,completed,74,79,75,91,59,40
135,male,group C,13,bachelor's degree,standard,none,58,55,48,66,13,63
136,male,group B,85,some high school,standard,completed,51,54,41,42,85,20
137,male,group E,83,high school,standard,none,70,55,56,29,83,6
138,female,group C,0,associate's degree,standard,none,59,66,67,83,0,42
139,male,group D,62,some college,standard,completed,71,61,69,25,62,61
140,female,group D,47,some high school,standard,none,76,72,71,31,47,78
141,female,group C,21,some college,free/reduced,none,59,62,64,15,21,4
142,female,group E,37,some college,free/reduced,completed,42,55,54,86,37,91
143,male,group A,67,high school,standard,none,57,43,47,79,67,64
144,male,group D,74,some college,standard,none,88,73,78,34,74,25
145,female,group C,94,some college,free/reduced,none,22,39,33,12,94,58
146,male,group B,3,some high school,standard,none,88,84,75,6,3,74
147,male,group C,99,associate's degree,free/reduced,none,73,68,66,24,99,11
148,female,group D,61,bachelor's degree,standard,completed,68,75,81,86,61,2
149,male,group E,83,associate's degree,free/reduced,completed,100,100,93,74,83,62
150,male,group A,56,some high school,standard,completed,62,67,69,58,56,84
151,male,group A,55,bachelor's degree,standard,none,77,67,68,18,55,73
152,female,group B,38,associate's degree,standard,completed,59,70,66,37,38,100
153,male,group D,87,bachelor's degree,standard,none,54,49,47,38,87,40
154,male,group D,17,some high school,standard,none,62,67,61,3,17,96
155,female,group C,22,some college,standard,completed,70,89,88,73,22,6
156,female,group E,16,high school,free/reduced,completed,66,74,78,40,16,54
157,male,group B,95,some college,free/reduced,none,60,60,60,69,95,43
158,female,group B,76,associate's degree,standard,completed,61,86,87,30,76,5
159,male,group D,60,associate's degree,free/reduced,none,66,62,64,61,60,90
160,male,group B,60,associate's degree,free/reduced,completed,82,78,74,25,60,42
161,female,group E,69,some college,free/reduced,completed,75,88,85,71,69,93
162,male,group B,55,master's degree,free/reduced,none,49,53,52,54,55,16
163,male,group C,57,high school,standard,none,52,53,49,33,57,60
164,female,group E,8,master's degree,standard,none,81,92,91,70,8,51
165,female,group C,80,bachelor's degree,standard,completed,96,100,100,58,80,81
166,male,group C,23,high school,free/reduced,completed,53,51,51,43,23,94
167,female,group B,93,master's degree,free/reduced,completed,58,76,78,6,93,24
168,female,group B,15,high school,standard,completed,68,83,78,78,15,28
169,female,group C,35,some college,free/reduced,completed,67,75,70,12,35,21
170,male,group A,31,high school,standard,completed,72,73,74,15,31,92
171,male,group E,18,some high school,standard,none,94,88,78,76,18,61
172,female,group D,54,some college,standard,none,79,86,81,9,54,36
173,female,group C,25,associate's degree,standard,none,63,67,70,31,25,30
174,female,group C,88,bachelor's degree,free/reduced,completed,43,51,54,74,88,23
175,female,group C,74,master's degree,standard,completed,81,91,87,58,74,8
176,female,group B,89,high school,free/reduced,completed,46,54,58,51,89,33
177,female,group C,32,associate's degree,standard,completed,71,77,77,75,32,12
178,female,group B,18,master's degree,free/reduced,completed,52,70,62,82,18,92
179,female,group D,45,some high school,standard,completed,97,100,100,15,45,43
180,male,group C,18,master's degree,free/reduced,completed,62,68,75,20,18,10
181,female,group C,9,some college,free/reduced,none,46,64,66,13,9,40
182,female,group E,61,high school,standard,none,50,50,47,13,61,54
183,female,group D,90,associate's degree,standard,none,65,69,70,43,90,98
184,male,group C,42,some high school,free/reduced,completed,45,52,49,26,42,25
185,male,group C,17,associate's degree,free/reduced,completed,65,67,65,57,17,7
186,male,group E,23,high school,standard,none,80,76,65,57,23,23
187,male,group D,38,some high school,standard,completed,62,66,68,92,38,18
188,male,group B,95,some high school,free/reduced,none,48,52,45,53,95,42
189,female,group C,65,bachelor's degree,standard,none,77,88,87,16,65,81
190,female,group E,95,associate's degree,standard,none,66,65,69,8,95,73
191,male,group D,51,some college,standard,completed,76,83,79,17,51,64
192,female,group B,82,some high school,standard,none,62,64,66,17,82,46
193,male,group D,1,some college,standard,completed,77,62,62,12,1,60
194,female,group C,42,master's degree,standard,completed,69,84,85,70,42,59
195,male,group D,26,associate's degree,standard,none,61,55,52,86,26,90
196,male,group C,7,some high school,free/reduced,completed,59,69,65,13,7,15
197,male,group E,28,high school,free/reduced,none,55,56,51,64,28,20
198,female,group B,64,some college,free/reduced,none,45,53,55,71,64,33
199,female,group B,74,bachelor's degree,free/reduced,none,78,79,76,99,74,65
200,female,group C,85,associate's degree,standard,completed,67,84,86,82,85,7
201,female,group D,87,some college,free/reduced,none,65,81,77,38,87,43
202,male,group C,45,associate's degree,standard,none,69,77,69,28,45,81
203,female,group B,40,associate's degree,standard,none,57,69,68,18,40,6
204,male,group C,25,some college,standard,none,59,41,42,69,25,89
205,male,group D,49,some high school,standard,completed,74,71,78,77,49,56
206,male,group E,21,bachelor's degree,standard,none,82,62,62,44,21,29
207,male,group E,29,high school,standard,completed,81,80,76,21,29,53
208,female,group B,9,some college,free/reduced,none,74,81,76,54,9,13
209,female,group B,43,some college,free/reduced,none,58,61,66,100,43,71
210,male,group D,55,some high school,free/reduced,completed,80,79,79,79,55,92
211,male,group C,22,some college,free/reduced,none,35,28,27,20,22,65
212,female,group C,33,high school,free/reduced,none,42,62,60,57,33,63
213,male,group C,30,associate's degree,free/reduced,completed,60,51,56,48,30,71
214,male,group E,93,high school,standard,completed,87,91,81,74,93,77
215,male,group B,50,some high school,standard,completed,84,83,75,94,50,3
216,female,group E,7,associate's degree,free/reduced,completed,83,86,88,26,7,99
217,female,group C,76,high school,free/reduced,none,34,42,39,97,76,59
218,male,group B,69,high school,free/reduced,none,66,77,70,69,69,69
219,male,group B,50,some high school,standard,completed,61,56,56,64,50,41
220,female,group D,27,high school,standard,completed,56,68,74,63,27,30
221,male,group B,55,associate's degree,standard,none,87,85,73,97,55,66
222,female,group C,81,some high school,free/reduced,none,55,65,62,41,81,1
223,male,group D,69,some high school,standard,none,86,80,75,81,69,55
224,female,group B,25,associate's degree,standard,completed,52,66,73,13,25,22
225,female,group E,70,master's degree,free/reduced,none,45,56,54,5,70,47
226,female,group C,20,some college,standard,none,72,72,71,83,20,46
227,male,group D,26,high school,standard,none,57,50,54,44,26,100
228,male,group A,75,some high school,free/reduced,none,68,72,64,70,75,45
229,female,group C,69,some college,standard,completed,88,95,94,38,69,16
230,male,group D,95,some college,standard,none,76,64,66,18,95,90
231,male,group C,19,associate's degree,standard,none,46,43,42,87,19,80
232,female,group B,81,bachelor's degree,standard,none,67,86,83,90,81,45
233,male,group E,96,some high school,standard,none,92,87,78,2,96,31
234,male,group C,57,bachelor's degree,standard,completed,83,82,84,22,57,6
235,male,group D,24,associate's degree,standard,none,80,75,77,65,24,73
236,male,group D,0,bachelor's degree,free/reduced,none,63,66,67,84,0,47
237,female,group D,38,some high school,standard,completed,64,60,74,100,38,20
238,male,group B,33,some college,standard,none,54,52,51,31,33,2
239,male,group C,9,associate's degree,standard,none,84,80,80,16,9,40
240,male,group D,40,high school,free/reduced,completed,73,68,66,92,40,95
241,female,group E,67,bachelor's degree,standard,none,80,83,83,41,67,47
242,female,group D,100,high school,standard,none,56,52,55,92,100,100
243,male,group E,100,some college,standard,none,59,51,43,61,100,11
244,male,group D,87,some high school,standard,none,75,74,69,86,87,24
245,male,group C,19,associate's degree,standard,none,85,76,71,8,19,45
246,male,group E,91,associate's degree,standard,none,89,76,74,95,91,4
247,female,group B,74,high school,standard,completed,58,70,68,43,74,20
248,female,group B,28,high school,standard,none,65,64,62,33,28,60
249,male,group C,0,high school,standard,none,68,60,53,96,0,65
250,male,group A,49,some high school,standard,completed,47,49,49,26,49,56
251,female,group D,38,some college,free/reduced,none,71,83,83,20,38,69
252,female,group B,86,some high school,standard,completed,60,70,70,23,86,9
253,male,group D,97,master's degree,standard,none,80,80,72,17,97,34
254,male,group D,66,high school,standard,none,54,52,52,97,66,47
255,female,group E,48,some college,standard,none,62,73,70,54,48,23
256,female,group C,44,associate's degree,free/reduced,none,64,73,68,81,44,12
257,male,group C,29,associate's degree,standard,completed,78,77,77,54,29,32
258,female,group B,79,some college,standard,none,70,75,78,15,79,59
259,female,group C,9,master's degree,free/reduced,completed,65,81,81,99,9,7
260,female,group C,37,some high school,free/reduced,completed,64,79,77,5,37,97
261,male,group C,45,some college,standard,completed,79,79,78,64,45,26
262,female,group C,28,some high school,free/reduced,none,44,50,51,0,28,53
263,female,group E,58,high school,standard,none,99,93,90,3,58,64
264,male,group D,37,high school,standard,none,76,73,68,88,37,54
265,male,group D,87,some high school,free/reduced,none,59,42,41,55,87,5
266,female,group C,48,bachelor's degree,standard,none,63,75,81,34,48,81
267,female,group D,4,high school,standard,none,69,72,77,25,4,3
268,female,group D,55,associate's degree,standard,completed,88,92,95,4,55,31
269,female,group E,12,some college,free/reduced,none,71,76,70,99,12,67
270,male,group C,48,bachelor's degree,standard,none,69,63,61,62,48,96
271,male,group C,100,some college,standard,none,58,49,42,98,100,23
272,female,group D,28,associate's degree,free/reduced,none,47,53,58,83,28,34
273,female,group D,36,some college,standard,none,65,70,71,34,36,15
274,male,group B,3,some college,standard,completed,88,85,76,58,3,34
275,male,group C,16,bachelor's degree,standard,none,83,78,73,78,16,1
276,female,group C,93,some high school,standard,completed,85,92,93,47,93,35
277,female,group E,27,high school,standard,completed,59,63,75,71,27,37
278,female,group C,22,some high school,free/reduced,none,65,86,80,68,22,39

# Math Operations

## Operations in columns

In [60]:
# select a column and sum
df_exams['math score'].sum()

np.int64(66089)

In [61]:
# count, mean, std, max, min
print(df_exams['math score'].count(),
      df_exams['math score'].mean(),
      df_exams['math score'].std(),
      df_exams['math score'].max(),
      df_exams['math score'].min())

1000 66.089 15.16308009600945 100 0

In [62]:
df_exams.describe()

,test,math score,reading score,writing score,Language Score,score1,score2
count,1000.000000,1000.00000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000
mean,50.327000,66.08900,69.169000,68.054000,49.68600,50.327000,49.805000
std,29.858761,15.16308,14.600192,15.195657,28.79487,29.858761,29.446291
min,0.000000,0.00000,17.000000,10.000000,0.00000,0.000000,0.000000
25%,24.000000,57.00000,59.000000,57.750000,23.00000,24.000000,24.750000
50%,50.000000,66.00000,70.000000,69.000000,51.00000,50.000000,50.000000
75%,77.000000,77.00000,79.000000,79.000000,73.25000,77.000000,75.000000
max,100.000000,100.00000,100.000000,100.000000,100.00000,100.000000,100.000000

## Operations in rows

In [64]:
# calculating the sum in a row
df_exams['math score'] + df_exams['reading score'] + df_exams['writing score']

0      218
1      247
2      278
3      148
4      229
5      232
6      275
7      122
8      195
9      148
10     164
11     135
12     219
13     220
14     161
15     222
16     263
17      78
18     134
19     173
20     198
21     210
22     151
23     215
24     225
25     219
26     178
27     211
28     205
29     207
30     217
31     189
32     193
33     120
34     266
35     241
36     238
37     173
38     253
39     170
40     170
41     199
42     176
43     190
44     160
45     176
46     182
47     213
48     207
49     248
50     156
51     214
52     139
53     241
54     242
55     117
56     253
57     156
58     175
59      27
60     225
61     112
62     178
63     220
64     176
65     192
66     119
67     206
68     175
69     160
70     194
71     181
72     140
73     174
74     139
75     123
76      78
77     239
78     207
79     198
80     146
81     139
82     151
83     199
84     115
85     235
86     247
87     216
88     195
89     241
90     211
91      97
92     221
93     138
94     257
95     241
96     193
97     205
98     187
99     194
100    213
101    216
102    265
103    151
104    274
105    197
106    287
107    193
108    198
109    206
110    264
111    166
112    154
113    163
114    299
115    235
116    242
117    239
118    175
119    189
120    260
121    272
122    274
123    176
124    236
125    268
126    207
127    216
128    238
129    151
130    255
131    130
132    231
133    240
134    228
135    161
136    146
137    181
138    192
139    201
140    219
141    185
142    151
143    147
144    239
145     94
146    247
147    207
148    224
149    293
150    198
151    212
152    195
153    150
154    190
155    247
156    218
157    180
158    234
159    192
160    234
161    248
162    154
163    154
164    264
165    296
166    155
167    212
168    229
169    212
170    219
171    260
172    246
173    200
174    148
175    259
176    158
177    225
178    184
179    297
180    205
181    176
182    147
183    204
184    146
185    197
186    221
187    196
188    145
189    252
190    200
191    238
192    192
193    201
194    238
195    168
196    193
197    162
198    153
199    233
200    237
201    223
202    215
203    194
204    142
205    223
206    206
207    237
208    231
209    185
210    238
211     90
212    164
213    167
214    259
215    242
216    257
217    115
218    213
219    173
220    198
221    245
222    182
223    241
224    191
225    155
226    215
227    161
228    204
229    277
230    206
231    131
232    236
233    257
234    249
235    232
236    196
237    198
238    157
239    244
240    207
241    246
242    163
243    153
244    218
245    232
246    239
247    196
248    191
249    181
250    145
251    237
252    200
253    232
254    158
255    205
256    205
257    232
258    223
259    227
260    220
261    236
262    145
263    282
264    217
265    142
266    219
267    218
268    275
269    217
270    193
271    149
272    158
273    206
274    249
275    234
276    270
277    197
278    231
279    186
280    147
281    139
282    236
283    226
284    129
285    245
286    267
287    238
288    239
289    230
290    214
291    229
292    180
293    213
294    235
295    189
296    130
297    213
298    136
299    252
300    240
301    162
302    232
303    220
304    232
305    205
306    267
307    147
308    191
309    158
310    229
311    183
312    196
313    204
314    198
315    202
316    250
317    233
318    203
319    184
320    230
321    240
322    232
323    149
324    130
325    266
326    184
327     70
328    234
329    147
330    192
331    119
332    171
333    249
334    271
335    195
336    215
337    143
338     89
339    150
340    171
341    197
342    219
343    206
344    219
345    227
346    180
347    266
348    215
349    237
350    186
351    175
352    221
353    161
354    200
355    203
356    185
357    177
358    182
359    259
360    179
361    247
362    168
363     93
364    177
365    167
366    180
367    188
368    166
369    242
370    232
371    188
372    220
373    275
374    202
375    130
376    252
377    280
378    231
379    192
380    249
381    282
382    231
383    132
384    124
385    218
386    207
387    202
388    190
389    218
390    199
391    222
392    210
393    167
394    216
395    134
396    180
397    269
398    194
399    173
400    180
401    139
402    169
403    287
404    175
405    204
406    193
407    239
408    165
409    256
410    215
411    245
412    197
413    197
414    202
415    226
416    213
417    214
418    189
419    167
420    268
421    179
422    172
423    224
424    114
425    191
426    255
427    205
428    177
429    185
430    189
431    203
432    172
433    156
434    205
435    151
436    207
437    214
438    177
439    259
440    227
441    239
442    201
443    232
444    234
445    218
446    195
447    247
448    135
449    226
450    234
451    289
452    216
453    172
454    176
455    140
456    257
457    155
458    300
459    205
460    166
461    153
462    217
463    258
464    195
465    262
466     95
467    204
468    250
469    241
470    258
471    206
472    238
473    187
474    271
475    230
476    204
477    220
478    189
479    214
480    212
481    167
482    197
483    157
484    155
485    215
486    164
487    209
488    174
489    243
490    226
491    198
492    256
493    259
494    186
495    198
496    154
497    213
498    203
499    219
500    235
501    273
502    178
503    276
504    153
505    244
506    204
507    168
508    234
509    265
510    220
511    157
512    163
513    177
514    268
515    248
516    247
517    213
518    222
519    224
520    172
521    261
522    184
523    163
524    154
525    187
526    177
527    132
528    117
529    206
530    208
531    154
532    181
533    261
534    210
535    232
536    169
537    179
538    222
539    275
540    212
541    241
542    237
543    266
544    193
545    241
546    289
547    203
548    193
549    220
550    220
551    265
552    138
553    203
554    138
555    104
556    206
557    194
558    193
559    201
560    228
561    211
562    278
563    223
564    145
565    136
566    292
567    210
568    158
569    203
570    216
571    279
572    171
573    180
574    226
575    148
576    164
577    261
578    162
579    182
580    274
581    236
582    214
583    228
584    223
585    217
586    201
587    169
588    183
589    179
590    169
591    183
592    200
593    223
594    291
595    207
596     69
597    155
598    219
599    228
600    177
601     88
602    234
603    168
604    263
605    209
606    251
607    152
608    187
609    186
610    192
611    183
612    275
613    216
614    268
615    200
616    120
617    249
618    260
619    206
620    150
621    181
622    161
623    282
624    181
625    296
626    202
627    155
628    152
629    150
630    201
631    204
632    221
633    248
634    248
635    209
636    228
637    260
638    236
639    223
640    144
641    252
642    232
643    233
644    195
645    227
646    194
647    194
648    158
649    229
650    160
651    224
652    269
653    209
654    231
655    196
656    208
657    196
658    161
659    262
660    224
661    202
662    195
663    201
664    206
665    170
666    207
667    249
668    208
669    230
670    210
671    159
672    223
673    233
674    224
675    180
676    227
677    228
678    234
679    184
680    213
681    188
682    171
683    113
684    196
685    293
686    228
687    228
688    155
689    266
690    155
691    227
692    221
693    227
694    168
695    254
696    247
697    201
698    214
699    191
700    242
701    196
702    258
703    194
704    186
705    199
706    116
707    177
708    255
709    161
710    267
711    250
712    297
713    246
714    204
715    257
716    223
717    291
718    226
719    244
720    204
721    173
722    252
723    140
724    131
725    226
726    217
727    176
728    249
729    129
730    225
731    144
732    270
733    146
734    168
735    183
736    255
737    192
738    225
739    176
740    225
741    150
742    247
743    204
744    157
745    225
746    215
747    201
748    169
749    257
750    208
751    205
752    231
753    252
754    166
755    271
756    165
757    210
758    176
759    223
760    189
761    160
762    245
763    187
764    182
765    218
766    210
767    198
768    214
769    175
770    149
771    222
772    191
773    219
774    191
775    162
776    208
777    122
778    233
779    261
780    159
781    251
782    243
783    173
784    251
785    127
786    228
787     89
788    194
789    178
790    170
791    196
792    209
793    250
794    145
795    198
796    210
797    235
798    183
799    164
800    208
801    229
802    276
803    254
804    227
805    230
806    213
807    126
808    234
809    164
810    118
811    141
812    185
813    247
814    235
815    267
816    168
817    207
818    200
819    256
820    267
821    261
822    152
823    240
824    158
825    187
826    194
827    210
828    236
829    175
830    178
831    249
832    182
833    248
834    153
835    198
836    194
837    236
838    168
839    216
840    137
841    173
842    103
843    227
844    169
845    259
846    261
847    168
848    199
849    224
850    205
851    192
852    265
853    210
854    181
855    290
856    208
857    225
858    147
859    232
860    168
861    254
862    119
863    222
864    281
865    252
866    164
867    144
868    224
869    151
870    164
871    218
872    244
873    262
874    166
875    210
876    247
877    172
878    211
879    214
880    193
881    211
882    208
883    145
884    156
885    218
886    288
887    185
888    208
889    143
890    262
891    262
892    190
893    237
894    190
895    104
896     92
897    220
898    184
899    225
900    258
901    225
902    123
903    293
904    235
905    242
906    156
907    254
908    214
909    204
910    140
911    235
912    179
913    175
914    162
915    204
916    300
917    157
918    214
919    278
920    206
921    134
922    204
923    184
924    213
925    198
926    172
927    197
928    133
929    155
930    211
931    181
932    205
933    219
934    275
935    191
936    177
937    172
938    251
939    214
940    210
941    265
942    211
943    184
944    187
945    173
946    244
947    167
948    151
949    205
950    238
951    235
952    220
953    164
954    200
955    191
956    252
957    292
958    167
959    227
960    178
961    155
962    300
963    216
964    187
965    204
966    198
967    186
968    211
969    239
970    289
971    219
972    163
973    175
974    184
975    223
976    182
977    185
978    144
979    280
980     55
981    237
982    250
983    256
984    231
985    162
986    150
987    232
988    134
989    236
990    242
991    225
992    207
993    208
994    188
995    282
996    172
997    195
998    223
999    249
dtype: int64

In [68]:
# calculating the average score
df_exams['average score'] = (df_exams['math score'] + df_exams['reading score'] + df_exams['writing score']) / 3
df_exams.round(2)

,gender,race/ethnicity,test,parental level of education,lunch,test preparation course,math score,reading score,writing score,Language Score,score1,score2,average score
0,female,group B,63,bachelor's degree,standard,none,72,72,74,34,63,100,72.67
1,female,group C,80,some college,standard,completed,69,90,88,71,80,11,82.33
2,female,group B,20,master's degree,standard,none,90,95,93,75,20,27,92.67
3,male,group A,32,associate's degree,free/reduced,none,47,57,44,86,32,6,49.33
4,male,group C,52,some college,standard,none,76,78,75,44,52,19,76.33
5,female,group B,15,associate's degree,standard,none,71,83,78,30,15,6,77.33
6,female,group B,67,some college,standard,completed,88,95,92,15,67,74,91.67
7,male,group B,73,some college,free/reduced,none,40,43,39,70,73,21,40.67
8,male,group D,8,high school,free/reduced,completed,64,64,67,56,8,51,65.00
9,female,group B,100,high school,free/reduced,none,38,60,50,81,100,50,49.33
10,male,group C,81,associate's degree,standard,none,58,54,52,76,81,13,54.67
11,male,group D,17,associate's degree,standard,none,40,52,43,43,17,42,45.00
12,female,group B,26,high school,standard,none,65,81,73,36,26,78,73.00
13,male,group A,20,some college,standard,completed,78,72,70,11,20,24,73.33
14,female,group A,0,master's degree,standard,none,50,53,58,43,0,94,53.67
15,female,group C,14,some high school,standard,none,69,75,78,67,14,64,74.00
16,male,group C,1,high school,standard,none,88,89,86,40,1,13,87.67
17,female,group B,64,some high school,free/reduced,none,18,32,28,90,64,94,26.00
18,male,group C,86,master's degree,free/reduced,completed,46,42,46,33,86,44,44.67
19,female,group C,13,associate's degree,free/reduced,none,54,58,61,98,13,27,57.67
20,male,group D,71,high school,standard,none,66,69,63,93,71,1,66.00
21,female,group B,67,some college,free/reduced,completed,65,75,70,58,67,65,70.00
22,male,group D,10,some college,standard,none,44,54,53,18,10,80,50.33
23,female,group C,63,some high school,standard,none,69,73,73,83,63,23,71.67
24,male,group D,94,bachelor's degree,free/reduced,completed,74,71,80,51,94,46,75.00
25,male,group A,22,master's degree,free/reduced,none,73,74,72,19,22,1,73.00
26,male,group B,29,some college,standard,none,69,54,55,1,29,42,59.33
27,female,group C,56,bachelor's degree,standard,none,67,69,75,11,56,54,70.33
28,male,group C,18,high school,standard,none,70,70,65,79,18,82,68.33
29,female,group D,39,master's degree,standard,none,62,70,75,2,39,1,69.00
30,female,group D,89,some college,standard,none,69,74,74,21,89,88,72.33
31,female,group B,51,some college,standard,none,63,65,61,94,51,49,63.00
32,female,group E,83,master's degree,free/reduced,none,56,72,65,9,83,99,64.33
33,male,group D,91,some college,standard,none,40,42,38,9,91,2,40.00
34,male,group E,6,some college,standard,none,97,87,82,49,6,27,88.67
35,male,group E,20,associate's degree,standard,completed,81,81,79,15,20,40,80.33
36,female,group D,77,associate's degree,standard,none,74,81,83,57,77,14,79.33
37,female,group D,3,some high school,free/reduced,none,50,64,59,33,3,20,57.67
38,female,group D,12,associate's degree,free/reduced,completed,75,90,88,6,12,100,84.33
39,male,group B,4,associate's degree,free/reduced,none,57,56,57,57,4,34,56.67
40,male,group C,68,associate's degree,free/reduced,none,55,61,54,34,68,70,56.67
41,female,group C,46,associate's degree,standard,none,58,73,68,12,46,99,66.33
42,female,group B,64,associate's degree,standard,none,53,58,65,41,64,43,58.67
43,male,group B,0,some college,free/reduced,completed,59,65,66,38,0,34,63.33
44,female,group E,81,associate's degree,free/reduced,none,50,56,54,98,81,35,53.33
45,male,group B,0,associate's degree,standard,none,65,54,57,10,0,67,58.67
46,female,group A,41,associate's degree,standard,completed,55,65,62,47,41,85,60.67
47,female,group C,22,high school,standard,none,66,71,76,87,22,38,71.00
48,female,group D,63,associate's degree,free/reduced,completed,57,74,76,55,63,22,69.00
49,male,group C,100,high school,standard,completed,82,84,82,37,100,34,82.67
50,male,group E,42,some college,standard,none,53,55,48,56,42,74,52.00
51,male,group E,56,associate's degree,free/reduced,completed,77,69,68,15,56,56,71.33
52,male,group C,94,some college,standard,none,53,44,42,34,94,94,46.33
53,male,group D,49,high school,standard,none,88,78,75,1,49,33,80.33
54,female,group C,72,some high school,free/reduced,completed,71,84,87,24,72,76,80.67
55,female,group C,94,high school,free/reduced,none,33,41,43,72,94,23,39.00
56,female,group E,52,associate's degree,standard,completed,82,85,86,24,52,93,84.33
57,male,group D,99,associate's degree,standard,none,52,55,49,43,99,96,52.00
58,male,group D,88,some college,standard,completed,58,59,58,18,88,39,58.33
59,female,group C,49,some high school,free/reduced,none,0,17,10,81,49,6,9.00
60,male,group E,31,bachelor's degree,free/reduced,completed,79,74,72,67,31,53,75.00
61,male,group A,61,some high school,free/reduced,none,39,39,34,99,61,86,37.33
62,male,group A,6,associate's degree,free/reduced,none,62,61,55,3,6,20,59.33
63,female,group C,43,associate's degree,standard,none,69,80,71,52,43,4,73.33
64,female,group D,9,some high school,standard,none,59,58,59,68,9,38,58.67
65,male,group B,11,some high school,standard,none,67,64,61,33,11,2,64.00
66,male,group D,76,some high school,free/reduced,none,45,37,37,62,76,68,39.67
67,female,group C,18,some college,standard,none,60,72,74,92,18,65,68.67
68,male,group B,66,associate's degree,free/reduced,none,61,58,56,99,66,24,58.33
69,female,group C,99,associate's degree,standard,none,39,64,57,91,99,98,53.33
70,female,group D,33,some college,free/reduced,completed,58,63,73,73,33,60,64.67
71,male,group D,63,some college,standard,completed,63,55,63,67,63,50,60.33
72,female,group A,32,associate's degree,free/reduced,none,41,51,48,10,32,39,46.67
73,male,group C,34,some high school,free/reduced,none,61,57,56,39,34,56,58.00
74,male,group C,52,some high school,standard,none,49,49,41,30,52,12,46.33
75,male,group B,16,associate's degree,free/reduced,none,44,41,38,16,16,38,41.00
76,male,group E,58,some high school,standard,none,30,26,22,75,58,86,26.00
77,male,group A,40,bachelor's degree,standard,completed,80,78,81,52,40,3,79.67
78,female,group D,78,some high school,standard,completed,61,74,72,53,78,2,69.00
79,female,group E,58,master's degree,standard,none,62,68,68,100,58,42,66.00
80,female,group B,96,associate's degree,standard,none,47,49,50,4,96,98,48.67
81,male,group B,80,high school,free/reduced,none,49,45,45,97,80,34,46.33
82,male,group A,97,some college,free/reduced,completed,50,47,54,73,97,16,50.33
83,male,group E,47,associate's degree,standard,none,72,64,63,30,47,92,66.33
84,male,group D,98,high school,free/reduced,none,42,39,34,54,98,16,38.33
85,female,group C,24,some college,standard,none,73,80,82,50,24,87,78.33
86,female,group C,38,some college,free/reduced,none,76,83,88,67,38,46,82.33
87,female,group D,58,associate's degree,standard,none,71,71,74,80,58,87,72.00
88,female,group A,62,some college,standard,none,58,70,67,65,62,79,65.00
89,female,group D,3,some high school,standard,none,73,86,82,47,3,47,80.33
90,female,group C,80,bachelor's degree,standard,none,65,72,74,4,80,63,70.33
91,male,group C,41,high school,free/reduced,none,27,34,36,23,41,100,32.33
92,male,group C,72,high school,standard,none,71,79,71,69,72,97,73.67
93,male,group C,8,associate's degree,free/reduced,completed,43,45,50,86,8,58,46.00
94,female,group B,5,some college,standard,none,79,86,92,48,5,66,85.67
95,male,group C,34,associate's degree,free/reduced,completed,78,81,82,72,34,87,80.33
96,male,group B,94,some high school,standard,completed,65,66,62,45,94,67,64.33
97,female,group E,11,some college,standard,completed,63,72,70,59,11,10,68.33
98,female,group D,93,some college,free/reduced,none,58,67,62,94,93,35,62.33
99,female,group D,54,bachelor's degree,standard,none,65,67,62,34,54,74,64.67
100,male,group B,88,some college,standard,none,79,67,67,96,88,71,71.00
101,male,group D,47,bachelor's degree,standard,completed,68,74,74,84,47,49,72.00
102,female,group D,22,associate's degree,standard,none,85,91,89,36,22,9,88.33
103,male,group B,23,high school,standard,completed,60,44,47,9,23,80,50.33
104,male,group C,2,some college,standard,completed,98,86,90,43,2,79,91.33
105,female,group C,30,some college,standard,none,58,67,72,86,30,12,65.67
106,female,group D,75,master's degree,standard,none,87,100,100,15,75,25,95.67
107,male,group E,4,associate's degree,standard,completed,66,63,64,92,4,87,64.33
108,female,group B,76,associate's degree,free/reduced,none,52,76,70,36,76,13,66.00
109,female,group B,87,some high school,standard,none,70,64,72,6,87,52,68.67
110,female,group D,67,associate's degree,free/reduced,completed,77,89,98,87,67,76,88.00
111,male,group C,50,high school,standard,none,62,55,49,55,50,32,55.33
112,male,group A,45,associate's degree,standard,none,54,53,47,34,45,82,51.33
113,female,group D,80,some college,standard,none,51,58,54,98,80,88,54.33
114,female,group E,2,bachelor's degree,standard,completed,99,100,100,37,2,54,99.67
115,male,group C,82,high school,standard,none,84,77,74,47,82,85,78.33
116,female,group B,5,bachelor's degree,free/reduced,none,75,85,82,28,5,45,80.67
117,female,group D,26,bachelor's degree,standard,none,78,82,79,42,26,69,79.67
118,female,group D,70,some high school,standard,none,51,63,61,34,70,24,58.33
119,female,group C,29,some college,standard,none,55,69,65,13,29,75,63.00
120,female,group C,19,bachelor's degree,standard,completed,79,92,89,79,19,49,86.67
121,male,group B,45,associate's degree,standard,completed,91,89,92,17,45,18,90.67
122,female,group C,6,some college,standard,completed,88,93,93,27,6,55,91.33
123,male,group D,26,high school,free/reduced,none,63,57,56,47,26,40,58.67
124,male,group E,11,some college,standard,none,83,80,73,73,11,0,78.67
125,female,group B,7,high school,standard,none,87,95,86,62,7,62,89.33
126,male,group B,22,some high school,standard,none,72,68,67,59,22,60,69.00
127,male,group D,8,some college,standard,completed,65,77,74,12,8,30,72.00
128,male,group D,63,master's degree,standard,none,82,82,74,38,63,48,79.33
129,female,group A,14,bachelor's degree,standard,none,51,49,51,75,14,80,50.33
130,male,group D,15,master's degree,standard,none,89,84,82,96,15,51,85.00
131,male,group C,84,some high school,free/reduced,completed,53,37,40,23,84,70,43.33
132,male,group E,39,some college,free/reduced,completed,87,74,70,63,39,70,77.00
133,female,group C,44,some college,standard,completed,75,81,84,93,44,32,80.00
134,male,group D,59,bachelor's degree,free/reduced,completed,74,79,75,91,59,40,76.00
135,male,group C,13,bachelor's degree,standard,none,58,55,48,66,13,63,53.67
136,male,group B,85,some high school,standard,completed,51,54,41,42,85,20,48.67
137,male,group E,83,high school,standard,none,70,55,56,29,83,6,60.33
138,female,group C,0,associate's degree,standard,none,59,66,67,83,0,42,64.00
139,male,group D,62,some college,standard,completed,71,61,69,25,62,61,67.00
140,female,group D,47,some high school,standard,none,76,72,71,31,47,78,73.00
141,female,group C,21,some college,free/reduced,none,59,62,64,15,21,4,61.67
142,female,group E,37,some college,free/reduced,completed,42,55,54,86,37,91,50.33
143,male,group A,67,high school,standard,none,57,43,47,79,67,64,49.00
144,male,group D,74,some college,standard,none,88,73,78,34,74,25,79.67
145,female,group C,94,some college,free/reduced,none,22,39,33,12,94,58,31.33
146,male,group B,3,some high school,standard,none,88,84,75,6,3,74,82.33
147,male,group C,99,associate's degree,free/reduced,none,73,68,66,24,99,11,69.00
148,female,group D,61,bachelor's degree,standard,completed,68,75,81,86,61,2,74.67
149,male,group E,83,associate's degree,free/reduced,completed,100,100,93,74,83,62,97.67
150,male,group A,56,some high school,standard,completed,62,67,69,58,56,84,66.00
151,male,group A,55,bachelor's degree,standard,none,77,67,68,18,55,73,70.67
152,female,group B,38,associate's degree,standard,completed,59,70,66,37,38,100,65.00
153,male,group D,87,bachelor's degree,standard,none,54,49,47,38,87,40,50.00
154,male,group D,17,some high school,standard,none,62,67,61,3,17,96,63.33
155,female,group C,22,some college,standard,completed,70,89,88,73,22,6,82.33
156,female,group E,16,high school,free/reduced,completed,66,74,78,40,16,54,72.67
157,male,group B,95,some college,free/reduced,none,60,60,60,69,95,43,60.00
158,female,group B,76,associate's degree,standard,completed,61,86,87,30,76,5,78.00
159,male,group D,60,associate's degree,free/reduced,none,66,62,64,61,60,90,64.00
160,male,group B,60,associate's degree,free/reduced,completed,82,78,74,25,60,42,78.00
161,female,group E,69,some college,free/reduced,completed,75,88,85,71,69,93,82.67
162,male,group B,55,master's degree,free/reduced,none,49,53,52,54,55,16,51.33
163,male,group C,57,high school,standard,none,52,53,49,33,57,60,51.33
164,female,group E,8,master's degree,standard,none,81,92,91,70,8,51,88.00
165,female,group C,80,bachelor's degree,standard,completed,96,100,100,58,80,81,98.67
166,male,group C,23,high school,free/reduced,completed,53,51,51,43,23,94,51.67
167,female,group B,93,master's degree,free/reduced,completed,58,76,78,6,93,24,70.67
168,female,group B,15,high school,standard,completed,68,83,78,78,15,28,76.33
169,female,group C,35,some college,free/reduced,completed,67,75,70,12,35,21,70.67
170,male,group A,31,high school,standard,completed,72,73,74,15,31,92,73.00
171,male,group E,18,some high school,standard,none,94,88,78,76,18,61,86.67
172,female,group D,54,some college,standard,none,79,86,81,9,54,36,82.00
173,female,group C,25,associate's degree,standard,none,63,67,70,31,25,30,66.67
174,female,group C,88,bachelor's degree,free/reduced,completed,43,51,54,74,88,23,49.33
175,female,group C,74,master's degree,standard,completed,81,91,87,58,74,8,86.33
176,female,group B,89,high school,free/reduced,completed,46,54,58,51,89,33,52.67
177,female,group C,32,associate's degree,standard,completed,71,77,77,75,32,12,75.00
178,female,group B,18,master's degree,free/reduced,completed,52,70,62,82,18,92,61.33
179,female,group D,45,some high school,standard,completed,97,100,100,15,45,43,99.00
180,male,group C,18,master's degree,free/reduced,completed,62,68,75,20,18,10,68.33
181,female,group C,9,some college,free/reduced,none,46,64,66,13,9,40,58.67
182,female,group E,61,high school,standard,none,50,50,47,13,61,54,49.00
183,female,group D,90,associate's degree,standard,none,65,69,70,43,90,98,68.00
184,male,group C,42,some high school,free/reduced,completed,45,52,49,26,42,25,48.67
185,male,group C,17,associate's degree,free/reduced,completed,65,67,65,57,17,7,65.67
186,male,group E,23,high school,standard,none,80,76,65,57,23,23,73.67
187,male,group D,38,some high school,standard,completed,62,66,68,92,38,18,65.33
188,male,group B,95,some high school,free/reduced,none,48,52,45,53,95,42,48.33
189,female,group C,65,bachelor's degree,standard,none,77,88,87,16,65,81,84.00
190,female,group E,95,associate's degree,standard,none,66,65,69,8,95,73,66.67
191,male,group D,51,some college,standard,completed,76,83,79,17,51,64,79.33
192,female,group B,82,some high school,standard,none,62,64,66,17,82,46,64.00
193,male,group D,1,some college,standard,completed,77,62,62,12,1,60,67.00
194,female,group C,42,master's degree,standard,completed,69,84,85,70,42,59,79.33
195,male,group D,26,associate's degree,standard,none,61,55,52,86,26,90,56.00
196,male,group C,7,some high school,free/reduced,completed,59,69,65,13,7,15,64.33
197,male,group E,28,high school,free/reduced,none,55,56,51,64,28,20,54.00
198,female,group B,64,some college,free/reduced,none,45,53,55,71,64,33,51.00
199,female,group B,74,bachelor's degree,free/reduced,none,78,79,76,99,74,65,77.67
200,female,group C,85,associate's degree,standard,completed,67,84,86,82,85,7,79.00
201,female,group D,87,some college,free/reduced,none,65,81,77,38,87,43,74.33
202,male,group C,45,associate's degree,standard,none,69,77,69,28,45,81,71.67
203,female,group B,40,associate's degree,standard,none,57,69,68,18,40,6,64.67
204,male,group C,25,some college,standard,none,59,41,42,69,25,89,47.33
205,male,group D,49,some high school,standard,completed,74,71,78,77,49,56,74.33
206,male,group E,21,bachelor's degree,standard,none,82,62,62,44,21,29,68.67
207,male,group E,29,high school,standard,completed,81,80,76,21,29,53,79.00
208,female,group B,9,some college,free/reduced,none,74,81,76,54,9,13,77.00
209,female,group B,43,some college,free/reduced,none,58,61,66,100,43,71,61.67
210,male,group D,55,some high school,free/reduced,completed,80,79,79,79,55,92,79.33
211,male,group C,22,some college,free/reduced,none,35,28,27,20,22,65,30.00
212,female,group C,33,high school,free/reduced,none,42,62,60,57,33,63,54.67
213,male,group C,30,associate's degree,free/reduced,completed,60,51,56,48,30,71,55.67
214,male,group E,93,high school,standard,completed,87,91,81,74,93,77,86.33
215,male,group B,50,some high school,standard,completed,84,83,75,94,50,3,80.67
216,female,group E,7,associate's degree,free/reduced,completed,83,86,88,26,7,99,85.67
217,female,group C,76,high school,free/reduced,none,34,42,39,97,76,59,38.33
218,male,group B,69,high school,free/reduced,none,66,77,70,69,69,69,71.00
219,male,group B,50,some high school,standard,completed,61,56,56,64,50,41,57.67
220,female,group D,27,high school,standard,completed,56,68,74,63,27,30,66.00
221,male,group B,55,associate's degree,standard,none,87,85,73,97,55,66,81.67
222,female,group C,81,some high school,free/reduced,none,55,65,62,41,81,1,60.67
223,male,group D,69,some high school,standard,none,86,80,75,81,69,55,80.33
224,female,group B,25,associate's degree,standard,completed,52,66,73,13,25,22,63.67
225,female,group E,70,master's degree,free/reduced,none,45,56,54,5,70,47,51.67
226,female,group C,20,some college,standard,none,72,72,71,83,20,46,71.67
227,male,group D,26,high school,standard,none,57,50,54,44,26,100,53.67
228,male,group A,75,some high school,free/reduced,none,68,72,64,70,75,45,68.00
229,female,group C,69,some college,standard,completed,88,95,94,38,69,16,92.33
230,male,group D,95,some college,standard,none,76,64,66,18,95,90,68.67
231,male,group C,19,associate's degree,standard,none,46,43,42,87,19,80,43.67
232,female,group B,81,bachelor's degree,standard,none,67,86,83,90,81,45,78.67
233,male,group E,96,some high school,standard,none,92,87,78,2,96,31,85.67
234,male,group C,57,bachelor's degree,standard,completed,83,82,84,22,57,6,83.00
235,male,group D,24,associate's degree,standard,none,80,75,77,65,24,73,77.33
236,male,group D,0,bachelor's degree,free/reduced,none,63,66,67,84,0,47,65.33
237,female,group D,38,some high school,standard,completed,64,60,74,100,38,20,66.00
238,male,group B,33,some college,standard,none,54,52,51,31,33,2,52.33
239,male,group C,9,associate's degree,standard,none,84,80,80,16,9,40,81.33
240,male,group D,40,high school,free/reduced,completed,73,68,66,92,40,95,69.00
241,female,group E,67,bachelor's degree,standard,none,80,83,83,41,67,47,82.00
242,female,group D,100,high school,standard,none,56,52,55,92,100,100,54.33
243,male,group E,100,some college,standard,none,59,51,43,61,100,11,51.00
244,male,group D,87,some high school,standard,none,75,74,69,86,87,24,72.67
245,male,group C,19,associate's degree,standard,none,85,76,71,8,19,45,77.33
246,male,group E,91,associate's degree,standard,none,89,76,74,95,91,4,79.67
247,female,group B,74,high school,standard,completed,58,70,68,43,74,20,65.33
248,female,group B,28,high school,standard,none,65,64,62,33,28,60,63.67
249,male,group C,0,high school,standard,none,68,60,53,96,0,65,60.33
250,male,group A,49,some high school,standard,completed,47,49,49,26,49,56,48.33
251,female,group D,38,some college,free/reduced,none,71,83,83,20,38,69,79.00
252,female,group B,86,some high school,standard,completed,60,70,70,23,86,9,66.67
253,male,group D,97,master's degree,standard,none,80,80,72,17,97,34,77.33
254,male,group D,66,high school,standard,none,54,52,52,97,66,47,52.67
255,female,group E,48,some college,standard,none,62,73,70,54,48,23,68.33
256,female,group C,44,associate's degree,free/reduced,none,64,73,68,81,44,12,68.33